/**
 * /api/recommend
 *
 * Session-aware hybrid retrieval + narrowing chat + RAG-grounded recommendation.
 *
 * Flow:
 *   1. Receive intakeForm + messages + sessionState
 *   2. If no sessionState → create session, run hybrid retrieval → initial candidatePool
 *   3. Run question engine on candidatePool
 *   4. If question → LLM polishes & returns question + chips + candidateSnapshot
 *   5. If resolved → build evidence-grounded recommendation
 *
 * Hallucination prevention:
 *   - Product codes, specs, stock, lead time NEVER generated by LLM
 *   - Cutting conditions ONLY from evidence-chunks.json
 *   - LLM only writes natural-language explanation of real results
 */

import { NextResponse } from "next/server"
import { normalizeInput, mergeInputs } from "@/lib/domain/input-normalizer"
import { runHybridRetrieval, classifyHybridResults } from "@/lib/domain/hybrid-retrieval"
import { selectNextQuestion, checkResolution, parseAnswerToFilter } from "@/lib/domain/question-engine"
import { buildDeterministicSummary, buildRationale, buildWarnings } from "@/lib/domain/summary-generator"
import { EvidenceRepo } from "@/lib/data/repos/evidence-repo"
import { getProvider } from "@/lib/llm/provider"
import {
  buildSystemPrompt,
  buildSessionContext,
  buildGreetingPrompt,
  buildNarrowingPrompt,
  buildResultPrompt,
  buildExplanationResultPrompt,
  buildIntentContext,
} from "@/lib/llm/prompt-builder"
import { resolveMaterialTag } from "@/lib/domain/material-resolver"
import { prepareRequest } from "@/lib/domain/request-preparation"
import { buildExplanation } from "@/lib/domain/explanation-builder"
import { runFactCheck } from "@/lib/domain/fact-checker"

import type { RecommendationInput, RecommendationResult, ScoredProduct, ChatMessage, MatchStatus } from "@/lib/types/canonical"
import type { ProductIntakeForm, AnswerState, MachiningIntent } from "@/lib/types/intake"
import type { ExplorationSessionState, AppliedFilter, NarrowingTurn, CandidateSnapshot } from "@/lib/types/exploration"
import type { EvidenceSummary } from "@/lib/types/evidence"
import type { FactCheckedRecommendation } from "@/lib/types/fact-check"
import type { RecommendationExplanation } from "@/lib/types/explanation"

export const maxDuration = 60

// ── POST Handler ─────────────────────────────────────────────
export async function POST(req: Request) {
  try {
    const body = await req.json()

    // Route: intake-based exploration flow
    if (body.intakeForm) {
      return handleExploration(
        body.intakeForm as ProductIntakeForm,
        body.messages ?? [],
        body.sessionState ?? null
      )
    }

    // Route: simple chat (legacy, kept for backward compat)
    return handleSimpleChat(body.messages ?? [], body.mode ?? "simple")

  } catch (err) {
    console.error("[recommend] Error:", err)
    return NextResponse.json({
      error: "internal_error",
      detail: err instanceof Error ? err.message : "Unknown error",
      text: "죄송합니다, 처리 중 오류가 발생했습니다. 다시 시도해주세요.",
      chips: ["처음부터 다시", "소재 입력", "직경 입력"],
      isComplete: false,
      recommendation: null,
      sessionState: null,
      evidenceSummaries: null,
      candidateSnapshot: null,
    }, { status: 500 })
  }
}

// ════════════════════════════════════════════════════════════════
// EXPLORATION HANDLER (session-aware hybrid retrieval + narrowing)
// ════════════════════════════════════════════════════════════════

async function handleExploration(
  form: ProductIntakeForm,
  messages: ChatMessage[],
  prevState: ExplorationSessionState | null
): Promise<Response> {
  const provider = getProvider()
  const baseInput = mapIntakeToInput(form)

  // ── Step 0: Request Preparation ────────────────────────────
  const filters: AppliedFilter[] = prevState?.appliedFilters ?? []
  const resolvedInput: RecommendationInput = prevState?.resolvedInput
    ? { ...baseInput, ...prevState.resolvedInput }
    : baseInput

  const hybridResult = runHybridRetrieval(resolvedInput, filters, 50)
  const candidates = hybridResult.candidates
  const evidenceMap = hybridResult.evidenceMap

  // Run request preparation engine
  const requestPrep = prepareRequest(form, messages, prevState, resolvedInput, candidates.length)
  console.log(`[recommend] Intent: ${requestPrep.intent} (${requestPrep.intentConfidence}), Route: ${requestPrep.route.action}`)

  // Handle reset
  if (requestPrep.route.action === "reset_session") {
    return NextResponse.json({
      text: "처음부터 다시 시작합니다. 새로운 조건을 입력해주세요.",
      purpose: "greeting",
      chips: ["처음부터 다시"],
      isComplete: true,
      recommendation: null,
      sessionState: null,
      evidenceSummaries: null,
      candidateSnapshot: null,
      extractedField: null,
      requestPreparation: requestPrep,
    })
  }

  // ── Step 2: Process user message (if any) ──────────────────
  const narrowingHistory: NarrowingTurn[] = prevState?.narrowingHistory ?? []
  let currentInput = { ...resolvedInput }
  let turnCount = prevState?.turnCount ?? 0

  // If there are messages and this isn't the first call
  if (messages.length > 0 && prevState) {
    const lastUserMsg = [...messages].reverse().find(m => m.role === "user")
    if (lastUserMsg) {
      // Try to extract parameters from user message
      const extracted = await extractParamsFromMessage(provider, lastUserMsg.text, currentInput, prevState)

      // Non-product input — handle as general conversation
      if (extracted === null) {
        const generalReply = await handleGeneralChat(provider, lastUserMsg.text, currentInput, candidates.length)
        if (generalReply) {
          return buildQuestionResponse(
            form, candidates, evidenceMap, currentInput,
            narrowingHistory, filters, turnCount, messages, provider,
            generalReply
          )
        }
        // Fallback: re-ask
        return buildQuestionResponse(
          form, candidates, evidenceMap, currentInput,
          narrowingHistory, filters, turnCount, messages, provider,
          `절삭공구 관련 조건을 알려주시거나, 아래 버튼을 선택해주세요.`
        )
      }

      if (extracted) {
        // Check for skip or complete signals
        if (extracted.isComplete) {
          // User wants results now — skip to recommendation
          return buildRecommendationResponse(
            form, candidates, evidenceMap, currentInput, narrowingHistory,
            filters, turnCount, messages, provider
          )
        }

        // Handle skipped field ("상관없음") — record in history so we don't re-ask
        if (extracted.skippedField) {
          const skipFilter: AppliedFilter = {
            field: extracted.skippedField,
            op: "skip",
            value: "상관없음",
            rawValue: "skip",
            appliedAt: turnCount,
          }

          narrowingHistory.push({
            question: "follow-up",
            answer: lastUserMsg.text,
            extractedFilters: [skipFilter],
            candidateCountBefore: candidates.length,
            candidateCountAfter: candidates.length, // no change
          })
          turnCount++

          // Check if we're resolved after skip
          const statusAfterSkip = checkResolution(candidates, narrowingHistory)
          if (statusAfterSkip.startsWith("resolved")) {
            return buildRecommendationResponse(
              form, candidates, evidenceMap, currentInput, narrowingHistory,
              filters, turnCount, messages, provider
            )
          }

          // Ask next question (which will be different since the field is now in history)
          return buildQuestionResponse(
            form, candidates, evidenceMap, currentInput,
            narrowingHistory, filters, turnCount, messages, provider
          )
        }

        // Apply extracted filters
        if (extracted.newFilter) {
          const filter = { ...extracted.newFilter, appliedAt: turnCount }
          filters.push(filter)

          // Update input based on filter
          currentInput = applyFilterToInput(currentInput, filter)

          // Re-run hybrid retrieval with new filter
          const newResult = runHybridRetrieval(currentInput, filters, 50)
          const newCandidates = newResult.candidates

          narrowingHistory.push({
            question: prevState.narrowingHistory?.length
              ? "follow-up"
              : "initial",
            answer: lastUserMsg.text,
            extractedFilters: [filter],
            candidateCountBefore: candidates.length,
            candidateCountAfter: newCandidates.length,
          })

          turnCount++

          // Check if we're resolved after applying the filter
          const newStatus = checkResolution(newCandidates, narrowingHistory)
          if (newStatus.startsWith("resolved")) {
            return buildRecommendationResponse(
              form, newCandidates, newResult.evidenceMap, currentInput,
              narrowingHistory, filters, turnCount, messages, provider
            )
          }

          // Ask next question based on new candidate pool
          return buildQuestionResponse(
            form, newCandidates, newResult.evidenceMap, currentInput,
            narrowingHistory, filters, turnCount, messages, provider
          )
        }
      }
    }
  }

  // ── Step 3: Determine what to do next ──────────────────────
  const status = checkResolution(candidates, narrowingHistory)

  if (status.startsWith("resolved") && turnCount > 0) {
    // Already resolved — show results
    return buildRecommendationResponse(
      form, candidates, evidenceMap, currentInput, narrowingHistory,
      filters, turnCount, messages, provider
    )
  }

  // Not resolved (or first call) — ask a question
  return buildQuestionResponse(
    form, candidates, evidenceMap, currentInput, narrowingHistory,
    filters, turnCount, messages, provider
  )
}

// ── Build Question Response ──────────────────────────────────
async function buildQuestionResponse(
  form: ProductIntakeForm,
  candidates: ScoredProduct[],
  evidenceMap: Map<string, EvidenceSummary>,
  input: RecommendationInput,
  history: NarrowingTurn[],
  filters: AppliedFilter[],
  turnCount: number,
  messages: ChatMessage[],
  provider: ReturnType<typeof getProvider>,
  overrideText?: string
): Promise<Response> {
  const question = selectNextQuestion(input, candidates, history)

  // Build session state for client
  const sessionState: ExplorationSessionState = {
    sessionId: `ses-${Date.now()}`,
    candidateCount: candidates.length,
    appliedFilters: filters,
    narrowingHistory: history,
    resolutionStatus: checkResolution(candidates, history),
    resolvedInput: input,
    turnCount,
    lastAskedField: question?.field ?? undefined,  // track which field we're asking about
  }

  // If no question (resolved or out of questions), go to recommendation
  if (!question) {
    return buildRecommendationResponse(
      form, candidates, evidenceMap, input, history,
      filters, turnCount, messages, provider
    )
  }

  // Build candidate snapshot for UI
  const candidateSnapshot = buildCandidateSnapshot(candidates, evidenceMap)

  // LLM-polish the question text (or use deterministic)
  let responseText = overrideText ?? question.questionText
  let chips = question.chips

  if (overrideText) {
    // Skip LLM polish when we have an override (e.g. irrelevant input nudge)
  } else if (provider.available() && messages.length === 0) {
    // First call: generate greeting
    try {
      const systemPrompt = buildSystemPrompt()
      const sessionCtx = buildSessionContext(form, sessionState, candidates.length)
      const greetingPrompt = buildGreetingPrompt(sessionCtx, question, candidates.length)

      const raw = await provider.complete(systemPrompt, [
        { role: "user", content: greetingPrompt }
      ], 400)

      const parsed = safeParseJSON(raw)
      if (parsed?.responseText) {
        responseText = parsed.responseText
      }
    } catch (e) {
      console.warn("[recommend] LLM greeting failed:", e)
    }
  } else if (provider.available() && messages.length > 0) {
    // Follow-up: polish the question
    try {
      const systemPrompt = buildSystemPrompt()
      const sessionCtx = buildSessionContext(form, sessionState, candidates.length)
      const raw = await provider.complete(systemPrompt, [
        { role: "user", content: `${sessionCtx}\n\n다음 질문을 자연스러운 한국어로 다듬어주세요: "${question.questionText}"\n현재 후보 ${candidates.length}개.\nJSON으로 응답: { "responseText": "...", "extractedParams": {}, "isComplete": false, "skipQuestion": false }` }
      ], 300)

      const parsed = safeParseJSON(raw)
      if (parsed?.responseText) {
        responseText = parsed.responseText
      }
    } catch (e) {
      console.warn("[recommend] LLM question polish failed:", e)
    }
  }

  // Run request preparation for metadata
  const requestPrep = prepareRequest(form, messages, sessionState, input, candidates.length)

  return NextResponse.json({
    text: responseText,
    purpose: messages.length === 0 ? "greeting" : "question",
    chips,
    isComplete: false,
    recommendation: null,
    sessionState,
    evidenceSummaries: null,
    candidateSnapshot,
    extractedField: null,
    requestPreparation: requestPrep,
    primaryExplanation: null,
    primaryFactChecked: null,
    altExplanations: [],
    altFactChecked: [],
  })
}

// ── Build Recommendation Response ────────────────────────────
async function buildRecommendationResponse(
  form: ProductIntakeForm,
  candidates: ScoredProduct[],
  evidenceMap: Map<string, EvidenceSummary>,
  input: RecommendationInput,
  history: NarrowingTurn[],
  filters: AppliedFilter[],
  turnCount: number,
  messages: ChatMessage[],
  provider: ReturnType<typeof getProvider>
): Promise<Response> {
  const { primary, alternatives, status } = classifyHybridResults({ candidates, evidenceMap, totalConsidered: candidates.length, filtersApplied: filters })
  const warnings = primary ? buildWarnings(primary, input) : ["조건에 맞는 제품을 찾지 못했습니다"]
  const rationale = primary ? buildRationale(primary, input) : []

  // Add intake-specific warnings
  if (form.material.status === "unknown") warnings.push("소재 미지정 — 전체 소재 대상 검색")
  if (form.diameterInfo.status === "unknown") warnings.push("직경 미지정 — 직경 기준 필터 없음")

  const deterministicSummary = buildDeterministicSummary({
    status,
    query: input,
    primaryProduct: primary,
    alternatives,
    warnings,
    rationale,
    sourceSummary: [],
    deterministicSummary: "",
    llmSummary: null,
    totalCandidatesConsidered: candidates.length,
  })

  // Build evidence summaries for top products
  const evidenceSummaries: EvidenceSummary[] = []
  if (primary) {
    const es = evidenceMap.get(primary.product.normalizedCode)
    if (es) evidenceSummaries.push(es)
  }
  for (const alt of alternatives) {
    const es = evidenceMap.get(alt.product.normalizedCode)
    if (es) evidenceSummaries.push(es)
  }

  // ── NEW: Build explanation + fact check for primary ────────
  let primaryExplanation: RecommendationExplanation | null = null
  let primaryFactChecked: FactCheckedRecommendation | null = null
  let altExplanations: RecommendationExplanation[] = []
  let altFactChecked: FactCheckedRecommendation[] = []

  if (primary) {
    const primaryEvidence = evidenceMap.get(primary.product.normalizedCode) ?? null
    primaryExplanation = buildExplanation(primary, input, primaryEvidence)
    primaryFactChecked = runFactCheck(primary, input, primaryEvidence, primaryExplanation)

    // Build explanations for alternatives too
    for (const alt of alternatives) {
      const altEvidence = evidenceMap.get(alt.product.normalizedCode) ?? null
      const altExpl = buildExplanation(alt, input, altEvidence)
      altExplanations.push(altExpl)
      altFactChecked.push(runFactCheck(alt, input, altEvidence, altExpl))
    }
  }

  const recommendation: RecommendationResult = {
    status,
    query: input,
    primaryProduct: primary,
    alternatives,
    warnings,
    rationale,
    sourceSummary: primary ? buildSourceSummary(primary) : [],
    deterministicSummary,
    llmSummary: null,
    totalCandidatesConsidered: candidates.length,
  }

  // LLM summary with explanation-aware prompt
  if (provider.available() && primary && primaryFactChecked && primaryExplanation) {
    try {
      const systemPrompt = buildSystemPrompt()
      const sessionState: ExplorationSessionState = {
        sessionId: `ses-${Date.now()}`,
        candidateCount: candidates.length,
        appliedFilters: filters,
        narrowingHistory: history,
        resolutionStatus: checkResolution(candidates, history),
        resolvedInput: input,
        turnCount,
      }
      const sessionCtx = buildSessionContext(form, sessionState, candidates.length)

      // Use new explanation-aware prompt
      const resultPrompt = buildExplanationResultPrompt(
        sessionCtx,
        primaryFactChecked,
        primaryExplanation,
        alternatives.map(a => ({ displayCode: a.product.displayCode, matchStatus: a.matchStatus, score: a.score })),
        warnings
      )

      const raw = await provider.complete(systemPrompt, [
        { role: "user", content: resultPrompt }
      ], 600)

      const parsed = safeParseJSON(raw)
      if (parsed?.responseText) {
        recommendation.llmSummary = parsed.responseText as string
      } else if (raw.trim()) {
        recommendation.llmSummary = raw.trim()
      }
    } catch (e) {
      console.warn("[recommend] LLM result summary failed:", e)
    }
  }

  const sessionState: ExplorationSessionState = {
    sessionId: `ses-${Date.now()}`,
    candidateCount: candidates.length,
    appliedFilters: filters,
    narrowingHistory: history,
    resolutionStatus: checkResolution(candidates, history),
    resolvedInput: input,
    turnCount,
  }

  // Run request preparation for metadata
  const requestPrep = prepareRequest(form, messages, sessionState, input, candidates.length)

  const responseText = recommendation.llmSummary ?? deterministicSummary
  const candidateSnapshot = buildCandidateSnapshot(candidates, evidenceMap)

  return NextResponse.json({
    text: status === "none"
      ? "조건에 맞는 제품을 찾지 못했습니다. 직경이나 소재 조건을 조정해보세요."
      : responseText,
    purpose: "recommendation",
    chips: getFollowUpChips(recommendation),
    isComplete: true,
    recommendation,
    sessionState,
    evidenceSummaries: evidenceSummaries.length > 0 ? evidenceSummaries : null,
    candidateSnapshot,
    extractedField: null,
    // New fields
    requestPreparation: requestPrep,
    primaryExplanation,
    primaryFactChecked: primaryFactChecked ? serializeFactChecked(primaryFactChecked) : null,
    altExplanations,
    altFactChecked: altFactChecked.map(fc => serializeFactChecked(fc)),
  })
}

// ── General Chat Handler (non-product questions) ──────────────
async function handleGeneralChat(
  provider: ReturnType<typeof getProvider>,
  userMessage: string,
  _currentInput: RecommendationInput,
  candidateCount: number
): Promise<string | null> {
  const clean = userMessage.trim()

  // Simple greetings
  if (/^(안녕|하이|헬로|hi|hello|반갑|좋은\s*(아침|오후|저녁))/i.test(clean)) {
    return `안녕하세요! YG-1 절삭공구 추천 시스템입니다. 현재 ${candidateCount}개 후보 제품이 있어요. 추가 조건을 알려주시면 더 정확한 추천이 가능합니다.`
  }

  // Thanks
  if (/^(감사|고마|ㄱㅅ|thank|thx)/i.test(clean)) {
    return `천만에요! 추가로 궁금한 점이나 다른 조건이 있으면 말씀해주세요.`
  }

  // Questions about the system
  if (/뭐\s*(할|하는)|어떤.*시스템|어떻게.*사용|도움|help/i.test(clean)) {
    return `저는 YG-1 엔드밀 추천 시스템이에요. 가공 소재, 직경, 날수, 코팅 등의 조건을 알려주시면 최적의 엔드밀을 추천해드립니다. 현재 약 9,800개 제품 데이터를 기반으로 추천합니다.`
  }

  // Cutting tool / machining general knowledge questions or any other chat
  if (/란\s*\?|뭐야|뭔가요|무엇|차이|설명|알려줘|궁금|왜.*쓰|언제.*쓰|어떤|좋은|추천.*방법|팁/i.test(clean) || clean.length > 3) {
    try {
      const systemPrompt = `당신은 YG-1 절삭공구 전문가입니다. 사용자의 질문에 간결하고 친절하게 답변하세요.
- 절삭공구, 가공, 소재, 코팅 관련 질문에 전문적으로 답변
- 그 외 일반 질문에도 짧고 친절하게 답변
- 답변은 2-3문장으로 짧게
- 답변 끝에 "추가 조건이 있으시면 알려주세요!" 같은 안내 추가
- 한국어로 답변`
      const raw = await provider.complete(systemPrompt, [
        { role: "user", content: clean }
      ], 300)
      if (raw && raw.trim()) return raw.trim()
    } catch {
      return null
    }
  }

  return null
}

// ── Extract Parameters from User Message ─────────────────────
async function extractParamsFromMessage(
  provider: ReturnType<typeof getProvider>,
  message: string,
  currentInput: RecommendationInput,
  prevState: ExplorationSessionState
): Promise<{ isComplete: boolean; newFilter: AppliedFilter | null; skippedField: string | null } | null> {
  const clean = message.trim().toLowerCase()

  // ── Use lastAskedField from session state (reliable) ──
  const lastAskedField = prevState.lastAskedField ?? inferCurrentQuestionField(currentInput, prevState)

  // 1. Reset signals
  if (["처음부터 다시", "처음부터", "다시 시작", "리셋"].some(s => clean.includes(s))) {
    return { isComplete: true, newFilter: null, skippedField: null }
  }

  // 2. Completion signals
  if (["추천해주세요", "바로 보여주세요", "결과 보기", "추천 받기", "추가 조건 없음", "그냥 추천", "바로 추천"].some(s => clean.includes(s))) {
    return { isComplete: true, newFilter: null, skippedField: null }
  }

  // 3. Skip / don't-care / don't-know — BEFORE tool keyword check
  const skipPatterns = [
    "상관없", "상관 없", "아무거나", "아무 거나", "다 괜찮", "괜찮아", "뭐든",
    "모름", "몰라", "모르겠", "잘 모르", "잘모르", "글쎄",
    "패스", "넘어가", "넘겨", "다음", "스킵", "skip", "pass", "next",
  ]
  if (skipPatterns.some(s => clean.includes(s))) {
    return { isComplete: false, newFilter: null, skippedField: lastAskedField !== "unknown" ? lastAskedField : null }
  }

  // 4. Detect irrelevant/off-topic input via tool keyword whitelist
  const toolRelatedKeywords = [
    "날", "mm", "코팅", "tialn", "alcrn", "tin", "dlc", "y-코팅", "ticn", "무코팅", "uncoated", "블루",
    "알루미늄", "스테인리스", "탄소강", "주철", "티타늄", "고경도", "sus", "인코넬", "구리",
    "비철", "합금강", "공구강", "내열합금", "카바이드", "carbide", "cbn", "hss", "초경",
    "황삭", "정삭", "중삭", "슬롯", "측면", "프로파일", "페이싱", "고이송",
    "엔드밀", "드릴", "볼", "플랫", "스퀘어", "챔퍼", "radius", "ball", "flat", "square",
    "샤프엣지", "터치", "테이퍼", "taper", "corner", "wave", "롱넥", "modular",
    "ce5", "ce7", "gnx", "sem", "alu",
    "추천", "결과", "비교", "대체", "납기", "재고", "직경", "파이", "지름",
  ]
  const hasToolKeyword = toolRelatedKeywords.some(k => clean.includes(k))
    || /\d+\s*날/.test(clean)
    || /\d+(\.\d+)?\s*mm/.test(clean)
    || /^[a-z]{2,}\d+/i.test(clean)
    || /^\d+(\.\d+)?$/.test(clean)      // bare numbers like "10", "4.5" (likely diameter)

  if (!hasToolKeyword) {
    return null
  }

  // Determine current question field from history
  const lastHistory = prevState.narrowingHistory
  const askedFields = new Set(lastHistory.flatMap(h => h.extractedFilters.map(f => f.field)))

  // ── Multi-condition extraction: detect when user provides multiple params at once ──
  // e.g. "탄소강 가공에 4mm 스퀘어 엔드밀 추천해줘"
  const materialKeywordMap: Record<string, string> = {
    "탄소강": "탄소강", "합금강": "합금강", "공구강": "공구강",
    "스테인리스": "스테인리스", "sus": "스테인리스", "스텐": "스테인리스",
    "알루미늄": "알루미늄", "알루": "알루미늄", "alu": "알루미늄",
    "주철": "주철", "cast iron": "주철",
    "티타늄": "티타늄", "titanium": "티타늄",
    "인코넬": "인코넬", "inconel": "인코넬", "내열합금": "내열합금",
    "고경도": "고경도강", "고경도강": "고경도강", "hrc": "고경도강",
    "구리": "구리", "copper": "구리", "비철": "비철금속",
  }
  const detectedMaterial = Object.keys(materialKeywordMap).find(k => clean.includes(k))
  const diamMatch = clean.match(/([\d.]+)\s*mm/)
  const fluteMatch = clean.match(/(\d+)\s*날/)
  const subtypeKeywords = ["flat", "플랫", "ball", "볼", "chamfer", "챔퍼", "radius", "래디우스", "corner", "square", "스퀘어", "스퀘어형", "라핑", "roughing"]
  const foundSubtype = subtypeKeywords.find(k => clean.includes(k))

  // Count how many params detected in this single message
  const paramCount = [detectedMaterial, diamMatch, fluteMatch, foundSubtype].filter(Boolean).length

  // If message contains 2+ params, treat as a "re-specification" — apply ALL filters
  if (paramCount >= 2) {
    console.log(`[recommend] Multi-param detected (${paramCount}): material=${detectedMaterial}, diam=${diamMatch?.[1]}, flute=${fluteMatch?.[1]}, subtype=${foundSubtype}`)

    // Return a compound filter by picking the most impactful one (material > diameter > subtype > flute)
    // and flag that we need to re-run with updated input
    if (detectedMaterial) {
      const matVal = materialKeywordMap[detectedMaterial]
      const filter = parseAnswerToFilter("material", matVal)
      if (filter) {
        // Enrich filter with side-effects: also update diameter and subtype if present
        const sideFilters: AppliedFilter[] = []
        if (diamMatch) {
          const df = parseAnswerToFilter("diameterRefine", `${diamMatch[1]}mm`)
          if (df) sideFilters.push(df)
        }
        if (foundSubtype) {
          const sf = parseAnswerToFilter("toolSubtype", foundSubtype)
          if (sf) sideFilters.push(sf)
        }
        if (fluteMatch) {
          const ff = parseAnswerToFilter("fluteCount", `${fluteMatch[1]}날`)
          if (ff) sideFilters.push(ff)
        }
        // Store side filters in the main filter's metadata for batch processing
        ;(filter as unknown as Record<string, unknown>)._sideFilters = sideFilters
        return { isComplete: false, newFilter: filter, skippedField: null }
      }
    }
  }

  // ── Single-param extraction ──

  // Material change (even alone, should override current material)
  if (detectedMaterial) {
    const matVal = materialKeywordMap[detectedMaterial]
    const currentMaterial = (currentInput.material || "").toLowerCase()
    const isNewMaterial = !currentMaterial.includes(matVal)
    if (isNewMaterial) {
      const filter = parseAnswerToFilter("material", matVal)
      return { isComplete: false, newFilter: filter, skippedField: null }
    }
  }

  // Flute count
  if (fluteMatch && !currentInput.flutePreference) {
    const filter = parseAnswerToFilter("fluteCount", message)
    return { isComplete: false, newFilter: filter, skippedField: null }
  }

  // Diameter
  if (diamMatch) {
    const filter = parseAnswerToFilter("diameterRefine", message)
    return { isComplete: false, newFilter: filter, skippedField: null }
  }

  // Coating keywords (expanded: includes Blue Coating, uncoated, etc.)
  const coatingKeywords = [
    "altin", "tialn", "dlc", "무코팅", "y-코팅", "y코팅", "ticn",
    "blue coating", "blue", "블루", "블루코팅", "uncoated", "코팅 없",
    "아니 코팅", "코팅 안", "노코팅",
  ]
  const foundCoating = coatingKeywords.find(k => clean.includes(k))
  if (foundCoating && !currentInput.coatingPreference) {
    // Normalize coating value
    let coatingVal = foundCoating.toUpperCase()
    if (["blue coating", "blue", "블루", "블루코팅"].includes(foundCoating)) {
      coatingVal = "Blue Coating"
    } else if (["무코팅", "uncoated", "코팅 없", "아니 코팅", "코팅 안", "노코팅"].includes(foundCoating)) {
      coatingVal = "Uncoated"
    }
    const filter = parseAnswerToFilter("coating", coatingVal)
    return { isComplete: false, newFilter: filter, skippedField: null }
  }

  // Series name patterns (CE*, GNX*, SEM* etc.) — detect when user clicks a series chip
  const seriesPatterns = [/^(ce\d+[a-z]*\d*)/i, /^(gnx\d+)/i, /^(sem[a-z]*\d+)/i, /^(e\d+[a-z]\d+)/i]
  const seriesMatch = seriesPatterns.find(p => p.test(clean))
  if (seriesMatch && !askedFields.has("seriesName")) {
    const filter = parseAnswerToFilter("seriesName", message.trim())
    return { isComplete: false, newFilter: filter, skippedField: null }
  }

  // Tool subtype keywords (single-param)
  if (foundSubtype && !askedFields.has("toolSubtype")) {
    const filter = parseAnswerToFilter("toolSubtype", message.trim())
    return { isComplete: false, newFilter: filter, skippedField: null }
  }

  // Cutting type keywords
  const cuttingKeywords = ["슬롯", "측면", "프로파일", "황삭", "정삭"]
  const foundCutting = cuttingKeywords.find(k => clean.includes(k))
  if (foundCutting) {
    const filter = parseAnswerToFilter("cuttingType", message)
    return { isComplete: false, newFilter: filter, skippedField: null }
  }

  // Try LLM extraction as fallback
  if (provider.available()) {
    try {
      const systemPrompt = buildSystemPrompt()
      const raw = await provider.complete(systemPrompt, [
        { role: "user", content: `사용자 메시지: "${message}"\n\n위 메시지에서 절삭 공구 관련 파라미터를 추출하세요.\nJSON으로 응답: { "responseText": "확인했습니다", "extractedParams": { "flutePreference": null, "coatingPreference": null, "operationType": null, "material": null, "diameterMm": null }, "isComplete": false, "skipQuestion": false }` }
      ], 300)

      const parsed = safeParseJSON(raw)
      if (parsed) {
        if (parsed.isComplete) return { isComplete: true, newFilter: null, skippedField: null }
        if (parsed.skipQuestion) {
          return { isComplete: false, newFilter: null, skippedField: lastAskedField !== "unknown" ? lastAskedField : null }
        }

        const params = parsed.extractedParams as Record<string, unknown>
        if (params) {
          if (params.flutePreference && !currentInput.flutePreference) {
            return { isComplete: false, newFilter: parseAnswerToFilter("fluteCount", `${params.flutePreference}날`), skippedField: null }
          }
          if (params.coatingPreference && !currentInput.coatingPreference) {
            return { isComplete: false, newFilter: parseAnswerToFilter("coating", String(params.coatingPreference)), skippedField: null }
          }
        }
      }
    } catch (e) {
      console.warn("[recommend] LLM extraction failed:", e)
    }
  }

  // ── Fallback: use lastAskedField (reliable, from session state) ──
  // This ensures we always map the answer to the field that was actually asked
  const targetField = lastAskedField !== "unknown" ? lastAskedField : inferCurrentQuestionField(currentInput, prevState)
  if (targetField !== "unknown" && message.trim().length > 0) {
    console.log(`[recommend] Fallback: treating "${message}" as answer to field "${targetField}" (lastAskedField=${lastAskedField})`)
    const filter = parseAnswerToFilter(targetField, message.trim())
    if (filter) {
      return { isComplete: false, newFilter: filter, skippedField: null }
    }
    // If parseAnswerToFilter returns null (e.g., unrecognized value), re-ask instead of skipping
    return null
  }

  // Truly unrecognizable — re-ask instead of skipping
  return null
}

// ── Infer which field the question engine was asking about ────
function inferCurrentQuestionField(
  input: RecommendationInput,
  prevState: ExplorationSessionState
): string {
  // Use the actual question engine to determine what's being asked
  // This ensures perfect sync between what was asked and what we infer
  const filters: AppliedFilter[] = prevState?.appliedFilters ?? []
  const currentInput = prevState?.resolvedInput
    ? { ...input, ...prevState.resolvedInput }
    : input
  const hybridResult = runHybridRetrieval(currentInput, filters, 50)
  const question = selectNextQuestion(currentInput, hybridResult.candidates, prevState.narrowingHistory ?? [])
  if (question) return question.field

  // Fallback: check by priority if question engine returns null
  const askedFields = new Set(
    prevState.narrowingHistory.flatMap(h => h.extractedFilters.map(f => f.field))
  )
  if (!input.flutePreference && !askedFields.has("fluteCount")) return "fluteCount"
  if (!input.coatingPreference && !askedFields.has("coating")) return "coating"
  if (!askedFields.has("seriesName")) return "seriesName"
  if (!input.toolSubtype && !askedFields.has("toolSubtype")) return "toolSubtype"
  if (!askedFields.has("cuttingType")) return "cuttingType"
  if (!askedFields.has("diameterRefine")) return "diameterRefine"
  return "unknown"
}

// ── Apply filter to RecommendationInput ──────────────────────
function applyFilterToInput(input: RecommendationInput, filter: AppliedFilter): RecommendationInput {
  let updated = { ...input }
  updated = applySingleFilter(updated, filter)

  // Apply side filters if present (from multi-param extraction)
  const sideFilters = (filter as unknown as Record<string, unknown>)._sideFilters as AppliedFilter[] | undefined
  if (sideFilters && Array.isArray(sideFilters)) {
    for (const sf of sideFilters) {
      updated = applySingleFilter(updated, sf)
    }
  }

  return updated
}

function applySingleFilter(input: RecommendationInput, filter: AppliedFilter): RecommendationInput {
  const updated = { ...input }
  switch (filter.field) {
    case "fluteCount":
      updated.flutePreference = typeof filter.rawValue === "number" ? filter.rawValue : parseInt(String(filter.rawValue))
      break
    case "coating":
      updated.coatingPreference = String(filter.rawValue)
      break
    case "diameterMm":
    case "diameterRefine":
      updated.diameterMm = typeof filter.rawValue === "number" ? filter.rawValue : parseFloat(String(filter.rawValue))
      break
    case "material":
      updated.material = String(filter.rawValue)
      break
    case "toolSubtype":
      updated.toolSubtype = String(filter.rawValue)
      break
    case "cuttingType":
      if (!updated.operationType) updated.operationType = String(filter.rawValue)
      break
  }
  return updated
}

// ── Build Candidate Snapshot (lightweight for UI) ────────────
function buildCandidateSnapshot(
  candidates: ScoredProduct[],
  evidenceMap: Map<string, EvidenceSummary>
): CandidateSnapshot[] {
  return candidates.slice(0, 30).map((c, i) => {
    const ev = evidenceMap.get(c.product.normalizedCode)
    return {
      rank: i + 1,
      productCode: c.product.normalizedCode,
      displayCode: c.product.displayCode,
      seriesName: c.product.seriesName,
      seriesIconUrl: c.product.seriesIconUrl ?? null,
      diameterMm: c.product.diameterMm,
      fluteCount: c.product.fluteCount,
      coating: c.product.coating,
      materialTags: c.product.materialTags,
      score: c.score,
      scoreBreakdown: c.scoreBreakdown,
      matchStatus: c.matchStatus,
      stockStatus: c.stockStatus,
      totalStock: c.totalStock,
      hasEvidence: !!ev && ev.chunks.length > 0,
      bestCondition: ev?.bestCondition ?? null,
    }
  })
}

// ════════════════════════════════════════════════════════════════
// SIMPLE CHAT HANDLER (legacy)
// ════════════════════════════════════════════════════════════════

async function handleSimpleChat(messages: ChatMessage[], mode: string): Promise<Response> {
  if (!messages.length) {
    return NextResponse.json({ error: "messages required" }, { status: 400 })
  }

  const latestUserMsg = [...messages].reverse().find(m => m.role === "user")?.text ?? ""
  const baseInput = normalizeInput(latestUserMsg)
  const provider = getProvider()

  // Quick check if enough info
  const hasEnough = !!(baseInput.diameterMm || (baseInput.material && baseInput.operationType))

  if (hasEnough) {
    const result = runHybridRetrieval(baseInput, [], 5)
    const { primary, alternatives, status } = classifyHybridResults(result)
    const warnings = primary ? buildWarnings(primary, baseInput) : []
    const rationale = primary ? buildRationale(primary, baseInput) : []

    const deterministicSummary = buildDeterministicSummary({
      status, query: baseInput, primaryProduct: primary, alternatives,
      warnings, rationale, sourceSummary: [], deterministicSummary: "",
      llmSummary: null, totalCandidatesConsidered: result.totalConsidered,
    })

    const recommendation: RecommendationResult = {
      status, query: baseInput, primaryProduct: primary, alternatives,
      warnings, rationale, sourceSummary: primary ? buildSourceSummary(primary) : [],
      deterministicSummary, llmSummary: null,
      totalCandidatesConsidered: result.totalConsidered,
    }

    return NextResponse.json({
      text: deterministicSummary,
      purpose: "recommendation",
      chips: getFollowUpChips(recommendation),
      isComplete: true,
      recommendation,
      sessionState: null,
      evidenceSummaries: null,
      candidateSnapshot: null,
    })
  }

  // Not enough info — ask question
  return NextResponse.json({
    text: getNextQuestion(baseInput),
    purpose: "question",
    chips: getDefaultChips(baseInput),
    isComplete: false,
    recommendation: null,
    sessionState: null,
    evidenceSummaries: null,
    candidateSnapshot: null,
  })
}

// ════════════════════════════════════════════════════════════════
// HELPERS
// ════════════════════════════════════════════════════════════════

function getKnown<T>(state: AnswerState<T>): T | undefined {
  return state.status === "known" ? (state as { status: "known"; value: T }).value : undefined
}

function parseIntakeDiameter(text: string): number | null {
  if (!text) return null
  const clean = text.trim()
  const mmMatch = clean.match(/^(\d+(?:\.\d+)?)\s*mm?$/i)
  if (mmMatch) return parseFloat(mmMatch[1])
  const numMatch = clean.match(/^(\d+(?:\.\d+)?)$/)
  if (numMatch) {
    const n = parseFloat(numMatch[1])
    return n > 0 && n <= 200 ? n : null
  }
  const inchFrac = clean.match(/^(\d+)\s*\/\s*(\d+)\s*(?:inch|인치|")?$/i)
  if (inchFrac) {
    return Math.round((parseInt(inchFrac[1]) / parseInt(inchFrac[2])) * 25.4 * 100) / 100
  }
  return null
}

function mapIntakeToInput(form: ProductIntakeForm): RecommendationInput {
  const input: Partial<RecommendationInput> = {
    manufacturerScope: "yg1-only",
    locale: "ko",
  }
  // Material: may be comma-separated for multi-select (e.g. "알루미늄,스테인리스")
  const material = getKnown(form.material)
  if (material) input.material = material  // keeps comma-separated string; hybrid-retrieval resolves each
  const opParts: string[] = []
  const intent = getKnown(form.machiningIntent as AnswerState<MachiningIntent>)
  const intentMap: Record<MachiningIntent, string> = { roughing: "황삭", semi: "중삭", finishing: "정삭" }
  if (intent) opParts.push(intentMap[intent])
  // OperationType: may be comma-separated for multi-select (e.g. "측면가공,슬롯")
  const opType = getKnown(form.operationType)
  if (opType) {
    // Split comma-separated and add each part
    const ops = opType.split(",").map(s => s.trim()).filter(Boolean)
    opParts.push(...ops)
  }
  if (opParts.length > 0) input.operationType = opParts.join(" ")
  const diamStr = getKnown(form.diameterInfo)
  if (diamStr) {
    const diam = parseIntakeDiameter(diamStr)
    if (diam !== null) input.diameterMm = diam
  }
  const toolType = getKnown(form.toolTypeOrCurrentProduct)
  if (toolType) input.toolType = toolType
  return input as RecommendationInput
}

function getNextQuestion(input: RecommendationInput): string {
  if (!input.material) return "어떤 소재를 가공하실 예정인가요?"
  if (!input.operationType) return "어떤 가공 방식이 필요하신가요? (황삭/정삭/고이송 등)"
  if (!input.diameterMm) return "공구 직경은 몇 mm가 필요하신가요?"
  if (!input.flutePreference) return "날 수(flute) 선호도가 있으신가요?"
  return "추가로 확인이 필요한 조건이 있으신가요?"
}

function getDefaultChips(input: RecommendationInput): string[] {
  if (!input.material) return ["알루미늄", "스테인리스", "탄소강", "주철", "티타늄", "고경도강"]
  if (!input.operationType) return ["황삭", "정삭", "고이송", "슬롯가공", "측면가공"]
  if (!input.diameterMm) return ["2mm", "4mm", "6mm", "8mm", "10mm", "12mm"]
  if (!input.flutePreference) return ["2날", "3날", "4날", "6날", "상관없음"]
  return ["추천 받기", "다른 조건으로", "경쟁사 비교"]
}

function getFollowUpChips(result: RecommendationResult): string[] {
  const chips = []
  if (result.alternatives.length > 0) chips.push(`대체 후보 ${result.alternatives.length}개 보기`)
  if (result.primaryProduct?.stockStatus === "outofstock") chips.push("납기 확인")
  chips.push("다른 직경 검색")
  chips.push("처음부터 다시")
  return chips.slice(0, 5)
}

function buildSourceSummary(primary: { product: { rawSourceFile: string; rawSourceSheet?: string | null; sourceConfidence?: string | null } } | null): string[] {
  if (!primary) return []
  const p = primary.product
  return [
    `Source: ${p.rawSourceFile}${p.rawSourceSheet ? ` / ${p.rawSourceSheet}` : ""}`,
    `Confidence: ${p.sourceConfidence ?? "unknown"}`,
  ]
}

/** Serialize FactCheckedRecommendation to plain object (strip non-serializable data) */
function serializeFactChecked(fc: FactCheckedRecommendation): Record<string, unknown> {
  return {
    productCode: fc.productCode,
    displayCode: fc.displayCode,
    seriesName: fc.seriesName,
    manufacturer: fc.manufacturer,
    diameterMm: fc.diameterMm,
    fluteCount: fc.fluteCount,
    coating: fc.coating,
    toolMaterial: fc.toolMaterial,
    materialTags: fc.materialTags,
    lengthOfCutMm: fc.lengthOfCutMm,
    overallLengthMm: fc.overallLengthMm,
    hasCuttingConditions: fc.hasCuttingConditions,
    bestCondition: fc.bestCondition,
    conditionConfidence: fc.conditionConfidence,
    conditionSourceCount: fc.conditionSourceCount,
    stockStatus: fc.stockStatus,
    totalStock: fc.totalStock,
    minLeadTimeDays: fc.minLeadTimeDays,
    matchPct: fc.matchPct,
    matchStatus: fc.matchStatus,
    score: fc.score,
    explanation: fc.explanation,
    factCheckReport: fc.factCheckReport,
  }
}

function safeParseJSON(raw: string): Record<string, unknown> | null {
  try {
    const cleaned = raw.replace(/```json\n?|\n?```/g, "").trim()
    return JSON.parse(cleaned)
  } catch {
    return null
  }
}
