/**
 * /api/recommend
 *
 * Session-aware hybrid retrieval + narrowing chat + RAG-grounded recommendation.
 *
 * Flow:
 *   1. Receive intakeForm + messages + sessionState
 *   2. If no sessionState → create session, run hybrid retrieval → initial candidatePool
 *   3. Run question engine on candidatePool
 *   4. If question → LLM polishes & returns question + chips + candidateSnapshot
 *   5. If resolved → build evidence-grounded recommendation
 *
 * Hallucination prevention:
 *   - Product codes, specs, stock, lead time NEVER generated by LLM
 *   - Cutting conditions ONLY from evidence-chunks.json
 *   - LLM only writes natural-language explanation of real results
 */

import { NextResponse } from "next/server"
import { normalizeInput, mergeInputs } from "@/lib/domain/input-normalizer"
import { runHybridRetrieval, classifyHybridResults } from "@/lib/domain/hybrid-retrieval"
import { selectNextQuestion, checkResolution, parseAnswerToFilter } from "@/lib/domain/question-engine"
import { buildDeterministicSummary, buildRationale, buildWarnings } from "@/lib/domain/summary-generator"
import { EvidenceRepo } from "@/lib/data/repos/evidence-repo"
import { getProvider } from "@/lib/llm/provider"
import {
  buildSystemPrompt,
  buildSessionContext,
  buildGreetingPrompt,
  buildNarrowingPrompt,
  buildResultPrompt,
  buildExplanationResultPrompt,
  buildIntentContext,
} from "@/lib/llm/prompt-builder"
import { resolveMaterialTag } from "@/lib/domain/material-resolver"
import { prepareRequest } from "@/lib/domain/request-preparation"
import { buildExplanation } from "@/lib/domain/explanation-builder"
import { runFactCheck } from "@/lib/domain/fact-checker"
import { analyzeInquiry, getRedirectResponse } from "@/lib/domain/inquiry-analyzer"
import { planAction } from "@/lib/domain/action-planner"
import type { ActionPlan } from "@/lib/domain/action-planner"

import type { RecommendationInput, RecommendationResult, ScoredProduct, ChatMessage, MatchStatus } from "@/lib/types/canonical"
import type { ProductIntakeForm, AnswerState, MachiningIntent } from "@/lib/types/intake"
import type { ExplorationSessionState, AppliedFilter, NarrowingTurn, CandidateSnapshot } from "@/lib/types/exploration"
import type { EvidenceSummary } from "@/lib/types/evidence"
import type { FactCheckedRecommendation } from "@/lib/types/fact-check"
import type { RecommendationExplanation } from "@/lib/types/explanation"

export const maxDuration = 60

// ── POST Handler ─────────────────────────────────────────────
export async function POST(req: Request) {
  try {
    const body = await req.json()

    // Route: intake-based exploration flow
    if (body.intakeForm) {
      return handleExploration(
        body.intakeForm as ProductIntakeForm,
        body.messages ?? [],
        body.sessionState ?? null
      )
    }

    // Route: simple chat (legacy, kept for backward compat)
    return handleSimpleChat(body.messages ?? [], body.mode ?? "simple")

  } catch (err) {
    console.error("[recommend] Error:", err)
    return NextResponse.json({
      error: "internal_error",
      detail: err instanceof Error ? err.message : "Unknown error",
      text: "죄송합니다, 처리 중 오류가 발생했습니다. 다시 시도해주세요.",
      chips: ["처음부터 다시", "소재 입력", "직경 입력"],
      isComplete: false,
      recommendation: null,
      sessionState: null,
      evidenceSummaries: null,
      candidateSnapshot: null,
    }, { status: 500 })
  }
}

// ════════════════════════════════════════════════════════════════
// EXPLORATION HANDLER (session-aware hybrid retrieval + narrowing)
// ════════════════════════════════════════════════════════════════

async function handleExploration(
  form: ProductIntakeForm,
  messages: ChatMessage[],
  prevState: ExplorationSessionState | null
): Promise<Response> {
  const provider = getProvider()
  const baseInput = mapIntakeToInput(form)

  // ── Step 0: Request Preparation ────────────────────────────
  const filters: AppliedFilter[] = prevState?.appliedFilters ?? []
  const resolvedInput: RecommendationInput = prevState?.resolvedInput
    ? { ...baseInput, ...prevState.resolvedInput }
    : baseInput

  const hybridResult = runHybridRetrieval(resolvedInput, filters)
  const candidates = hybridResult.candidates
  const evidenceMap = hybridResult.evidenceMap

  // Run request preparation engine
  const requestPrep = prepareRequest(form, messages, prevState, resolvedInput, candidates.length)
  console.log(`[recommend] Intent: ${requestPrep.intent} (${requestPrep.intentConfidence}), Route: ${requestPrep.route.action}`)

  // Handle reset
  if (requestPrep.route.action === "reset_session") {
    return NextResponse.json({
      text: "처음부터 다시 시작합니다. 새로운 조건을 입력해주세요.",
      purpose: "greeting",
      chips: ["처음부터 다시"],
      isComplete: true,
      recommendation: null,
      sessionState: null,
      evidenceSummaries: null,
      candidateSnapshot: null,
      extractedField: null,
      requestPreparation: requestPrep,
    })
  }

  // ── Step 2: Process user message (if any) ──────────────────
  const narrowingHistory: NarrowingTurn[] = prevState?.narrowingHistory ?? []
  let currentInput = { ...resolvedInput }
  let turnCount = prevState?.turnCount ?? 0

  // If there are messages and this isn't the first call
  if (messages.length > 0 && prevState) {
    const lastUserMsg = [...messages].reverse().find(m => m.role === "user")
    if (lastUserMsg) {
      // ── NEW: Inquiry Analysis Gate ──
      const inquiry = analyzeInquiry(lastUserMsg.text)
      const actionPlan = planAction(inquiry, lastUserMsg.text, form, prevState)
      console.log(`[recommend] Inquiry: signal=${inquiry.signalStrength}, domain=${inquiry.domainRelevance}, action=${actionPlan.intent} (${actionPlan.reason})`)

      // Gate: true nonsense → static redirect
      if (actionPlan.retrievalStrategy === "none" && actionPlan.responseFormat === "redirect") {
        const redirect = getRedirectResponse(inquiry)
        const sessionState: ExplorationSessionState = {
          sessionId: prevState.sessionId ?? `ses-${Date.now()}`,
          candidateCount: prevState.candidateCount,
          appliedFilters: filters,
          narrowingHistory: narrowingHistory,
          resolutionStatus: prevState.resolutionStatus ?? "broad",
          resolvedInput: currentInput,
          turnCount,
          lastAskedField: prevState.lastAskedField,
        }
        return NextResponse.json({
          text: redirect.text,
          purpose: "question",
          chips: redirect.chips,
          isComplete: false,
          recommendation: null,
          sessionState,
          evidenceSummaries: null,
          candidateSnapshot: redirect.showCandidates ? buildCandidateSnapshot(candidates, evidenceMap) : null,
          extractedField: null,
          requestPreparation: null,
          primaryExplanation: null,
          primaryFactChecked: null,
          altExplanations: [],
          altFactChecked: [],
          actionPlan: { intent: actionPlan.intent, reason: actionPlan.reason },
        })
      }

      // Gate: general_chat → use LLM to answer freely (greetings, general questions, off-domain)
      if (actionPlan.responseFormat === "general_chat") {
        const llmResponse = await handleGeneralChat(provider, lastUserMsg.text, currentInput, candidates, form)
        const sessionState: ExplorationSessionState = {
          sessionId: prevState.sessionId ?? `ses-${Date.now()}`,
          candidateCount: prevState.candidateCount ?? candidates.length,
          appliedFilters: filters,
          narrowingHistory: narrowingHistory,
          resolutionStatus: prevState.resolutionStatus ?? "broad",
          resolvedInput: currentInput,
          turnCount,
          lastAskedField: prevState.lastAskedField,
        }
        return NextResponse.json({
          text: llmResponse.text,
          purpose: "general_chat",
          chips: llmResponse.chips,
          isComplete: false,
          recommendation: null,
          sessionState,
          evidenceSummaries: null,
          candidateSnapshot: candidates.length > 0 ? buildCandidateSnapshot(candidates, evidenceMap) : null,
          extractedField: null,
          requestPreparation: null,
          primaryExplanation: null,
          primaryFactChecked: null,
          altExplanations: [],
          altFactChecked: [],
          actionPlan: { intent: actionPlan.intent, reason: actionPlan.reason },
        })
      }

      // Gate: post-recommendation follow-up — user asking about already-recommended products
      if (prevState.resolutionStatus?.startsWith("resolved") && !actionPlan.skipNarrowing) {
        const followUpReply = await handlePostRecommendationFollowUp(
          provider, lastUserMsg.text, currentInput, candidates, evidenceMap, form
        )
        if (followUpReply) {
          const sessionState: ExplorationSessionState = {
            sessionId: prevState.sessionId ?? `ses-${Date.now()}`,
            candidateCount: candidates.length,
            appliedFilters: filters,
            narrowingHistory: narrowingHistory,
            resolutionStatus: prevState.resolutionStatus,
            resolvedInput: currentInput,
            turnCount,
          }
          return NextResponse.json({
            text: followUpReply,
            purpose: "follow_up",
            chips: ["절삭조건 알려줘", "코팅 비교", "다른 직경 검색", "처음부터 다시"],
            isComplete: true,
            recommendation: null,
            sessionState,
            evidenceSummaries: null,
            candidateSnapshot: buildCandidateSnapshot(candidates, evidenceMap),
            extractedField: null,
            requestPreparation: null,
            primaryExplanation: null,
            primaryFactChecked: null,
            altExplanations: [],
            altFactChecked: [],
          })
        }
      }

      // Gate: forced recommendation → skip narrowing, go straight to results
      if (actionPlan.skipNarrowing) {
        return buildRecommendationResponse(
          form, candidates, evidenceMap, currentInput, narrowingHistory,
          filters, turnCount, messages, provider
        )
      }

      // ── Contextual question about current narrowing field ──
      const contextualQuestionPattern = /그게\s*뭐|그건\s*뭐|이게\s*뭐|뭐야\s*그|그거\s*뭐|차이.*뭐|뭐가\s*다|뭐가\s*좋|어떤\s*게\s*좋/i
      const alreadySaidPattern = /이미.*했|이미.*말했|이미.*입력|아까.*했|아까.*말했|했잖아|했잔아|말했잖아|말했잔아|입력했/i
      if (contextualQuestionPattern.test(lastUserMsg.text)) {
        const contextReply = await handleContextualNarrowingQuestion(
          provider, lastUserMsg.text, currentInput, candidates, prevState
        )
        if (contextReply) {
          return buildQuestionResponse(
            form, candidates, evidenceMap, currentInput,
            narrowingHistory, filters, turnCount, messages, provider,
            contextReply
          )
        }
      }
      // User frustrated that system re-asks already provided info → skip to results
      if (alreadySaidPattern.test(lastUserMsg.text)) {
        return buildRecommendationResponse(
          form, candidates, evidenceMap, currentInput, narrowingHistory,
          filters, turnCount, messages, provider
        )
      }

      // ── Standard extraction path (inquiry passed the gate) ──
      const extracted = await extractParamsFromMessage(provider, lastUserMsg.text, currentInput, prevState)

      // Non-product input — handle as general conversation
      if (extracted === null) {
        const generalResult = await handleGeneralChat(provider, lastUserMsg.text, currentInput, candidates, form)
        return buildQuestionResponse(
          form, candidates, evidenceMap, currentInput,
          narrowingHistory, filters, turnCount, messages, provider,
          generalResult.text || `절삭공구 관련 조건을 알려주시거나, 아래 버튼을 선택해주세요.`
        )
      }

      if (extracted) {
        // Check for skip or complete signals
        if (extracted.isComplete) {
          // User wants results now — skip to recommendation
          return buildRecommendationResponse(
            form, candidates, evidenceMap, currentInput, narrowingHistory,
            filters, turnCount, messages, provider
          )
        }

        // Handle skipped field ("상관없음") — record in history so we don't re-ask
        if (extracted.skippedField) {
          const skipFilter: AppliedFilter = {
            field: extracted.skippedField,
            op: "skip",
            value: "상관없음",
            rawValue: "skip",
            appliedAt: turnCount,
          }

          narrowingHistory.push({
            question: "follow-up",
            answer: lastUserMsg.text,
            extractedFilters: [skipFilter],
            candidateCountBefore: candidates.length,
            candidateCountAfter: candidates.length, // no change
          })
          turnCount++

          // Check if we're resolved after skip
          const statusAfterSkip = checkResolution(candidates, narrowingHistory)
          if (statusAfterSkip.startsWith("resolved")) {
            return buildRecommendationResponse(
              form, candidates, evidenceMap, currentInput, narrowingHistory,
              filters, turnCount, messages, provider
            )
          }

          // Ask next question (which will be different since the field is now in history)
          return buildQuestionResponse(
            form, candidates, evidenceMap, currentInput,
            narrowingHistory, filters, turnCount, messages, provider
          )
        }

        // Apply extracted filters
        if (extracted.newFilter) {
          const filter = { ...extracted.newFilter, appliedAt: turnCount }
          filters.push(filter)

          // Update input based on filter
          currentInput = applyFilterToInput(currentInput, filter)

          // Re-run hybrid retrieval with new filter
          const newResult = runHybridRetrieval(currentInput, filters)
          const newCandidates = newResult.candidates

          // Use previous session's candidate count for "before" (not current re-filtered count)
          const prevCandidateCount = prevState.candidateCount ?? candidates.length
          narrowingHistory.push({
            question: prevState.narrowingHistory?.length
              ? "follow-up"
              : "initial",
            answer: lastUserMsg.text,
            extractedFilters: [filter],
            candidateCountBefore: prevCandidateCount,
            candidateCountAfter: newCandidates.length,
          })

          turnCount++

          // Check if we're resolved after applying the filter
          const newStatus = checkResolution(newCandidates, narrowingHistory)
          if (newStatus.startsWith("resolved")) {
            return buildRecommendationResponse(
              form, newCandidates, newResult.evidenceMap, currentInput,
              narrowingHistory, filters, turnCount, messages, provider
            )
          }

          // Ask next question based on new candidate pool
          return buildQuestionResponse(
            form, newCandidates, newResult.evidenceMap, currentInput,
            narrowingHistory, filters, turnCount, messages, provider
          )
        }
      }
    }
  }

  // ── Step 3: Determine what to do next ──────────────────────
  const status = checkResolution(candidates, narrowingHistory)

  if (status.startsWith("resolved") && turnCount > 0) {
    // Already resolved — show results
    return buildRecommendationResponse(
      form, candidates, evidenceMap, currentInput, narrowingHistory,
      filters, turnCount, messages, provider
    )
  }

  // Not resolved (or first call) — ask a question
  return buildQuestionResponse(
    form, candidates, evidenceMap, currentInput, narrowingHistory,
    filters, turnCount, messages, provider
  )
}

// ── Build Question Response ──────────────────────────────────
async function buildQuestionResponse(
  form: ProductIntakeForm,
  candidates: ScoredProduct[],
  evidenceMap: Map<string, EvidenceSummary>,
  input: RecommendationInput,
  history: NarrowingTurn[],
  filters: AppliedFilter[],
  turnCount: number,
  messages: ChatMessage[],
  provider: ReturnType<typeof getProvider>,
  overrideText?: string
): Promise<Response> {
  const question = selectNextQuestion(input, candidates, history)

  // Build session state for client
  const sessionState: ExplorationSessionState = {
    sessionId: `ses-${Date.now()}`,
    candidateCount: candidates.length,
    appliedFilters: filters,
    narrowingHistory: history,
    resolutionStatus: checkResolution(candidates, history),
    resolvedInput: input,
    turnCount,
    lastAskedField: question?.field ?? undefined,  // track which field we're asking about
  }

  // If no question (resolved or out of questions), go to recommendation
  if (!question) {
    return buildRecommendationResponse(
      form, candidates, evidenceMap, input, history,
      filters, turnCount, messages, provider
    )
  }

  // Build candidate snapshot for UI
  const candidateSnapshot = buildCandidateSnapshot(candidates, evidenceMap)

  // LLM-polish the question text (or use deterministic)
  let responseText = overrideText ?? question.questionText
  let chips = question.chips

  if (overrideText) {
    // Skip LLM polish when we have an override (e.g. irrelevant input nudge)
  } else if (provider.available() && messages.length === 0) {
    // First call: generate greeting
    try {
      const systemPrompt = buildSystemPrompt()
      const sessionCtx = buildSessionContext(form, sessionState, candidates.length)
      const greetingPrompt = buildGreetingPrompt(sessionCtx, question, candidates.length)

      const raw = await provider.complete(systemPrompt, [
        { role: "user", content: greetingPrompt }
      ], 800)

      const parsed = safeParseJSON(raw)
      if (parsed?.responseText) {
        responseText = parsed.responseText
      }
    } catch (e) {
      console.warn("[recommend] LLM greeting failed:", e)
    }
  } else if (provider.available() && messages.length > 0) {
    // Follow-up: polish the question
    try {
      const systemPrompt = buildSystemPrompt()
      const sessionCtx = buildSessionContext(form, sessionState, candidates.length)
      const raw = await provider.complete(systemPrompt, [
        { role: "user", content: `${sessionCtx}\n\n다음 질문을 자연스러운 한국어로 다듬어주세요: "${question.questionText}"\n현재 후보 ${candidates.length}개.\nJSON으로 응답: { "responseText": "...", "extractedParams": {}, "isComplete": false, "skipQuestion": false }` }
      ], 300)

      const parsed = safeParseJSON(raw)
      if (parsed?.responseText) {
        responseText = parsed.responseText
      }
    } catch (e) {
      console.warn("[recommend] LLM question polish failed:", e)
    }
  }

  // Run request preparation for metadata
  const requestPrep = prepareRequest(form, messages, sessionState, input, candidates.length)

  return NextResponse.json({
    text: responseText,
    purpose: messages.length === 0 ? "greeting" : "question",
    chips,
    isComplete: false,
    recommendation: null,
    sessionState,
    evidenceSummaries: null,
    candidateSnapshot,
    extractedField: null,
    requestPreparation: requestPrep,
    primaryExplanation: null,
    primaryFactChecked: null,
    altExplanations: [],
    altFactChecked: [],
  })
}

// ── Build Recommendation Response ────────────────────────────
async function buildRecommendationResponse(
  form: ProductIntakeForm,
  candidates: ScoredProduct[],
  evidenceMap: Map<string, EvidenceSummary>,
  input: RecommendationInput,
  history: NarrowingTurn[],
  filters: AppliedFilter[],
  turnCount: number,
  messages: ChatMessage[],
  provider: ReturnType<typeof getProvider>
): Promise<Response> {
  const { primary, alternatives, status } = classifyHybridResults({ candidates, evidenceMap, totalConsidered: candidates.length, filtersApplied: filters })
  const warnings = primary ? buildWarnings(primary, input) : ["조건에 맞는 제품을 찾지 못했습니다"]
  const rationale = primary ? buildRationale(primary, input) : []

  // Add intake-specific warnings
  if (form.material.status === "unknown") warnings.push("소재 미지정 — 전체 소재 대상 검색")
  if (form.diameterInfo.status === "unknown") warnings.push("직경 미지정 — 직경 기준 필터 없음")

  const deterministicSummary = buildDeterministicSummary({
    status,
    query: input,
    primaryProduct: primary,
    alternatives,
    warnings,
    rationale,
    sourceSummary: [],
    deterministicSummary: "",
    llmSummary: null,
    totalCandidatesConsidered: candidates.length,
  })

  // Build evidence summaries for top products
  const evidenceSummaries: EvidenceSummary[] = []
  if (primary) {
    const es = evidenceMap.get(primary.product.normalizedCode)
    if (es) evidenceSummaries.push(es)
  }
  for (const alt of alternatives) {
    const es = evidenceMap.get(alt.product.normalizedCode)
    if (es) evidenceSummaries.push(es)
  }

  // ── NEW: Build explanation + fact check for primary ────────
  let primaryExplanation: RecommendationExplanation | null = null
  let primaryFactChecked: FactCheckedRecommendation | null = null
  let altExplanations: RecommendationExplanation[] = []
  let altFactChecked: FactCheckedRecommendation[] = []

  if (primary) {
    const primaryEvidence = evidenceMap.get(primary.product.normalizedCode) ?? null
    primaryExplanation = buildExplanation(primary, input, primaryEvidence)
    primaryFactChecked = runFactCheck(primary, input, primaryEvidence, primaryExplanation)

    // Build explanations for alternatives too
    for (const alt of alternatives) {
      const altEvidence = evidenceMap.get(alt.product.normalizedCode) ?? null
      const altExpl = buildExplanation(alt, input, altEvidence)
      altExplanations.push(altExpl)
      altFactChecked.push(runFactCheck(alt, input, altEvidence, altExpl))
    }
  }

  const recommendation: RecommendationResult = {
    status,
    query: input,
    primaryProduct: primary,
    alternatives,
    warnings,
    rationale,
    sourceSummary: primary ? buildSourceSummary(primary) : [],
    deterministicSummary,
    llmSummary: null,
    totalCandidatesConsidered: candidates.length,
  }

  // LLM summary with explanation-aware prompt
  if (provider.available() && primary && primaryFactChecked && primaryExplanation) {
    try {
      const systemPrompt = buildSystemPrompt()
      const sessionState: ExplorationSessionState = {
        sessionId: `ses-${Date.now()}`,
        candidateCount: candidates.length,
        appliedFilters: filters,
        narrowingHistory: history,
        resolutionStatus: checkResolution(candidates, history),
        resolvedInput: input,
        turnCount,
      }
      const sessionCtx = buildSessionContext(form, sessionState, candidates.length)

      // Use new explanation-aware prompt — include per-product evidence
      const resultPrompt = buildExplanationResultPrompt(
        sessionCtx,
        primaryFactChecked,
        primaryExplanation,
        alternatives.map(a => {
          const altEvidence = evidenceMap.get(a.product.normalizedCode)
          return {
            displayCode: a.product.displayCode,
            matchStatus: a.matchStatus,
            score: a.score,
            bestCondition: altEvidence?.bestCondition ?? null,
            sourceCount: altEvidence?.sourceCount ?? 0,
          }
        }),
        warnings
      )

      const raw = await provider.complete(systemPrompt, [
        { role: "user", content: resultPrompt }
      ], 1500)

      const parsed = safeParseJSON(raw)
      if (parsed?.responseText) {
        recommendation.llmSummary = parsed.responseText as string
      } else if (raw.trim() && !raw.trim().startsWith("{") && !raw.trim().startsWith("[")) {
        // Only use raw text if it's NOT malformed JSON (prevents JSON leaking into UI)
        recommendation.llmSummary = raw.trim()
      }
    } catch (e) {
      console.warn("[recommend] LLM result summary failed:", e)
    }
  }

  const sessionState: ExplorationSessionState = {
    sessionId: `ses-${Date.now()}`,
    candidateCount: candidates.length,
    appliedFilters: filters,
    narrowingHistory: history,
    resolutionStatus: checkResolution(candidates, history),
    resolvedInput: input,
    turnCount,
  }

  // Run request preparation for metadata
  const requestPrep = prepareRequest(form, messages, sessionState, input, candidates.length)

  const responseText = recommendation.llmSummary ?? deterministicSummary
  const candidateSnapshot = buildCandidateSnapshot(candidates, evidenceMap)

  return NextResponse.json({
    text: status === "none"
      ? "조건에 맞는 제품을 찾지 못했습니다. 직경이나 소재 조건을 조정해보세요."
      : responseText,
    purpose: "recommendation",
    chips: getFollowUpChips(recommendation),
    isComplete: true,
    recommendation,
    sessionState,
    evidenceSummaries: evidenceSummaries.length > 0 ? evidenceSummaries : null,
    candidateSnapshot,
    extractedField: null,
    // New fields
    requestPreparation: requestPrep,
    primaryExplanation,
    primaryFactChecked: primaryFactChecked ? serializeFactChecked(primaryFactChecked) : null,
    altExplanations,
    altFactChecked: altFactChecked.map(fc => serializeFactChecked(fc)),
  })
}

// ── Contextual Narrowing Question Handler ────────────────────
async function handleContextualNarrowingQuestion(
  provider: ReturnType<typeof getProvider>,
  userMessage: string,
  _currentInput: RecommendationInput,
  candidates: ScoredProduct[],
  prevState: ExplorationSessionState
): Promise<string | null> {
  const lastField = prevState.lastAskedField ?? "unknown"

  // Build context about what options exist in candidates for this field
  const fieldExplanations: Record<string, () => string> = {
    coating: () => {
      const coatings = [...new Set(candidates.map(c => c.product.coating).filter(Boolean))]
      return `코팅 종류에 대해 설명드리겠습니다.

현재 후보 제품들의 코팅 종류:
${coatings.map(c => `• ${c}`).join("\n")}

간단 설명:
• DLC (Diamond-Like Carbon) — 알루미늄/비철금속에 최적. 낮은 마찰, 높은 내마모성
• TiAlN — 고온 가공에 적합. 내열성 우수 (강, 스테인리스)
• AlCrN — 고경도 소재 가공용. TiAlN보다 더 높은 내열성
• TiCN — 범용. 중간 경도, 탄소강/합금강에 적합
• Blue Coating — YG-1 자체 코팅. 범용 가공에 적합
• 무코팅 — 알루미늄/구리 등 연질 소재에 사용

모르시면 "상관없음"을 선택하면 전체 후보에서 추천해드립니다.`
    },
    fluteCount: () => {
      const flutes = [...new Set(candidates.map(c => c.product.fluteCount).filter(Boolean))].sort()
      return `날 수(flute)에 대해 설명드리겠습니다.

현재 후보 제품 날 수: ${flutes.join(", ")}날

• 2날 — 알루미늄/비철 가공, 칩 배출 우수 (황삭에 유리)
• 3날 — 범용. 황삭~정삭 겸용
• 4날 — 정삭/고정밀 가공. 표면 품질 우수
• 6날 이상 — 고이송 가공, 높은 생산성

모르시면 "상관없음"을 선택해주세요.`
    },
    diameterRefine: () => {
      const diameters = [...new Set(candidates.map(c => c.product.diameterMm).filter((d): d is number => d != null))].sort((a, b) => a - b)
      const min = diameters[0]
      const max = diameters[diameters.length - 1]
      return `직경은 가공하려는 형상과 장비에 따라 선택합니다.

현재 후보 직경 범위: ${min}mm ~ ${max}mm
가용 직경: ${diameters.slice(0, 10).join(", ")}mm${diameters.length > 10 ? " ..." : ""}

직경을 모르시면 "상관없음"을 선택해주세요.`
    },
  }

  const explainer = fieldExplanations[lastField]
  if (explainer) return explainer()

  // Fallback: use LLM for other fields
  if (provider.available()) {
    try {
      const raw = await provider.complete(
        "당신은 YG-1 절삭공구 전문 엔지니어입니다. 사용자가 추천 대화 중 현재 질문에 대해 '그게 뭐야?' 같은 질문을 했습니다. 간결하게 3-4문장으로 설명하세요.",
        [{ role: "user", content: `현재 질문 필드: ${lastField}\n사용자 질문: ${userMessage}\n현재 후보 수: ${candidates.length}개` }],
        400
      )
      if (raw?.trim()) return raw.trim()
    } catch { /* fallback below */ }
  }

  return `현재 ${candidates.length}개 후보가 있습니다. 잘 모르시면 "상관없음"을 선택해주세요.`
}

// ── Post-Recommendation Follow-Up Handler ────────────────────
async function handlePostRecommendationFollowUp(
  provider: ReturnType<typeof getProvider>,
  userMessage: string,
  currentInput: RecommendationInput,
  candidates: ScoredProduct[],
  evidenceMap: Map<string, EvidenceSummary>,
  form: ProductIntakeForm
): Promise<string | null> {
  if (!provider.available()) return null

  const clean = userMessage.trim()

  // Reset / new search signals should NOT be handled here
  if (/처음부터|다시 시작|리셋|다른 직경|다른 소재|새로운/.test(clean)) return null

  // Build context about recommended products
  const topProducts = candidates.slice(0, 5)
  const productContext = topProducts.map((sp, i) => {
    const p = sp.product
    const ev = evidenceMap.get(p.normalizedCode)
    const lines = [
      `${i + 1}. ${p.displayCode} (${p.seriesName})`,
      `   소재군: ${p.materialTags.join(", ")}`,
      `   직경: ${p.diameterMm}mm, 날수: ${p.fluteCount ?? "?"}`,
      `   코팅: ${p.coating ?? "미상"}`,
      `   점수: ${sp.score}/${sp.scoreBreakdown?.maxTotal ?? 110}pt (${sp.matchStatus})`,
    ]
    if (ev?.bestCondition) {
      const c = ev.bestCondition
      lines.push(`   절삭조건: Vc=${c.Vc ?? "?"}, fz=${c.fz ?? "?"}, ap=${c.ap ?? "?"}, ae=${c.ae ?? "?"}`)
    }
    if (ev && !ev.bestCondition && ev.sourceCount > 0) {
      lines.push(`   절삭조건: ${ev.sourceCount}건 참조 데이터 있음 (조건 상세 미확인)`)
    }
    return lines.join("\n")
  }).join("\n\n")

  const materialInfo = currentInput.material ?? (form.material.status === "known" ? form.material.value : "미지정")
  const diameterInfo = currentInput.diameterMm ? `${currentInput.diameterMm}mm` : "미지정"

  try {
    const systemPrompt = `당신은 YG-1 절삭공구 전문 엔지니어 출신 AI입니다.
사용자가 이미 추천 결과를 받은 후, 후속 질문을 하고 있습니다.

═══ 현재 추천 상황 ═══
- 요청 소재: ${materialInfo}
- 요청 직경: ${diameterInfo}
- 가공 형상: ${form.operationType.status === "known" ? form.operationType.value : "미지정"}
- 추천 제품 ${topProducts.length}개:

${productContext}

═══ 응답 규칙 ═══
- 위 추천 제품 데이터만 기반으로 답변
- 절삭조건(Vc, fz, ap, ae)은 위에 나온 데이터에서만 인용 (없으면 "해당 제품의 카탈로그 절삭조건 데이터가 없습니다" 안내)
- 코팅 비교, 제품 비교 등은 위 제품들 간 비교
- 한국어로 간결하게 3-6문장
- 구체적 수치 포함
- 데이터에 없는 정보는 생성하지 말 것`

    const raw = await provider.complete(systemPrompt, [
      { role: "user", content: clean }
    ], 1000)
    if (raw && raw.trim()) return raw.trim()
  } catch (e) {
    console.warn("[recommend] Follow-up handler failed:", e)
  }
  return null
}

// ── General Chat Handler (non-product questions) ──────────────
// Unified handler: greetings, general knowledge, off-domain, system questions
async function handleGeneralChat(
  provider: ReturnType<typeof getProvider>,
  userMessage: string,
  _currentInput: RecommendationInput,
  candidates: ScoredProduct[],
  form: ProductIntakeForm,
): Promise<{ text: string; chips: string[] }> {
  const clean = userMessage.trim()
  const candidateCount = candidates.length

  // Fallback if LLM not available
  if (!provider.available()) {
    return {
      text: "안녕하세요! YG-1 절삭공구 추천 시스템입니다. 가공 조건을 알려주시면 최적의 제품을 추천해드립니다.",
      chips: ["스테인리스 가공", "알루미늄 10mm", "엔드밀 추천", "절삭조건 문의"],
    }
  }

  // Build context about current session for richer answers
  const sessionContext = candidateCount > 0
    ? `현재 ${candidateCount}개 후보 제품이 검색되어 있습니다.`
    : ""

  const formContext = form.material.status === "known" || form.operationType.status === "known"
    ? `사용자 입력 조건: 소재=${form.material.status === "known" ? form.material.value : "미지정"}, 가공=${form.operationType.status === "known" ? form.operationType.value : "미지정"}`
    : ""

  try {
    const systemPrompt = `당신은 YG-1의 절삭공구 전문 AI 어시스턴트입니다.
YG-1은 한국의 세계적인 절삭공구 제조사입니다.

═══ 역할 ═══
- 절삭공구, 가공 기술, 소재, 코팅에 대한 전문 지식
- CNC 가공 현장 경험 기반 실용적 조언
- 시스템/화면 용어 설명
- 절삭공구 무관한 질문에도 유연하게 대응

═══ 시스템 정보 (사용자가 물어볼 때) ═══
- 약 36,000개 YG-1 절삭공구 제품 데이터 보유
- 스코어링: 직경(40pt), 소재(20pt), 날수(15pt), 가공방식(15pt), 절삭조건(10pt), 코팅(5pt), 완성도(5pt) = 110점 만점
- 정확 매칭(75%↑), 근사 매칭(45~75%), 매칭 없음(45%↓)
- 팩트 체크: 추천 제품 스펙이 DB 데이터와 일치하는지 자동 검증
- ISO 소재 분류: P=탄소강, M=스테인리스, K=주철, N=비철/알루미늄, S=내열합금/티타늄, H=고경도강
- 할루시네이션 방지: 모든 데이터는 DB에서만 인용

═══ 기술 지식 ═══
## ISO 소재 분류
- P (파란색): 탄소강, 합금강, 공구강
- M (노란색): 스테인리스강 — 가공경화 주의
- K (빨간색): 주철, CGI — 짧은 칩, 마모 주의
- N (초록색): 알루미늄, 비철 — 고속 가공, 구성인선 주의
- S (갈색): 내열합금, 티타늄 — 저속, 고압 쿨란트 필수
- H (회색): 고경도강 HRc 40~65

## 코팅
- TiAlN: 고온 내마모, 고경도강/SUS용, 건식 가공
- AlCrN: 내열성 우수, 고속/난삭재
- DLC: 알루미늄/비철용, 낮은 마찰
- 무코팅: 비철 전용, 날카로운 인선

## 가공 종류
- 황삭: 높은 이송, 깊은 절입, 4~6날
- 정삭: 낮은 이송, 면조도 우선, 2~4날
- 슬롯: 100% 물림, 칩 배출 중요
- 측면: 진동 주의

${sessionContext}
${formContext}

═══ 응답 규칙 ═══
- 한국어로 자연스럽게 대화
- 간결하게 (2-5문장)
- 절삭공구 무관한 질문: 짧게 답변 후 "절삭공구 관련 질문도 도와드릴 수 있어요" 정도만
- 기술 질문: 구체적 수치와 비교 포함
- "추가 조건을 알려주시면~" 같은 빈 말 금지
- 응답 끝에 JSON이나 특수 포맷 쓰지 말고 순수 자연어로만`

    const raw = await provider.complete(systemPrompt, [
      { role: "user", content: clean }
    ], 800)

    if (raw && raw.trim()) {
      // Generate contextual chips based on question type
      const chips = generateFollowUpChips(clean, candidateCount)
      return { text: raw.trim(), chips }
    }
  } catch (e) {
    console.warn("[recommend] General chat handler failed:", e)
  }

  // Fallback
  return {
    text: "죄송합니다, 잠시 오류가 있었습니다. 절삭공구 관련 질문이나 가공 조건을 말씀해주세요.",
    chips: ["스테인리스 가공", "알루미늄 10mm", "엔드밀 추천", "절삭조건 문의"],
  }
}

// Generate contextual follow-up chips
function generateFollowUpChips(userMessage: string, candidateCount: number): string[] {
  const lower = userMessage.toLowerCase()

  // If asking about coatings
  if (/코팅|tialn|alcrn|dlc/i.test(lower)) {
    return ["코팅별 적합 소재", "무코팅 vs DLC", "소재별 추천 코팅", "제품 추천"]
  }
  // If asking about materials
  if (/소재|알루|스테인|주철|티타늄|가공/i.test(lower)) {
    return ["절삭조건 알려줘", "추천 코팅은?", "주의사항 더 알려줘", "제품 추천"]
  }
  // If asking about the system
  if (/시스템|점수|매칭|어떻게/i.test(lower)) {
    return ["점수 기준 설명", "소재 태그 뜻", "팩트 체크란?", "제품 추천"]
  }
  // Default
  if (candidateCount > 0) {
    return ["후보 제품 보기", "절삭조건 문의", "코팅 비교", "처음부터 다시"]
  }
  return ["제품 추천", "절삭조건 문의", "코팅 비교", "시리즈 검색"]
}

// ── Tool definitions for LLM-powered extraction ─────────────
const EXTRACTION_TOOL: import("@/lib/llm/provider").LLMTool = {
  name: "extract_cutting_tool_params",
  description: `Extract cutting tool parameters from a Korean user message in a machining/CNC context.
This tool is used to parse user responses during a product recommendation conversation.
The user may provide: material (소재), diameter (직경), flute count (날 수), coating, operation type, or signal that they want to skip/complete.`,
  input_schema: {
    type: "object",
    properties: {
      intent: {
        type: "string",
        enum: ["provide_param", "skip_question", "show_results", "reset", "off_topic"],
        description: "What the user wants: provide_param (giving a machining parameter), skip_question (don't care / don't know), show_results (wants recommendations now), reset (start over), off_topic (not about cutting tools)",
      },
      material: {
        type: "string",
        description: "Workpiece material if mentioned. Normalize to: 탄소강, 합금강, 공구강, 스테인리스, 알루미늄, 주철, 티타늄, 인코넬, 내열합금, 고경도강, 구리, 비철금속. Null if not mentioned.",
        nullable: true,
      },
      diameterMm: {
        type: "number",
        description: "Tool diameter in mm if mentioned. Null if not mentioned.",
        nullable: true,
      },
      fluteCount: {
        type: "integer",
        description: "Number of flutes (날 수) if mentioned. Null if not mentioned.",
        nullable: true,
      },
      coating: {
        type: "string",
        description: "Coating type if mentioned (e.g., TiAlN, AlCrN, DLC, Uncoated, Blue Coating). Null if not mentioned.",
        nullable: true,
      },
      operationType: {
        type: "string",
        description: "Machining operation if mentioned (e.g., 황삭, 정삭, 중삭, 슬롯, 측면, 프로파일). Null if not mentioned.",
        nullable: true,
      },
      toolSubtype: {
        type: "string",
        description: "Tool subtype if mentioned (e.g., flat, ball, square, chamfer, radius, corner). Null if not mentioned.",
        nullable: true,
      },
      seriesName: {
        type: "string",
        description: "YG-1 series name if mentioned (e.g., CE5, CE7, GNX, SEME61). Null if not mentioned.",
        nullable: true,
      },
      reasoning: {
        type: "string",
        description: "Brief reasoning about what the user wants (1 sentence, in Korean).",
      },
    },
    required: ["intent", "reasoning"],
  },
}

// ── Extract Parameters from User Message ─────────────────────
async function extractParamsFromMessage(
  provider: ReturnType<typeof getProvider>,
  message: string,
  currentInput: RecommendationInput,
  prevState: ExplorationSessionState
): Promise<{ isComplete: boolean; newFilter: AppliedFilter | null; skippedField: string | null } | null> {
  const clean = message.trim().toLowerCase()

  // ── Use lastAskedField from session state (reliable) ──
  const lastAskedField = prevState.lastAskedField ?? inferCurrentQuestionField(currentInput, prevState)

  // ── Fast-path: deterministic signals (no LLM needed) ──

  // 1. Reset signals
  if (["처음부터 다시", "처음부터", "다시 시작", "리셋"].some(s => clean.includes(s))) {
    return { isComplete: true, newFilter: null, skippedField: null }
  }

  // 2. Completion signals — expanded to catch vague/impatient requests
  const completionSignals = [
    "추천해주세요", "바로 보여주세요", "결과 보기", "추천 받기", "추가 조건 없음", "그냥 추천", "바로 추천",
    "그냥 좋은 거", "좋은 거", "좋은거", "니가 알아서", "알아서 골라", "알아서 추천",
    "그냥 줘", "빨리", "빨리 줘", "빨리빨리", "걍 줘", "걍", "그냥",
    "무난한 거", "무난한거", "무난하게", "대충", "대충 추천",
    "많이 쓰는 거", "많이 쓰는거", "인기 있는", "인기있는", "베스트",
    "3개만", "3개 줘", "세개만", "세 개만", "몇 개만", "몇개만",
    "왜 자꾸 물어", "질문 그만", "그만 물어", "더 이상 질문",
    "결과", "보여줘", "바로 보여", "바로보여", "빨리 보여",
    "대체 후보", "후보 보기", "개 보기",
    "다 보여", "전부 보여", "다보여",
  ]
  if (completionSignals.some(s => clean.includes(s))) {
    return { isComplete: true, newFilter: null, skippedField: null }
  }

  // 3. Skip / don't-care / don't-know — BEFORE LLM call
  const skipPatterns = [
    "상관없", "상관 없", "아무거나", "아무 거나", "다 괜찮", "괜찮아", "뭐든",
    "모름", "몰라", "모르겠", "모른다", "모릅니다", "잘 모르", "잘모르", "글쎄",
    "패스", "넘어가", "넘겨", "다음", "스킵", "skip", "pass", "next",
    "넘어", "다음으로",
  ]
  if (skipPatterns.some(s => clean.includes(s))) {
    return { isComplete: false, newFilter: null, skippedField: lastAskedField !== "unknown" ? lastAskedField : null }
  }

  // ── PRIMARY: LLM-powered extraction via tool_use ──
  if (provider.available()) {
    try {
      const currentState = [
        `현재 질문 필드: ${lastAskedField}`,
        `현재 입력 상태: material=${currentInput.material ?? "미지정"}, diameter=${currentInput.diameterMm ?? "미지정"}mm, flute=${currentInput.flutePreference ?? "미지정"}, coating=${currentInput.coatingPreference ?? "미지정"}, operation=${currentInput.operationType ?? "미지정"}`,
        `이전 대화 턴 수: ${prevState.turnCount}`,
        `현재 후보 수: ${prevState.candidateCount}개`,
      ].join("\n")

      const extractionPrompt = `절삭공구 추천 대화 중입니다.

${currentState}

사용자 메시지: "${message}"

위 메시지를 분석하여 절삭공구 관련 파라미터를 추출하세요. 절삭공구와 관련 없는 메시지라면 intent를 "off_topic"으로 설정하세요.`

      const result = await provider.completeWithTools(
        "당신은 YG-1 절삭공구 파라미터 추출 엔진입니다. 사용자 메시지에서 가공 조건을 정확히 추출하세요.",
        [{ role: "user", content: extractionPrompt }],
        [EXTRACTION_TOOL],
        512
      )

      if (result.toolUse && result.toolUse.toolName === "extract_cutting_tool_params") {
        const params = result.toolUse.input
        console.log(`[recommend] LLM extraction: intent=${params.intent}, reasoning=${params.reasoning}`)

        // Map LLM intent to action
        if (params.intent === "reset") return { isComplete: true, newFilter: null, skippedField: null }
        if (params.intent === "show_results") return { isComplete: true, newFilter: null, skippedField: null }
        if (params.intent === "skip_question") {
          return { isComplete: false, newFilter: null, skippedField: lastAskedField !== "unknown" ? lastAskedField : null }
        }
        if (params.intent === "off_topic") return null

        // Extract parameters — build filters from what was extracted
        const filters: AppliedFilter[] = []

        if (params.material && typeof params.material === "string") {
          const currentMat = (currentInput.material || "").toLowerCase()
          if (!currentMat.includes(params.material.toLowerCase())) {
            const f = parseAnswerToFilter("material", params.material as string)
            if (f) filters.push(f)
          }
        }

        if (params.diameterMm != null && typeof params.diameterMm === "number") {
          const f = parseAnswerToFilter("diameterRefine", `${params.diameterMm}mm`)
          if (f) filters.push(f)
        }

        if (params.fluteCount != null && typeof params.fluteCount === "number" && !currentInput.flutePreference) {
          const f = parseAnswerToFilter("fluteCount", `${params.fluteCount}날`)
          if (f) filters.push(f)
        }

        if (params.coating && typeof params.coating === "string" && !currentInput.coatingPreference) {
          const f = parseAnswerToFilter("coating", params.coating as string)
          if (f) filters.push(f)
        }

        if (params.operationType && typeof params.operationType === "string" && !currentInput.operationType) {
          const f = parseAnswerToFilter("cuttingType", params.operationType as string)
          if (f) filters.push(f)
        }

        if (params.toolSubtype && typeof params.toolSubtype === "string") {
          const f = parseAnswerToFilter("toolSubtype", params.toolSubtype as string)
          if (f) filters.push(f)
        }

        if (params.seriesName && typeof params.seriesName === "string") {
          const f = parseAnswerToFilter("seriesName", params.seriesName as string)
          if (f) filters.push(f)
        }

        // Return the most impactful filter, attach rest as side filters
        if (filters.length > 0) {
          const primary = filters[0]
          if (filters.length > 1) {
            ;(primary as unknown as Record<string, unknown>)._sideFilters = filters.slice(1)
          }
          return { isComplete: false, newFilter: primary, skippedField: null }
        }

        // LLM detected provide_param but couldn't extract anything specific
        // Fall through to keyword matching
      }
    } catch (e) {
      console.warn("[recommend] LLM tool_use extraction failed, falling back to keywords:", e)
    }
  }

  // ── FALLBACK: Keyword-based extraction ──
  const materialKeywordMap: Record<string, string> = {
    "탄소강": "탄소강", "합금강": "합금강", "공구강": "공구강",
    "스테인리스": "스테인리스", "sus": "스테인리스", "스텐": "스테인리스",
    "알루미늄": "알루미늄", "알루": "알루미늄", "alu": "알루미늄",
    "주철": "주철", "cast iron": "주철",
    "티타늄": "티타늄", "titanium": "티타늄",
    "인코넬": "인코넬", "inconel": "인코넬", "내열합금": "내열합금",
    "고경도": "고경도강", "고경도강": "고경도강", "hrc": "고경도강",
    "구리": "구리", "copper": "구리", "비철": "비철금속",
  }
  const detectedMaterial = Object.keys(materialKeywordMap).find(k => clean.includes(k))
  const diamMatch = clean.match(/([\d.]+)\s*mm/)
  const fluteMatch = clean.match(/(\d+)\s*날/)
  const subtypeKeywords = ["flat", "플랫", "ball", "볼", "chamfer", "챔퍼", "radius", "래디우스", "corner", "square", "스퀘어"]
  const foundSubtype = subtypeKeywords.find(k => clean.includes(k))

  // Multi-param
  const paramCount = [detectedMaterial, diamMatch, fluteMatch, foundSubtype].filter(Boolean).length
  if (paramCount >= 2 && detectedMaterial) {
    const matVal = materialKeywordMap[detectedMaterial]
    const filter = parseAnswerToFilter("material", matVal)
    if (filter) {
      const sideFilters: AppliedFilter[] = []
      if (diamMatch) { const df = parseAnswerToFilter("diameterRefine", `${diamMatch[1]}mm`); if (df) sideFilters.push(df) }
      if (foundSubtype) { const sf = parseAnswerToFilter("toolSubtype", foundSubtype); if (sf) sideFilters.push(sf) }
      if (fluteMatch) { const ff = parseAnswerToFilter("fluteCount", `${fluteMatch[1]}날`); if (ff) sideFilters.push(ff) }
      ;(filter as unknown as Record<string, unknown>)._sideFilters = sideFilters
      return { isComplete: false, newFilter: filter, skippedField: null }
    }
  }

  // Single-param fallbacks
  if (detectedMaterial) {
    const matVal = materialKeywordMap[detectedMaterial]
    const currentMaterial = (currentInput.material || "").toLowerCase()
    if (!currentMaterial.includes(matVal)) {
      const filter = parseAnswerToFilter("material", matVal)
      return { isComplete: false, newFilter: filter, skippedField: null }
    }
  }
  if (fluteMatch && !currentInput.flutePreference) {
    return { isComplete: false, newFilter: parseAnswerToFilter("fluteCount", message), skippedField: null }
  }
  if (diamMatch) {
    return { isComplete: false, newFilter: parseAnswerToFilter("diameterRefine", message), skippedField: null }
  }

  const coatingKeywords = ["altin", "tialn", "dlc", "무코팅", "y-코팅", "y코팅", "ticn", "blue", "블루", "블루코팅", "uncoated", "코팅 없", "노코팅"]
  const foundCoating = coatingKeywords.find(k => clean.includes(k))
  if (foundCoating && !currentInput.coatingPreference) {
    let coatingVal = foundCoating.toUpperCase()
    if (["blue", "블루", "블루코팅"].includes(foundCoating)) coatingVal = "Blue Coating"
    else if (["무코팅", "uncoated", "코팅 없", "노코팅"].includes(foundCoating)) coatingVal = "Uncoated"
    return { isComplete: false, newFilter: parseAnswerToFilter("coating", coatingVal), skippedField: null }
  }

  const seriesPatterns = [/^(ce\d+[a-z]*\d*)/i, /^(gnx\d+)/i, /^(sem[a-z]*\d+)/i, /^(e\d+[a-z]\d+)/i]
  if (seriesPatterns.find(p => p.test(clean))) {
    return { isComplete: false, newFilter: parseAnswerToFilter("seriesName", message.trim()), skippedField: null }
  }

  if (foundSubtype) {
    return { isComplete: false, newFilter: parseAnswerToFilter("toolSubtype", message.trim()), skippedField: null }
  }

  const cuttingKeywords = ["슬롯", "측면", "프로파일", "황삭", "정삭"]
  const foundCutting = cuttingKeywords.find(k => clean.includes(k))
  if (foundCutting) {
    return { isComplete: false, newFilter: parseAnswerToFilter("cuttingType", message), skippedField: null }
  }

  // Bare number → likely diameter
  if (/^\d+(\.\d+)?$/.test(clean)) {
    return { isComplete: false, newFilter: parseAnswerToFilter("diameterRefine", `${clean}mm`), skippedField: null }
  }

  // Truly unrecognizable
  return null
}

// ── Infer which field the question engine was asking about ────
function inferCurrentQuestionField(
  input: RecommendationInput,
  prevState: ExplorationSessionState
): string {
  // Use the actual question engine to determine what's being asked
  // This ensures perfect sync between what was asked and what we infer
  const filters: AppliedFilter[] = prevState?.appliedFilters ?? []
  const currentInput = prevState?.resolvedInput
    ? { ...input, ...prevState.resolvedInput }
    : input
  const hybridResult = runHybridRetrieval(currentInput, filters)
  const question = selectNextQuestion(currentInput, hybridResult.candidates, prevState.narrowingHistory ?? [])
  if (question) return question.field

  // Fallback: check by priority if question engine returns null
  const askedFields = new Set(
    prevState.narrowingHistory.flatMap(h => h.extractedFilters.map(f => f.field))
  )
  if (!input.flutePreference && !askedFields.has("fluteCount")) return "fluteCount"
  if (!input.coatingPreference && !askedFields.has("coating")) return "coating"
  if (!askedFields.has("seriesName")) return "seriesName"
  if (!input.toolSubtype && !askedFields.has("toolSubtype")) return "toolSubtype"
  if (!askedFields.has("cuttingType")) return "cuttingType"
  if (!askedFields.has("diameterRefine")) return "diameterRefine"
  return "unknown"
}

// ── Apply filter to RecommendationInput ──────────────────────
function applyFilterToInput(input: RecommendationInput, filter: AppliedFilter): RecommendationInput {
  let updated = { ...input }
  updated = applySingleFilter(updated, filter)

  // Apply side filters if present (from multi-param extraction)
  const sideFilters = (filter as unknown as Record<string, unknown>)._sideFilters as AppliedFilter[] | undefined
  if (sideFilters && Array.isArray(sideFilters)) {
    for (const sf of sideFilters) {
      updated = applySingleFilter(updated, sf)
    }
  }

  return updated
}

function applySingleFilter(input: RecommendationInput, filter: AppliedFilter): RecommendationInput {
  const updated = { ...input }
  switch (filter.field) {
    case "fluteCount":
      updated.flutePreference = typeof filter.rawValue === "number" ? filter.rawValue : parseInt(String(filter.rawValue))
      break
    case "coating":
      updated.coatingPreference = String(filter.rawValue)
      break
    case "diameterMm":
    case "diameterRefine":
      updated.diameterMm = typeof filter.rawValue === "number" ? filter.rawValue : parseFloat(String(filter.rawValue))
      break
    case "material":
      updated.material = String(filter.rawValue)
      break
    case "toolSubtype":
      updated.toolSubtype = String(filter.rawValue)
      break
    case "cuttingType":
      if (!updated.operationType) updated.operationType = String(filter.rawValue)
      break
  }
  return updated
}

// ── Build Candidate Snapshot (lightweight for UI) ────────────
function buildCandidateSnapshot(
  candidates: ScoredProduct[],
  evidenceMap: Map<string, EvidenceSummary>
): CandidateSnapshot[] {
  return candidates.map((c, i) => {
    const ev = evidenceMap.get(c.product.normalizedCode)
    return {
      rank: i + 1,
      productCode: c.product.normalizedCode,
      displayCode: c.product.displayCode,
      brand: c.product.brand ?? null,
      seriesName: c.product.seriesName,
      seriesIconUrl: c.product.seriesIconUrl ?? null,
      diameterMm: c.product.diameterMm,
      fluteCount: c.product.fluteCount,
      coating: c.product.coating,
      materialTags: c.product.materialTags,
      score: c.score,
      scoreBreakdown: c.scoreBreakdown,
      matchStatus: c.matchStatus,
      stockStatus: c.stockStatus,
      totalStock: c.totalStock,
      hasEvidence: !!ev && ev.chunks.length > 0,
      bestCondition: ev?.bestCondition ?? null,
    }
  })
}

// ════════════════════════════════════════════════════════════════
// SIMPLE CHAT HANDLER (legacy)
// ════════════════════════════════════════════════════════════════

async function handleSimpleChat(messages: ChatMessage[], mode: string): Promise<Response> {
  if (!messages.length) {
    return NextResponse.json({ error: "messages required" }, { status: 400 })
  }

  const latestUserMsg = [...messages].reverse().find(m => m.role === "user")?.text ?? ""
  const baseInput = normalizeInput(latestUserMsg)
  const provider = getProvider()

  // Quick check if enough info
  const hasEnough = !!(baseInput.diameterMm || (baseInput.material && baseInput.operationType))

  if (hasEnough) {
    const result = runHybridRetrieval(baseInput, [], 5)
    const { primary, alternatives, status } = classifyHybridResults(result)
    const warnings = primary ? buildWarnings(primary, baseInput) : []
    const rationale = primary ? buildRationale(primary, baseInput) : []

    const deterministicSummary = buildDeterministicSummary({
      status, query: baseInput, primaryProduct: primary, alternatives,
      warnings, rationale, sourceSummary: [], deterministicSummary: "",
      llmSummary: null, totalCandidatesConsidered: result.totalConsidered,
    })

    const recommendation: RecommendationResult = {
      status, query: baseInput, primaryProduct: primary, alternatives,
      warnings, rationale, sourceSummary: primary ? buildSourceSummary(primary) : [],
      deterministicSummary, llmSummary: null,
      totalCandidatesConsidered: result.totalConsidered,
    }

    return NextResponse.json({
      text: deterministicSummary,
      purpose: "recommendation",
      chips: getFollowUpChips(recommendation),
      isComplete: true,
      recommendation,
      sessionState: null,
      evidenceSummaries: null,
      candidateSnapshot: null,
    })
  }

  // Not enough info — ask question
  return NextResponse.json({
    text: getNextQuestion(baseInput),
    purpose: "question",
    chips: getDefaultChips(baseInput),
    isComplete: false,
    recommendation: null,
    sessionState: null,
    evidenceSummaries: null,
    candidateSnapshot: null,
  })
}

// ════════════════════════════════════════════════════════════════
// HELPERS
// ════════════════════════════════════════════════════════════════

function getKnown<T>(state: AnswerState<T>): T | undefined {
  return state.status === "known" ? (state as { status: "known"; value: T }).value : undefined
}

function parseIntakeDiameter(text: string): number | null {
  if (!text) return null
  const clean = text.trim()
  const mmMatch = clean.match(/^(\d+(?:\.\d+)?)\s*mm?$/i)
  if (mmMatch) return parseFloat(mmMatch[1])
  const numMatch = clean.match(/^(\d+(?:\.\d+)?)$/)
  if (numMatch) {
    const n = parseFloat(numMatch[1])
    return n > 0 && n <= 200 ? n : null
  }
  const inchFrac = clean.match(/^(\d+)\s*\/\s*(\d+)\s*(?:inch|인치|")?$/i)
  if (inchFrac) {
    return Math.round((parseInt(inchFrac[1]) / parseInt(inchFrac[2])) * 25.4 * 100) / 100
  }
  return null
}

function mapIntakeToInput(form: ProductIntakeForm): RecommendationInput {
  const input: Partial<RecommendationInput> = {
    manufacturerScope: "yg1-only",
    locale: "ko",
  }
  // Material: may be comma-separated for multi-select (e.g. "알루미늄,스테인리스")
  const material = getKnown(form.material)
  if (material) input.material = material  // keeps comma-separated string; hybrid-retrieval resolves each
  const opParts: string[] = []
  const intent = getKnown(form.machiningIntent as AnswerState<MachiningIntent>)
  const intentMap: Record<MachiningIntent, string> = { roughing: "황삭", semi: "중삭", finishing: "정삭" }
  if (intent) opParts.push(intentMap[intent])
  // OperationType: may be comma-separated for multi-select (e.g. "측면가공,슬롯")
  const opType = getKnown(form.operationType)
  if (opType) {
    // Split comma-separated and add each part
    const ops = opType.split(",").map(s => s.trim()).filter(Boolean)
    opParts.push(...ops)
  }
  if (opParts.length > 0) input.operationType = opParts.join(" ")
  const diamStr = getKnown(form.diameterInfo)
  if (diamStr) {
    const diam = parseIntakeDiameter(diamStr)
    if (diam !== null) input.diameterMm = diam
  }
  const toolType = getKnown(form.toolTypeOrCurrentProduct)
  if (toolType) input.toolType = toolType
  return input as RecommendationInput
}

function getNextQuestion(input: RecommendationInput): string {
  if (!input.material) return "어떤 소재를 가공하실 예정인가요?"
  if (!input.operationType) return "어떤 가공 방식이 필요하신가요? (황삭/정삭/고이송 등)"
  if (!input.diameterMm) return "공구 직경은 몇 mm가 필요하신가요?"
  if (!input.flutePreference) return "날 수(flute) 선호도가 있으신가요?"
  return "추가로 확인이 필요한 조건이 있으신가요?"
}

function getDefaultChips(input: RecommendationInput): string[] {
  if (!input.material) return ["알루미늄", "스테인리스", "탄소강", "주철", "티타늄", "고경도강"]
  if (!input.operationType) return ["황삭", "정삭", "고이송", "슬롯가공", "측면가공"]
  if (!input.diameterMm) return ["2mm", "4mm", "6mm", "8mm", "10mm", "12mm"]
  if (!input.flutePreference) return ["2날", "3날", "4날", "6날", "상관없음"]
  return ["추천 받기", "다른 조건으로", "경쟁사 비교"]
}

function getFollowUpChips(result: RecommendationResult): string[] {
  const chips = []
  if (result.alternatives.length > 0) chips.push(`대체 후보 ${result.alternatives.length}개 보기`)
  chips.push("절삭조건 알려줘")
  chips.push("코팅 비교")
  if (result.primaryProduct?.stockStatus === "outofstock") chips.push("납기 확인")
  chips.push("다른 직경 검색")
  chips.push("처음부터 다시")
  return chips.slice(0, 6)
}

function buildSourceSummary(primary: { product: { rawSourceFile: string; rawSourceSheet?: string | null; sourceConfidence?: string | null } } | null): string[] {
  if (!primary) return []
  const p = primary.product
  return [
    `Source: ${p.rawSourceFile}${p.rawSourceSheet ? ` / ${p.rawSourceSheet}` : ""}`,
    `Confidence: ${p.sourceConfidence ?? "unknown"}`,
  ]
}

/** Serialize FactCheckedRecommendation to plain object (strip non-serializable data) */
function serializeFactChecked(fc: FactCheckedRecommendation): Record<string, unknown> {
  return {
    productCode: fc.productCode,
    displayCode: fc.displayCode,
    seriesName: fc.seriesName,
    manufacturer: fc.manufacturer,
    diameterMm: fc.diameterMm,
    fluteCount: fc.fluteCount,
    coating: fc.coating,
    toolMaterial: fc.toolMaterial,
    materialTags: fc.materialTags,
    lengthOfCutMm: fc.lengthOfCutMm,
    overallLengthMm: fc.overallLengthMm,
    hasCuttingConditions: fc.hasCuttingConditions,
    bestCondition: fc.bestCondition,
    conditionConfidence: fc.conditionConfidence,
    conditionSourceCount: fc.conditionSourceCount,
    stockStatus: fc.stockStatus,
    totalStock: fc.totalStock,
    minLeadTimeDays: fc.minLeadTimeDays,
    matchPct: fc.matchPct,
    matchStatus: fc.matchStatus,
    score: fc.score,
    explanation: fc.explanation,
    factCheckReport: fc.factCheckReport,
  }
}

function safeParseJSON(raw: string): Record<string, unknown> | null {
  try {
    const cleaned = raw.replace(/```json\n?|\n?```/g, "").trim()
    return JSON.parse(cleaned)
  } catch {
    return null
  }
}
