"use client"

import { useState, useEffect, useCallback } from "react"
import {
  Search,
  BookOpen,
  FileText,
  MessageSquare,
  Tag,
  ChevronLeft,
  ChevronRight,
  Loader2,
  Languages,
  Filter,
  Lightbulb,
  Hash,
  Network,
  GitBranch,
  Database,
  Layers,
} from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { useApp } from "@/lib/store"

const CATEGORY_LABELS: Record<string, string> = {
  product_overview: "제품 개요",
  material_target: "소재 적합",
  feature: "특징",
  tool_shape: "형상/사양",
  application: "용도",
  selection: "제품 선택",
  coating_material: "코팅/재질",
  brand_overview: "브랜드 개요",
  brand_lineup: "브랜드 라인업",
  brand_application: "브랜드 용도",
}

const FEATURE_KEY_LABELS: Record<string, string> = {
  target_material: "소재별",
  application: "용도별",
  iso_group: "ISO 그룹별",
  tool_subtype: "형상별",
  flute_count: "날수별",
  coating: "코팅별",
  "material+tool_type": "소재+공구타입",
  "material+flute_count": "소재+날수",
  "iso+tool_subtype": "ISO+형상",
}

const NODE_TYPE_LABELS: Record<string, { ko: string; en: string; color: string }> = {
  field: { ko: "필드", en: "Field", color: "bg-blue-500" },
  value: { ko: "값", en: "Value", color: "bg-emerald-500" },
  material: { ko: "소재", en: "Material", color: "bg-amber-500" },
  operation: { ko: "가공", en: "Operation", color: "bg-purple-500" },
}

interface KGNode {
  id: string
  type: "field" | "value" | "material" | "operation"
  label: string
  labelKo: string
  detail?: string
  detailKo?: string
  aliases?: string[]
  connections: string[]
  productCount?: number
  autoGenerated?: boolean
}

interface KGData {
  nodes: KGNode[]
  source: string
  stats: {
    subtypes: number
    coatings: number
    materials: number
    fluteCounts: number
    operations: number
    coatingMaterialLinks: number
    subtypeMaterialLinks: number
  }
  syncedAt: string
}

interface QAItem {
  question: string
  answer: string
  series?: string
  brand?: string
  category: string
  feature_key?: string
  feature_value?: string
  matched_count?: number
}

interface TermItem {
  en: string
  ko: string
}

function useDebounce(value: string, delay: number) {
  const [debounced, setDebounced] = useState(value)
  useEffect(() => {
    const t = setTimeout(() => setDebounced(value), delay)
    return () => clearTimeout(t)
  }, [value, delay])
  return debounced
}

// ── Knowledge Graph Tab ──

function KnowledgeGraphTab({ language }: { language: string }) {
  const [kgData, setKgData] = useState<KGData | null>(null)
  const [loading, setLoading] = useState(true)
  const [selectedNode, setSelectedNode] = useState<KGNode | null>(null)
  const [filterType, setFilterType] = useState<string>("all")
  const [search, setSearch] = useState("")

  useEffect(() => {
    fetch("/api/knowledge-graph")
      .then(r => r.json())
      .then(d => { setKgData(d); setLoading(false) })
      .catch(() => setLoading(false))
  }, [])

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    )
  }

  if (!kgData || !kgData.nodes) {
    return <p className="text-center text-muted-foreground py-8">Knowledge Graph 데이터를 불러올 수 없습니다.</p>
  }

  const nodes = kgData.nodes
  const byType = (t: string) => nodes.filter(n => n.type === t)
  const totalAliases = nodes.reduce((s, n) => s + (n.aliases?.length ?? 0), 0)

  const filtered = nodes.filter(n => {
    if (filterType !== "all" && n.type !== filterType) return false
    if (search) {
      const q = search.toLowerCase()
      return n.label.toLowerCase().includes(q) ||
        n.labelKo.includes(q) ||
        n.aliases?.some(a => a.toLowerCase().includes(q))
    }
    return true
  })

  const connectedNodes = selectedNode
    ? nodes.filter(n => selectedNode.connections.includes(n.id))
    : []

  return (
    <div className="p-6 space-y-6">
      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
        {[
          { label: language === "ko" ? "필드 노드" : "Field Nodes", value: byType("field").length, icon: Layers, color: "text-blue-500" },
          { label: language === "ko" ? "값 노드" : "Value Nodes", value: byType("value").length, icon: Database, color: "text-emerald-500" },
          { label: language === "ko" ? "소재 노드" : "Material Nodes", value: byType("material").length, icon: GitBranch, color: "text-amber-500" },
          { label: language === "ko" ? "가공 노드" : "Operation Nodes", value: byType("operation").length, icon: Network, color: "text-purple-500" },
          { label: language === "ko" ? "총 별칭" : "Total Aliases", value: totalAliases, icon: Tag, color: "text-rose-500" },
        ].map((s, i) => (
          <Card key={i}>
            <CardContent className="p-4 flex items-center gap-3">
              <s.icon className={`h-8 w-8 ${s.color}`} />
              <div>
                <p className="text-2xl font-bold">{s.value}</p>
                <p className="text-xs text-muted-foreground">{s.label}</p>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* DB Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: language === "ko" ? "공구 형상" : "Subtypes", value: kgData.stats.subtypes },
          { label: language === "ko" ? "코팅" : "Coatings", value: kgData.stats.coatings },
          { label: language === "ko" ? "ISO 소재" : "Materials", value: kgData.stats.materials },
          { label: language === "ko" ? "가공 타입" : "Operations", value: kgData.stats.operations },
        ].map((s, i) => (
          <div key={i} className="bg-muted rounded-lg px-4 py-3 text-center">
            <p className="text-lg font-semibold">{s.value}</p>
            <p className="text-xs text-muted-foreground">{s.label}</p>
          </div>
        ))}
      </div>

      <div className="text-xs text-muted-foreground">
        {language === "ko" ? "데이터 소스" : "Source"}: {kgData.source} | {language === "ko" ? "동기화" : "Synced"}: {new Date(kgData.syncedAt).toLocaleString()}
      </div>

      {/* Entity Explorer */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-lg">
            <Network className="h-5 w-5" />
            {language === "ko" ? "엔티티 그래프 탐색기" : "Entity Graph Explorer"}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Filters */}
          <div className="flex gap-3">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder={language === "ko" ? "노드 검색 (이름, 별칭)..." : "Search nodes..."}
                className="pl-10"
                value={search}
                onChange={e => setSearch(e.target.value)}
              />
            </div>
            <div className="flex gap-1">
              <Button
                variant={filterType === "all" ? "default" : "outline"}
                size="sm"
                onClick={() => setFilterType("all")}
              >
                {language === "ko" ? "전체" : "All"} ({nodes.length})
              </Button>
              {Object.entries(NODE_TYPE_LABELS).map(([type, meta]) => (
                <Button
                  key={type}
                  variant={filterType === type ? "default" : "outline"}
                  size="sm"
                  onClick={() => setFilterType(type)}
                >
                  {language === "ko" ? meta.ko : meta.en} ({byType(type).length})
                </Button>
              ))}
            </div>
          </div>

          {/* Node Grid + Detail */}
          <div className="flex gap-4">
            {/* Node List */}
            <div className="flex-1 grid grid-cols-2 md:grid-cols-3 gap-2 max-h-[500px] overflow-y-auto content-start">
              {filtered.map(node => {
                const meta = NODE_TYPE_LABELS[node.type]
                return (
                  <div
                    key={node.id}
                    className={`p-3 rounded-lg border cursor-pointer transition-all hover:shadow-md ${
                      selectedNode?.id === node.id ? "ring-2 ring-primary bg-primary/5" : "hover:bg-muted/50"
                    }`}
                    onClick={() => setSelectedNode(node)}
                  >
                    <div className="flex items-center gap-2 mb-1">
                      <span className={`w-2 h-2 rounded-full ${meta.color}`} />
                      <span className="font-medium text-sm truncate">
                        {language === "ko" ? node.labelKo : node.label}
                      </span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge variant="outline" className="text-[10px]">
                        {language === "ko" ? meta.ko : meta.en}
                      </Badge>
                      {node.productCount != null && node.productCount > 0 && (
                        <span className="text-[10px] text-muted-foreground">{node.productCount.toLocaleString()}개</span>
                      )}
                    </div>
                  </div>
                )
              })}
            </div>

            {/* Detail Panel */}
            <div className="w-80 shrink-0">
              {selectedNode ? (
                <Card>
                  <CardContent className="p-4 space-y-3">
                    <div className="flex items-center gap-2">
                      <span className={`w-3 h-3 rounded-full ${NODE_TYPE_LABELS[selectedNode.type].color}`} />
                      <h3 className="font-bold text-lg">
                        {language === "ko" ? selectedNode.labelKo : selectedNode.label}
                      </h3>
                    </div>
                    <p className="text-sm text-muted-foreground">
                      {language === "ko" ? selectedNode.label : selectedNode.labelKo}
                    </p>
                    {(language === "ko" ? selectedNode.detailKo : selectedNode.detail) && (
                      <p className="text-sm bg-muted p-2 rounded">{language === "ko" ? selectedNode.detailKo : selectedNode.detail}</p>
                    )}
                    {selectedNode.productCount != null && (
                      <div className="text-sm">
                        <span className="text-muted-foreground">{language === "ko" ? "제품 수" : "Products"}:</span>{" "}
                        <span className="font-semibold">{selectedNode.productCount.toLocaleString()}</span>
                      </div>
                    )}
                    {selectedNode.aliases && selectedNode.aliases.length > 0 && (
                      <div>
                        <p className="text-xs text-muted-foreground mb-1">{language === "ko" ? "별칭" : "Aliases"} ({selectedNode.aliases.length})</p>
                        <div className="flex flex-wrap gap-1">
                          {selectedNode.aliases.map((a, i) => (
                            <Badge key={i} variant="secondary" className="text-[10px]">{a}</Badge>
                          ))}
                        </div>
                      </div>
                    )}
                    {connectedNodes.length > 0 && (
                      <div>
                        <p className="text-xs text-muted-foreground mb-1">{language === "ko" ? "연결" : "Connections"} ({connectedNodes.length})</p>
                        <div className="flex flex-wrap gap-1">
                          {connectedNodes.map(cn => (
                            <Badge
                              key={cn.id}
                              variant="outline"
                              className="text-[10px] cursor-pointer hover:bg-muted"
                              onClick={() => setSelectedNode(cn)}
                            >
                              {language === "ko" ? cn.labelKo : cn.label}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              ) : (
                <div className="flex items-center justify-center h-48 text-muted-foreground border rounded-lg">
                  <div className="text-center">
                    <Network className="h-10 w-10 mx-auto mb-2 opacity-30" />
                    <p className="text-sm">{language === "ko" ? "노드를 선택하세요" : "Select a node"}</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// ── Main Page ──

export default function KnowledgePage() {
  const { language } = useApp()
  const [activeTab, setActiveTab] = useState("graph")

  // QA state
  const [qaSearch, setQaSearch] = useState("")
  const [qaCategory, setQaCategory] = useState("")
  const [qaItems, setQaItems] = useState<QAItem[]>([])
  const [qaTotal, setQaTotal] = useState(0)
  const [qaCategories, setQaCategories] = useState<Record<string, number>>({})
  const [qaPage, setQaPage] = useState(1)
  const [qaLoading, setQaLoading] = useState(false)
  const [qaSelected, setQaSelected] = useState<QAItem | null>(null)

  // Feature state
  const [featSearch, setFeatSearch] = useState("")
  const [featKey, setFeatKey] = useState("")
  const [featItems, setFeatItems] = useState<QAItem[]>([])
  const [featTotal, setFeatTotal] = useState(0)
  const [featKeys, setFeatKeys] = useState<Record<string, number>>({})
  const [featPage, setFeatPage] = useState(1)
  const [featLoading, setFeatLoading] = useState(false)

  // Terminology state
  const [termSearch, setTermSearch] = useState("")
  const [terms, setTerms] = useState<TermItem[]>([])
  const [termLoading, setTermLoading] = useState(false)

  const debouncedQa = useDebounce(qaSearch, 300)
  const debouncedFeat = useDebounce(featSearch, 300)
  const debouncedTerm = useDebounce(termSearch, 300)

  const LIMIT = 20

  const fetchQA = useCallback(async () => {
    setQaLoading(true)
    try {
      const params = new URLSearchParams({ tab: "qa", page: String(qaPage), limit: String(LIMIT) })
      if (debouncedQa) params.set("q", debouncedQa)
      if (qaCategory) params.set("category", qaCategory)
      const res = await fetch(`/api/knowledge?${params}`)
      const data = await res.json()
      setQaItems(data.items || [])
      setQaTotal(data.total || 0)
      if (data.categories) setQaCategories(data.categories)
    } catch { /* ignore */ }
    setQaLoading(false)
  }, [debouncedQa, qaCategory, qaPage])

  const fetchFeature = useCallback(async () => {
    setFeatLoading(true)
    try {
      const params = new URLSearchParams({ tab: "feature", page: String(featPage), limit: String(LIMIT) })
      if (debouncedFeat) params.set("q", debouncedFeat)
      if (featKey) params.set("category", featKey)
      const res = await fetch(`/api/knowledge?${params}`)
      const data = await res.json()
      setFeatItems(data.items || [])
      setFeatTotal(data.total || 0)
      if (data.featureKeys) setFeatKeys(data.featureKeys)
    } catch { /* ignore */ }
    setFeatLoading(false)
  }, [debouncedFeat, featKey, featPage])

  const fetchTerminology = useCallback(async () => {
    setTermLoading(true)
    try {
      const params = new URLSearchParams({ tab: "terminology" })
      if (debouncedTerm) params.set("q", debouncedTerm)
      const res = await fetch(`/api/knowledge?${params}`)
      const data = await res.json()
      setTerms(data.items || [])
    } catch { /* ignore */ }
    setTermLoading(false)
  }, [debouncedTerm])

  useEffect(() => { fetchQA() }, [fetchQA])
  useEffect(() => { fetchFeature() }, [fetchFeature])
  useEffect(() => { fetchTerminology() }, [fetchTerminology])

  useEffect(() => { setQaPage(1) }, [debouncedQa, qaCategory])
  useEffect(() => { setFeatPage(1) }, [debouncedFeat, featKey])

  const qaMaxPage = Math.max(1, Math.ceil(qaTotal / LIMIT))
  const featMaxPage = Math.max(1, Math.ceil(featTotal / LIMIT))

  return (
    <div className="flex h-full flex-col">
      {/* Header */}
      <div className="border-b bg-card p-6">
        <div className="flex items-center justify-between mb-2">
          <div>
            <h1 className="text-2xl font-bold flex items-center gap-2">
              <BookOpen className="h-6 w-6 text-primary" />
              {language === "ko" ? "지식 베이스" : "Knowledge Base"}
            </h1>
            <p className="text-muted-foreground mt-1">
              {language === "ko"
                ? "Knowledge Graph / 제품 QA / 조건별 추천 / 용어 사전"
                : "Knowledge Graph / Product QA / Recommendations / Terminology"}
            </p>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex-1 overflow-hidden">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="h-full flex flex-col">
          <div className="border-b px-6">
            <TabsList className="h-12">
              <TabsTrigger value="graph" className="gap-2">
                <Network className="h-4 w-4" />
                Knowledge Graph
              </TabsTrigger>
              <TabsTrigger value="qa" className="gap-2">
                <MessageSquare className="h-4 w-4" />
                {language === "ko" ? "제품 QA" : "Product QA"}
                {qaTotal > 0 && <Badge variant="secondary" className="ml-1">{qaTotal.toLocaleString()}</Badge>}
              </TabsTrigger>
              <TabsTrigger value="feature" className="gap-2">
                <Lightbulb className="h-4 w-4" />
                {language === "ko" ? "조건별 추천" : "Recommendations"}
                {featTotal > 0 && <Badge variant="secondary" className="ml-1">{featTotal.toLocaleString()}</Badge>}
              </TabsTrigger>
              <TabsTrigger value="terminology" className="gap-2">
                <Languages className="h-4 w-4" />
                {language === "ko" ? "용어 사전" : "Terminology"}
                {terms.length > 0 && <Badge variant="secondary" className="ml-1">{terms.length}</Badge>}
              </TabsTrigger>
            </TabsList>
          </div>

          {/* ─── Knowledge Graph Tab ─── */}
          <TabsContent value="graph" className="flex-1 overflow-y-auto m-0">
            <KnowledgeGraphTab language={language} />
          </TabsContent>

          {/* ─── QA Tab ─── */}
          <TabsContent value="qa" className="flex-1 overflow-hidden m-0">
            <div className="flex h-full">
              <div className="w-1/2 border-r flex flex-col">
                <div className="p-4 border-b space-y-2">
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                    <Input
                      placeholder={language === "ko" ? "시리즈명, 브랜드, 키워드 검색..." : "Search series, brand, keyword..."}
                      className="pl-10"
                      value={qaSearch}
                      onChange={e => setQaSearch(e.target.value)}
                    />
                  </div>
                  <Select value={qaCategory} onValueChange={setQaCategory}>
                    <SelectTrigger className="w-full">
                      <Filter className="h-4 w-4 mr-2" />
                      <SelectValue placeholder={language === "ko" ? "전체 카테고리" : "All categories"} />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="">{language === "ko" ? "전체" : "All"}</SelectItem>
                      {Object.entries(qaCategories).map(([key, count]) => (
                        <SelectItem key={key} value={key}>
                          {CATEGORY_LABELS[key] || key} ({count.toLocaleString()})
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="flex-1 overflow-y-auto p-4 space-y-2">
                  {qaLoading ? (
                    <div className="flex items-center justify-center h-32">
                      <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
                    </div>
                  ) : qaItems.length === 0 ? (
                    <p className="text-center text-muted-foreground py-8">
                      {language === "ko" ? "결과 없음" : "No results"}
                    </p>
                  ) : (
                    qaItems.map((item, i) => (
                      <Card
                        key={`${item.series}-${item.category}-${i}`}
                        className={`cursor-pointer transition-colors hover:bg-muted/50 ${
                          qaSelected === item ? "ring-2 ring-primary" : ""
                        }`}
                        onClick={() => setQaSelected(item)}
                      >
                        <CardContent className="p-3">
                          <p className="font-medium text-sm line-clamp-2">{item.question}</p>
                          <div className="flex items-center gap-2 mt-2">
                            {item.brand && <Badge variant="outline" className="text-xs">{item.brand}</Badge>}
                            {item.series && <Badge variant="secondary" className="text-xs">{item.series}</Badge>}
                            <Badge className="text-xs">{CATEGORY_LABELS[item.category] || item.category}</Badge>
                          </div>
                        </CardContent>
                      </Card>
                    ))
                  )}
                </div>

                <div className="p-3 border-t flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">
                    {qaTotal.toLocaleString()}건 중 {((qaPage - 1) * LIMIT) + 1}-{Math.min(qaPage * LIMIT, qaTotal)}
                  </span>
                  <div className="flex gap-1">
                    <Button variant="outline" size="sm" disabled={qaPage <= 1} onClick={() => setQaPage(p => p - 1)}>
                      <ChevronLeft className="h-4 w-4" />
                    </Button>
                    <span className="px-2 py-1">{qaPage}/{qaMaxPage}</span>
                    <Button variant="outline" size="sm" disabled={qaPage >= qaMaxPage} onClick={() => setQaPage(p => p + 1)}>
                      <ChevronRight className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </div>

              <div className="w-1/2 overflow-y-auto">
                {qaSelected ? (
                  <div className="p-6">
                    <div className="flex items-center gap-2 mb-3">
                      {qaSelected.brand && <Badge>{qaSelected.brand}</Badge>}
                      {qaSelected.series && <Badge variant="outline">{qaSelected.series}</Badge>}
                      <Badge variant="secondary">{CATEGORY_LABELS[qaSelected.category] || qaSelected.category}</Badge>
                    </div>
                    <h2 className="text-lg font-bold mb-4">{qaSelected.question}</h2>
                    <div className="bg-muted p-4 rounded-lg">
                      <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed">{qaSelected.answer}</pre>
                    </div>
                  </div>
                ) : (
                  <div className="flex items-center justify-center h-full text-muted-foreground">
                    <div className="text-center">
                      <FileText className="h-12 w-12 mx-auto mb-3 opacity-30" />
                      <p>{language === "ko" ? "QA를 선택하세요" : "Select a QA item"}</p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </TabsContent>

          {/* ─── Feature Recommendations Tab ─── */}
          <TabsContent value="feature" className="flex-1 overflow-y-auto m-0 p-6">
            <div className="max-w-4xl mx-auto space-y-4">
              <div className="flex gap-4">
                <div className="relative flex-1">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                  <Input
                    placeholder={language === "ko" ? "소재, 형상, 코팅 등 검색..." : "Search material, shape, coating..."}
                    className="pl-10"
                    value={featSearch}
                    onChange={e => setFeatSearch(e.target.value)}
                  />
                </div>
                <Select value={featKey} onValueChange={setFeatKey}>
                  <SelectTrigger className="w-48">
                    <Tag className="h-4 w-4 mr-2" />
                    <SelectValue placeholder={language === "ko" ? "전체 분류" : "All types"} />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="">{language === "ko" ? "전체" : "All"}</SelectItem>
                    {Object.entries(featKeys).map(([key, count]) => (
                      <SelectItem key={key} value={key}>
                        {FEATURE_KEY_LABELS[key] || key} ({count})
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {featLoading ? (
                <div className="flex justify-center py-8">
                  <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
                </div>
              ) : (
                <div className="space-y-3">
                  {featItems.map((item, i) => (
                    <Card key={`${item.feature_key}-${item.feature_value}-${i}`}>
                      <CardHeader className="pb-2">
                        <div className="flex items-start justify-between">
                          <CardTitle className="text-base">{item.question}</CardTitle>
                          <div className="flex gap-1 shrink-0">
                            <Badge variant="outline">
                              {FEATURE_KEY_LABELS[item.feature_key || ""] || item.feature_key}
                            </Badge>
                            {item.matched_count && (
                              <Badge variant="secondary">
                                <Hash className="h-3 w-3 mr-1" />
                                {item.matched_count}
                              </Badge>
                            )}
                          </div>
                        </div>
                      </CardHeader>
                      <CardContent>
                        <pre className="whitespace-pre-wrap font-sans text-sm text-muted-foreground bg-muted p-3 rounded-lg max-h-48 overflow-y-auto">
                          {item.answer}
                        </pre>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              )}

              <div className="flex items-center justify-between text-sm pt-2">
                <span className="text-muted-foreground">{featTotal}건</span>
                <div className="flex gap-1">
                  <Button variant="outline" size="sm" disabled={featPage <= 1} onClick={() => setFeatPage(p => p - 1)}>
                    <ChevronLeft className="h-4 w-4" />
                  </Button>
                  <span className="px-2 py-1">{featPage}/{featMaxPage}</span>
                  <Button variant="outline" size="sm" disabled={featPage >= featMaxPage} onClick={() => setFeatPage(p => p + 1)}>
                    <ChevronRight className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            </div>
          </TabsContent>

          {/* ─── Terminology Tab ─── */}
          <TabsContent value="terminology" className="flex-1 overflow-y-auto m-0 p-6">
            <div className="max-w-3xl mx-auto space-y-4">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder={language === "ko" ? "영문 또는 한글로 검색..." : "Search in English or Korean..."}
                  className="pl-10"
                  value={termSearch}
                  onChange={e => setTermSearch(e.target.value)}
                />
              </div>

              {termLoading ? (
                <div className="flex justify-center py-8">
                  <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
                </div>
              ) : (
                <div className="border rounded-lg overflow-hidden">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b bg-muted/50">
                        <th className="text-left py-3 px-4 font-medium w-1/2">English</th>
                        <th className="text-left py-3 px-4 font-medium w-1/2">
                          {language === "ko" ? "한국어" : "Korean"}
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {terms.map((t, i) => (
                        <tr key={i} className="border-b last:border-b-0 hover:bg-muted/30">
                          <td className="py-2 px-4 font-mono">{t.en}</td>
                          <td className="py-2 px-4">{t.ko}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}
