DROP MATERIALIZED VIEW catalog_app.product_recommendation_mv;
CREATE MATERIALIZED VIEW catalog_app.product_recommendation_mv AS
 WITH ranked_edp AS (
         SELECT pe_1._row_num,
            pe_1.idx,
            pe_1.root_category,
            pe_1.category_idx,
            pe_1.brand_idx,
            pe_1.brand_name,
            pe_1.series_idx,
            pe_1.series_name,
            pe_1.edp_no,
            pe_1.your_code,
            pe_1.file1,
            pe_1.file2,
            pe_1.file3,
            pe_1.dxf,
            pe_1.dxf_name,
            pe_1.stp,
            pe_1.stp_name,
            pe_1.unit,
            pe_1.option_od,
            pe_1.option_r,
            pe_1.option_sd,
            pe_1.option_loc,
            pe_1.option_oal,
            pe_1.option_flute,
            pe_1.option_z,
            pe_1.option_dc,
            pe_1.option_dcx,
            pe_1.option_lf,
            pe_1.option_dcon,
            pe_1.option_cbdp,
            pe_1.option_dcsfms,
            pe_1.option_apmx,
            pe_1.option_drill_diameter,
            pe_1.option_shank_diameter,
            pe_1.option_flute_length,
            pe_1.option_overall_length,
            pe_1.option_length,
            pe_1.option_depth_of_hole,
            pe_1.option_d1,
            pe_1.option_size,
            pe_1.option_pitch,
            pe_1.option_tpi,
            pe_1.option_designation,
            pe_1.option_re,
            pe_1.option_l,
            pe_1.option_ic,
            pe_1.option_s,
            pe_1.option_lbs,
            pe_1.option_chip_breaker,
            pe_1.option_model_no,
            pe_1.option_grade,
            pe_1.option_d,
            pe_1.option_clamping_range,
            pe_1.option_nut_collet,
            pe_1.option_taper_no,
            pe_1.flag_del,
            pe_1.flag_save,
            pe_1.flag_show,
            pe_1.reg_id,
            pe_1.reg_dtm,
            pe_1.modi_id,
            pe_1.modi_dtm,
            pe_1.option_thread_shape,
            pe_1.option_pitch_tpi,
            pe_1.option_thread_tolerance_class,
            pe_1.option_chamfer_length,
            pe_1.option_coolant,
            pe_1.option_hand,
            pe_1.option_dmin,
            pe_1.option_h,
            pe_1.option_b,
            pe_1.option_wf,
            pe_1.option_insert,
            pe_1.option_cw,
            pe_1.option_cdx,
            pe_1.option_series,
            pe_1.option_series_description,
            pe_1.option_series_filter,
            pe_1.option_chip_breaker_description,
            pe_1.option_loc_1,
            pe_1.option_lbs_1,
            pe_1.option_tolofmilldia,
            pe_1.option_tolofshankdia,
            pe_1.option_taperangle,
            pe_1.option_coolanthole,
            pe_1.option_threadlength,
            pe_1.option_shankdia,
            pe_1.option_squaresize,
            pe_1.option_numberofflute,
            pe_1.option_connection_type,
            row_number() OVER (PARTITION BY pe_1.edp_no ORDER BY pe_1.idx DESC) AS edp_rank
           FROM raw_catalog.prod_edp pe_1
          WHERE COALESCE(pe_1.flag_del, 'N'::text) <> 'Y'::text AND COALESCE(pe_1.flag_show, 'Y'::text) = 'Y'::text AND NULLIF(pe_1.edp_no, ''::text) IS NOT NULL
        ), dedup_edp AS (
         SELECT ranked_edp._row_num,
            ranked_edp.idx,
            ranked_edp.root_category,
            ranked_edp.category_idx,
            ranked_edp.brand_idx,
            ranked_edp.brand_name,
            ranked_edp.series_idx,
            ranked_edp.series_name,
            ranked_edp.edp_no,
            ranked_edp.your_code,
            ranked_edp.file1,
            ranked_edp.file2,
            ranked_edp.file3,
            ranked_edp.dxf,
            ranked_edp.dxf_name,
            ranked_edp.stp,
            ranked_edp.stp_name,
            ranked_edp.unit,
            ranked_edp.option_od,
            ranked_edp.option_r,
            ranked_edp.option_sd,
            ranked_edp.option_loc,
            ranked_edp.option_oal,
            ranked_edp.option_flute,
            ranked_edp.option_z,
            ranked_edp.option_dc,
            ranked_edp.option_dcx,
            ranked_edp.option_lf,
            ranked_edp.option_dcon,
            ranked_edp.option_cbdp,
            ranked_edp.option_dcsfms,
            ranked_edp.option_apmx,
            ranked_edp.option_drill_diameter,
            ranked_edp.option_shank_diameter,
            ranked_edp.option_flute_length,
            ranked_edp.option_overall_length,
            ranked_edp.option_length,
            ranked_edp.option_depth_of_hole,
            ranked_edp.option_d1,
            ranked_edp.option_size,
            ranked_edp.option_pitch,
            ranked_edp.option_tpi,
            ranked_edp.option_designation,
            ranked_edp.option_re,
            ranked_edp.option_l,
            ranked_edp.option_ic,
            ranked_edp.option_s,
            ranked_edp.option_lbs,
            ranked_edp.option_chip_breaker,
            ranked_edp.option_model_no,
            ranked_edp.option_grade,
            ranked_edp.option_d,
            ranked_edp.option_clamping_range,
            ranked_edp.option_nut_collet,
            ranked_edp.option_taper_no,
            ranked_edp.flag_del,
            ranked_edp.flag_save,
            ranked_edp.flag_show,
            ranked_edp.reg_id,
            ranked_edp.reg_dtm,
            ranked_edp.modi_id,
            ranked_edp.modi_dtm,
            ranked_edp.option_thread_shape,
            ranked_edp.option_pitch_tpi,
            ranked_edp.option_thread_tolerance_class,
            ranked_edp.option_chamfer_length,
            ranked_edp.option_coolant,
            ranked_edp.option_hand,
            ranked_edp.option_dmin,
            ranked_edp.option_h,
            ranked_edp.option_b,
            ranked_edp.option_wf,
            ranked_edp.option_insert,
            ranked_edp.option_cw,
            ranked_edp.option_cdx,
            ranked_edp.option_series,
            ranked_edp.option_series_description,
            ranked_edp.option_series_filter,
            ranked_edp.option_chip_breaker_description,
            ranked_edp.option_loc_1,
            ranked_edp.option_lbs_1,
            ranked_edp.option_tolofmilldia,
            ranked_edp.option_tolofshankdia,
            ranked_edp.option_taperangle,
            ranked_edp.option_coolanthole,
            ranked_edp.option_threadlength,
            ranked_edp.option_shankdia,
            ranked_edp.option_squaresize,
            ranked_edp.option_numberofflute,
            ranked_edp.option_connection_type,
            ranked_edp.edp_rank
           FROM ranked_edp
          WHERE ranked_edp.edp_rank = 1
        ), series_materials AS (
         SELECT prod_series_work_material_status.prod_series_idx,
            array_remove(array_agg(DISTINCT NULLIF(prod_series_work_material_status.tag_name, ''::text)), NULL::text) AS material_tags
           FROM raw_catalog.prod_series_work_material_status
          GROUP BY prod_series_work_material_status.prod_series_idx
        ), country_sources AS (
         SELECT raw_country_codes.edp_no,
            btrim(raw_country_codes.country_code) AS country_code
           FROM ( SELECT pm_1.edp_no,
                    country_row.country_code
                   FROM raw_catalog.prod_edp_option_milling pm_1,
                    LATERAL unnest(string_to_array(COALESCE(pm_1.country, ''::text), ','::text)) country_row(country_code)
                UNION ALL
                 SELECT ph_1.edp_no,
                    country_row.country_code
                   FROM raw_catalog.prod_edp_option_holemaking ph_1,
                    LATERAL unnest(string_to_array(COALESCE(ph_1.country, ''::text), ','::text)) country_row(country_code)
                UNION ALL
                 SELECT pt_1.edp_no,
                    country_row.country_code
                   FROM raw_catalog.prod_edp_option_threading pt_1,
                    LATERAL unnest(string_to_array(COALESCE(pt_1.country, ''::text), ','::text)) country_row(country_code)
                UNION ALL
                 SELECT ptool_1.edp_no,
                    country_row.country_code
                   FROM raw_catalog.prod_edp_option_tooling ptool_1,
                    LATERAL unnest(string_to_array(COALESCE(ptool_1.country, ''::text), ','::text)) country_row(country_code)
                UNION ALL
                 SELECT pturn.edp_no,
                    country_row.country_code
                   FROM raw_catalog.prod_edp_option_turning pturn,
                    LATERAL unnest(string_to_array(COALESCE(pturn.country, ''::text), ','::text)) country_row(country_code)) raw_country_codes
          WHERE btrim(raw_country_codes.country_code) <> ''::text
        ), edp_countries AS (
         SELECT country_sources.edp_no,
            string_agg(DISTINCT country_sources.country_code, ','::text ORDER BY country_sources.country_code) AS country,
            array_agg(DISTINCT country_sources.country_code ORDER BY country_sources.country_code) AS country_codes
           FROM country_sources
          GROUP BY country_sources.edp_no
        )
 SELECT pe.idx AS edp_idx,
    pe.edp_no,
    pe.brand_name AS edp_brand_name,
    pe.series_name AS edp_series_name,
    pe.series_idx AS edp_series_idx,
    pe.root_category AS edp_root_category,
    pe.unit AS edp_unit,
    pe.option_z,
    pe.option_numberofflute,
    pe.option_drill_diameter,
    pe.option_d1,
    pe.option_dc,
    pe.option_d,
    pe.option_shank_diameter,
    pe.option_dcon,
    pe.option_flute_length,
    pe.option_loc,
    pe.option_overall_length,
    pe.option_oal,
    pe.option_r,
    pe.option_re,
    pe.option_tolofmilldia,
    pe.option_tolofshankdia,
    pe.option_taperangle,
    pe.option_coolanthole,
    ps.idx AS series_row_idx,
    ps.brand_name AS series_brand_name,
    ps.description AS series_description,
    ps.feature AS series_feature,
    ps.tool_type AS series_tool_type,
    ps.product_type AS series_product_type,
    ps.application_shape AS series_application_shape,
    ps.cutting_edge_shape AS series_cutting_edge_shape,
    ps.shank_type AS series_shank_type,
    country_source.country,
    COALESCE(country_source.country_codes, ARRAY[]::text[]) AS country_codes,
    sm.material_tags,
    pm.option_milling_outsidedia AS milling_outside_dia,
    pm.option_milling_numberofflute AS milling_number_of_flute,
    pm.option_milling_coating AS milling_coating,
    pm.option_milling_toolmaterial AS milling_tool_material,
    pm.option_milling_shankdia AS milling_shank_dia,
    pm.option_milling_shanktype AS milling_shank_type,
    pm.option_milling_lengthofcut AS milling_length_of_cut,
    pm.option_milling_overalllength AS milling_overall_length,
    pm.option_milling_helixangle AS milling_helix_angle,
    pm.option_milling_radiusofballnose AS milling_ball_radius,
    pm.option_milling_tolofmilldia AS milling_diameter_tolerance,
    pm.option_milling_tolofshankdia AS milling_shank_diameter_tolerance,
    pm.option_milling_taperangle AS milling_taper_angle,
    pm.option_milling_neckdiameter AS milling_neck_diameter,
    pm.option_milling_effective_length AS milling_effective_length,
    pm.option_milling_coolanthole AS milling_coolant_hole,
    pm.option_milling_cuttingedgeshape AS milling_cutting_edge_shape,
    pm.option_milling_cuttershape AS milling_cutter_shape,
    ph.option_holemaking_outsidedia AS holemaking_outside_dia,
    ph.option_holemaking_numberofflute AS holemaking_number_of_flute,
    ph.option_holemaking_coating AS holemaking_coating,
    ph.option_holemaking_toolmaterial AS holemaking_tool_material,
    ph.option_holemaking_shankdia AS holemaking_shank_dia,
    ph.option_holemaking_flutelength AS holemaking_flute_length,
    ph.option_holemaking_overalllength AS holemaking_overall_length,
    ph.option_holemaking_helixangle AS holemaking_helix_angle,
    ph.option_holemaking_tolofdrilldia AS holemaking_diameter_tolerance,
    ph.option_holemaking_tolofshankdia AS holemaking_shank_diameter_tolerance,
    ph.option_holemaking_length_below_shank AS holemaking_length_below_shank,
    ph.option_holemaking_taper_angle AS holemaking_taper_angle,
    ph.option_holemaking_coolanthole AS holemaking_coolant_hole,
    pt.option_threading_outsidedia AS threading_outside_dia,
    pt.option_threading_numberofflute AS threading_number_of_flute,
    pt.option_threading_coating AS threading_coating,
    pt.option_threading_toolmaterial AS threading_tool_material,
    pt.option_threading_shankdia AS threading_shank_dia,
    pt.option_threading_threadlength AS threading_thread_length,
    pt.option_threading_overalllength AS threading_overall_length,
    pt.option_threading_l3 AS threading_l3,
    pt.option_threading_coolanthole AS threading_coolant_hole,
    pt.option_threading_flutetype AS threading_flute_type,
    pt.option_threading_threadshape AS threading_thread_shape,
    ptool.option_tooling_shanktype AS tooling_shank_type,
    ptool.option_tooling_back_bore_l3 AS tooling_back_bore_l3,
    replace(replace(upper(pe.edp_no), ' '::text, ''::text), '-'::text, ''::text) AS normalized_code,
        CASE
            WHEN upper(COALESCE(pe.unit, ''::text)) ~~ '%INCH%'::text THEN NULLIF("substring"(COALESCE(NULLIF(pm.option_milling_outsidedia, ''::text), NULLIF(ph.option_holemaking_outsidedia, ''::text), NULLIF(pt.option_threading_outsidedia, ''::text), NULLIF(pe.option_drill_diameter, ''::text), NULLIF(pe.option_d1, ''::text), NULLIF(pe.option_dc, ''::text), NULLIF(pe.option_d, ''::text)), '(-?[0-9]+(?:\.[0-9]+)?)'::text), ''::text)::numeric * 25.4
            ELSE NULLIF("substring"(COALESCE(NULLIF(pm.option_milling_outsidedia, ''::text), NULLIF(ph.option_holemaking_outsidedia, ''::text), NULLIF(pt.option_threading_outsidedia, ''::text), NULLIF(pe.option_drill_diameter, ''::text), NULLIF(pe.option_d1, ''::text), NULLIF(pe.option_dc, ''::text), NULLIF(pe.option_d, ''::text)), '(-?[0-9]+(?:\.[0-9]+)?)'::text), ''::text)::numeric
        END AS search_diameter_mm,
    COALESCE(NULLIF(pm.option_milling_coating, ''::text), NULLIF(ph.option_holemaking_coating, ''::text), NULLIF(pt.option_threading_coating, ''::text)) AS search_coating,
    COALESCE(NULLIF(pm.option_milling_cuttingedgeshape, ''::text), NULLIF(ps.cutting_edge_shape, ''::text), NULLIF(pm.option_milling_cuttershape, ''::text), NULLIF(pt.option_threading_flutetype, ''::text), NULLIF(pt.option_threading_threadshape, ''::text)) AS search_subtype,
    COALESCE(NULLIF(pm.option_milling_shanktype, ''::text), NULLIF(ptool.option_tooling_shanktype, ''::text), NULLIF(ps.shank_type, ''::text)) AS search_shank_type,
    ph.option_holemaking_pointangle AS holemaking_point_angle,
    pt.option_threading_pitch AS threading_pitch,
    pt.option_threading_tpi AS threading_tpi
   FROM dedup_edp pe
     LEFT JOIN raw_catalog.prod_series ps ON ps.idx = pe.series_idx
     LEFT JOIN series_materials sm ON sm.prod_series_idx = pe.series_idx
     LEFT JOIN edp_countries country_source ON country_source.edp_no = pe.edp_no
     LEFT JOIN raw_catalog.prod_edp_option_milling pm ON pm.edp_no = pe.edp_no
     LEFT JOIN raw_catalog.prod_edp_option_holemaking ph ON ph.edp_no = pe.edp_no
     LEFT JOIN raw_catalog.prod_edp_option_threading pt ON pt.edp_no = pe.edp_no
     LEFT JOIN raw_catalog.prod_edp_option_tooling ptool ON ptool.edp_no = pe.edp_no;;
CREATE INDEX product_recommendation_mv_code_idx ON catalog_app.product_recommendation_mv USING btree (normalized_code);
CREATE INDEX product_recommendation_mv_diameter_idx ON catalog_app.product_recommendation_mv USING btree (search_diameter_mm);
CREATE INDEX product_recommendation_mv_material_tags_idx ON catalog_app.product_recommendation_mv USING gin (material_tags);
CREATE INDEX product_recommendation_mv_country_codes_idx ON catalog_app.product_recommendation_mv USING gin (country_codes);
CREATE INDEX product_recommendation_mv_series_trgm_idx ON catalog_app.product_recommendation_mv USING gin (edp_series_name gin_trgm_ops);
CREATE INDEX product_recommendation_mv_coating_trgm_idx ON catalog_app.product_recommendation_mv USING gin (search_coating gin_trgm_ops);
CREATE INDEX product_recommendation_mv_subtype_trgm_idx ON catalog_app.product_recommendation_mv USING gin (search_subtype gin_trgm_ops);
CREATE INDEX product_recommendation_mv_appshape_trgm_idx ON catalog_app.product_recommendation_mv USING gin (series_application_shape gin_trgm_ops);
