/**
 * Knowledge Graph Auto-Sync API
 *
 * Queries the product database for all distinct values across key fields,
 * then builds a dynamic knowledge graph with auto-generated connections.
 * New data in DB → automatically appears in KG.
 */

import { NextResponse } from "next/server"
import { getSharedPool } from "@/lib/data/shared-pool"

interface KGNode {
  id: string
  type: "field" | "value" | "material" | "operation"
  label: string
  labelKo: string
  detail?: string
  detailKo?: string
  aliases?: string[]
  connections: string[]
  productCount?: number
  autoGenerated?: boolean
}

// ── Base field nodes (always present) ────────────────────────
const BASE_FIELD_NODES: KGNode[] = [
  { id: "f-toolSubtype", type: "field", label: "Tool Subtype", labelKo: "공구 형상", connections: [] },
  { id: "f-coating", type: "field", label: "Coating", labelKo: "코팅", connections: [] },
  { id: "f-material", type: "field", label: "Material (ISO)", labelKo: "피삭재 (ISO)", connections: [] },
  { id: "f-fluteCount", type: "field", label: "Flute Count", labelKo: "날 수", connections: [] },
  { id: "f-diameter", type: "field", label: "Diameter", labelKo: "직경 (mm)", connections: [] },
  { id: "f-operation", type: "field", label: "Operation", labelKo: "가공 종류", connections: [] },
]

// ── Known aliases & Korean labels ────────────────────────────
const SUBTYPE_META: Record<string, { ko: string; aliases: string[] }> = {
  "Square": { ko: "스퀘어", aliases: ["스퀘어", "평엔드밀"] },
  "Ball": { ko: "볼", aliases: ["볼", "볼노즈", "볼엔드밀"] },
  "Radius": { ko: "라디우스", aliases: ["라디우스", "코너R", "코너반경"] },
  "Roughing": { ko: "황삭", aliases: ["황삭", "러핑"] },
  "Taper": { ko: "테이퍼", aliases: ["테이퍼"] },
  "Chamfer": { ko: "챔퍼", aliases: ["챔퍼", "모따기", "면취"] },
  "High-Feed": { ko: "하이피드", aliases: ["하이피드", "고이송"] },
  "Corner Radius": { ko: "코너라디우스", aliases: ["코너라디우스"] },
  "Drill Mill": { ko: "드릴밀", aliases: ["드릴밀"] },
}

const COATING_META: Record<string, { ko: string; aliases: string[]; materials: string[] }> = {
  "TiAlN": { ko: "TiAlN", aliases: ["티알엔"], materials: ["P", "M", "K"] },
  "AlTiN": { ko: "AlTiN", aliases: ["알틴"], materials: ["M", "S", "H"] },
  "AlCrN": { ko: "AlCrN", aliases: ["알크롬"], materials: ["H", "S"] },
  "TiCN": { ko: "TiCN", aliases: ["티씨엔"], materials: ["P", "K"] },
  "DLC": { ko: "DLC", aliases: ["디엘씨"], materials: ["N"] },
  "Bright Finish": { ko: "무코팅", aliases: ["무코팅", "브라이트"], materials: ["N"] },
}

const MATERIAL_META: Record<string, { label: string; ko: string; detail: string; detailKo: string; aliases: string[] }> = {
  "P": { label: "ISO P", ko: "ISO P", detail: "Carbon/Alloy Steel", detailKo: "탄소강/합금강", aliases: ["탄소강", "합금강", "steel", "S45C", "SCM440"] },
  "M": { label: "ISO M", ko: "ISO M", detail: "Stainless Steel", detailKo: "스테인리스강", aliases: ["스테인리스", "스텐", "SUS", "SUS304"] },
  "K": { label: "ISO K", ko: "ISO K", detail: "Cast Iron", detailKo: "주철", aliases: ["주철", "주물", "FC", "FCD"] },
  "N": { label: "ISO N", ko: "ISO N", detail: "Non-ferrous / Aluminum", detailKo: "비철/알루미늄", aliases: ["알루미늄", "비철", "AL", "구리", "황동"] },
  "S": { label: "ISO S", ko: "ISO S", detail: "Heat-resistant / Titanium", detailKo: "내열합금/티타늄", aliases: ["티타늄", "인코넬", "Ti", "Inconel"] },
  "H": { label: "ISO H", ko: "ISO H", detail: "Hardened Steel", detailKo: "경화강", aliases: ["경화강", "열처리강", "HRC", "SKD", "금형강"] },
}

const OPERATION_META: Record<string, { ko: string; aliases: string[] }> = {
  "Milling": { ko: "밀링", aliases: ["밀링", "엔드밀", "사이드밀링"] },
  "Drilling": { ko: "드릴링", aliases: ["드릴링", "홀가공", "보링"] },
  "Threading": { ko: "탭핑", aliases: ["탭핑", "나사가공", "태핑"] },
  "Turning": { ko: "선삭", aliases: ["선삭", "터닝", "CNC선반"] },
}

// ── DB Queries ───────────────────────────────────────────────
async function queryDistinctValues(pool: import("pg").Pool) {
  const queries = {
    subtypes: `SELECT DISTINCT BTRIM(val) AS val, COUNT(*) AS cnt
               FROM catalog_app.product_recommendation_mv,
                    unnest(string_to_array(COALESCE(search_subtype, ''), ',')) AS val
               WHERE BTRIM(val) != '' GROUP BY BTRIM(val) ORDER BY cnt DESC`,
    coatings: `SELECT DISTINCT BTRIM(COALESCE(search_coating, '')) AS val, COUNT(*) AS cnt
               FROM catalog_app.product_recommendation_mv
               WHERE search_coating IS NOT NULL AND BTRIM(search_coating) != ''
               GROUP BY BTRIM(COALESCE(search_coating, '')) ORDER BY cnt DESC`,
    materials: `SELECT DISTINCT UPPER(BTRIM(tag)) AS val, COUNT(*) AS cnt
                FROM catalog_app.product_recommendation_mv,
                     unnest(COALESCE(material_tags, ARRAY[]::text[])) AS tag
                WHERE BTRIM(tag) != '' GROUP BY UPPER(BTRIM(tag)) ORDER BY cnt DESC`,
    operations: `SELECT DISTINCT BTRIM(val) AS val, COUNT(*) AS cnt
                 FROM catalog_app.product_recommendation_mv,
                      unnest(string_to_array(COALESCE(series_application_shape, ''), ',')) AS val
                 WHERE BTRIM(val) != '' GROUP BY BTRIM(val) ORDER BY cnt DESC LIMIT 20`,
    fluteCounts: `SELECT DISTINCT NULLIF(
                    substring(COALESCE(option_numberofflute, milling_number_of_flute, holemaking_number_of_flute, '') from '[0-9]+'), ''
                  )::int AS val, COUNT(*) AS cnt
                  FROM catalog_app.product_recommendation_mv
                  WHERE COALESCE(option_numberofflute, milling_number_of_flute, holemaking_number_of_flute, '') ~ '[0-9]+'
                  GROUP BY val HAVING val IS NOT NULL ORDER BY val`,
    // Co-occurrence: which coatings appear with which materials
    coatingMaterials: `SELECT BTRIM(COALESCE(search_coating, '')) AS coating, UPPER(BTRIM(tag)) AS material, COUNT(*) AS cnt
                       FROM catalog_app.product_recommendation_mv,
                            unnest(COALESCE(material_tags, ARRAY[]::text[])) AS tag
                       WHERE search_coating IS NOT NULL AND BTRIM(search_coating) != '' AND BTRIM(tag) != ''
                       GROUP BY coating, material HAVING COUNT(*) >= 3 ORDER BY cnt DESC`,
    // Co-occurrence: which subtypes appear with which materials
    subtypeMaterials: `SELECT BTRIM(val) AS subtype, UPPER(BTRIM(tag)) AS material, COUNT(*) AS cnt
                       FROM catalog_app.product_recommendation_mv,
                            unnest(string_to_array(COALESCE(search_subtype, ''), ',')) AS val,
                            unnest(COALESCE(material_tags, ARRAY[]::text[])) AS tag
                       WHERE BTRIM(val) != '' AND BTRIM(tag) != ''
                       GROUP BY subtype, material HAVING COUNT(*) >= 3 ORDER BY cnt DESC`,
  }

  const results: Record<string, Array<{ val: string; cnt: number }>> = {}
  const coOccurrences: { coatingMaterials: Array<{ coating: string; material: string }>; subtypeMaterials: Array<{ subtype: string; material: string }> } = {
    coatingMaterials: [],
    subtypeMaterials: [],
  }

  for (const [key, sql] of Object.entries(queries)) {
    try {
      const res = await pool.query(sql)
      if (key === "coatingMaterials") {
        coOccurrences.coatingMaterials = res.rows.map(r => ({ coating: r.coating, material: r.material }))
      } else if (key === "subtypeMaterials") {
        coOccurrences.subtypeMaterials = res.rows.map(r => ({ subtype: r.subtype, material: r.material }))
      } else {
        results[key] = res.rows.map(r => ({ val: String(r.val), cnt: Number(r.cnt) }))
      }
    } catch (err) {
      console.warn(`[kg-sync] Query failed for ${key}:`, err)
      results[key] = []
    }
  }

  return { results, coOccurrences }
}

// ── Build dynamic KG from DB data ────────────────────────────
function buildDynamicKG(
  dbData: { results: Record<string, Array<{ val: string; cnt: number }>>; coOccurrences: { coatingMaterials: Array<{ coating: string; material: string }>; subtypeMaterials: Array<{ subtype: string; material: string }> } }
): KGNode[] {
  const nodes: KGNode[] = [...BASE_FIELD_NODES.map(n => ({ ...n, connections: [] as string[] }))]
  const nodeIds = new Set(nodes.map(n => n.id))

  const addNode = (node: KGNode) => {
    if (nodeIds.has(node.id)) return
    nodeIds.add(node.id)
    nodes.push(node)
  }

  const addConnection = (fromId: string, toId: string) => {
    const from = nodes.find(n => n.id === fromId)
    const to = nodes.find(n => n.id === toId)
    if (from && to) {
      if (!from.connections.includes(toId)) from.connections.push(toId)
      if (!to.connections.includes(fromId)) to.connections.push(fromId)
    }
  }

  // Tool subtypes from DB
  for (const { val, cnt } of dbData.results.subtypes ?? []) {
    const meta = SUBTYPE_META[val]
    const id = `v-${val.toLowerCase().replace(/[\s-]+/g, "")}`
    addNode({
      id,
      type: "value",
      label: val,
      labelKo: meta?.ko ?? val,
      aliases: meta?.aliases ?? [],
      connections: [],
      productCount: cnt,
      autoGenerated: !meta,
    })
    addConnection("f-toolSubtype", id)
    addConnection(id, "op-milling") // most subtypes are milling
  }

  // Coatings from DB
  for (const { val, cnt } of dbData.results.coatings ?? []) {
    const meta = COATING_META[val]
    const id = `v-${val.toLowerCase().replace(/[\s\/.]+/g, "")}`
    addNode({
      id,
      type: "value",
      label: val,
      labelKo: meta?.ko ?? val,
      aliases: meta?.aliases ?? [],
      connections: [],
      productCount: cnt,
      autoGenerated: !meta,
    })
    addConnection("f-coating", id)
  }

  // Materials from DB
  for (const { val, cnt } of dbData.results.materials ?? []) {
    const meta = MATERIAL_META[val]
    if (!meta) continue // Only known ISO codes
    const id = `m-${val}`
    addNode({
      id,
      type: "material",
      label: meta.label,
      labelKo: meta.ko,
      detail: meta.detail,
      detailKo: meta.detailKo,
      aliases: meta.aliases,
      connections: [],
      productCount: cnt,
    })
    addConnection("f-material", id)
  }

  // Flute counts from DB
  for (const { val, cnt } of dbData.results.fluteCounts ?? []) {
    const num = parseInt(val)
    if (isNaN(num) || num < 1 || num > 12) continue
    const id = `v-${num}f`
    addNode({
      id,
      type: "value",
      label: `${num}F`,
      labelKo: `${num}날`,
      aliases: [`${num}날`],
      connections: [],
      productCount: cnt,
    })
    addConnection("f-fluteCount", id)
  }

  // Operations from DB
  for (const { val, cnt } of dbData.results.operations ?? []) {
    const normalized = val.replace(/_/g, " ")
    const baseOp = normalized.includes("Milling") || normalized.includes("Side") || normalized.includes("Slot")
      ? "Milling"
      : normalized.includes("Drill") ? "Drilling"
      : normalized.includes("Thread") ? "Threading"
      : normalized.includes("Turn") ? "Turning"
      : null

    if (baseOp) {
      const meta = OPERATION_META[baseOp]
      const id = `op-${baseOp.toLowerCase()}`
      if (!nodeIds.has(id)) {
        addNode({
          id,
          type: "operation",
          label: baseOp,
          labelKo: meta?.ko ?? baseOp,
          aliases: meta?.aliases ?? [],
          connections: [],
          productCount: cnt,
        })
      }
      addConnection("f-operation", id)
    }
  }

  // ── Auto-generate connections from co-occurrence data ──

  // Coating ↔ Material (from real product data)
  for (const { coating, material } of dbData.coOccurrences.coatingMaterials) {
    const coatingId = `v-${coating.toLowerCase().replace(/[\s\/.]+/g, "")}`
    const materialId = `m-${material}`
    if (nodeIds.has(coatingId) && nodeIds.has(materialId)) {
      addConnection(coatingId, materialId)
    }
  }

  // Subtype ↔ Material (from real product data)
  for (const { subtype, material } of dbData.coOccurrences.subtypeMaterials) {
    const subtypeId = `v-${subtype.toLowerCase().replace(/[\s-]+/g, "")}`
    const materialId = `m-${material}`
    if (nodeIds.has(subtypeId) && nodeIds.has(materialId)) {
      addConnection(subtypeId, materialId)
    }
  }

  // ── Cross-category field connections ──
  addConnection("f-toolSubtype", "f-operation")
  addConnection("f-toolSubtype", "f-material")
  addConnection("f-coating", "f-material")
  addConnection("f-coating", "f-operation")
  addConnection("f-material", "f-fluteCount")
  addConnection("f-diameter", "f-toolSubtype")
  addConnection("f-diameter", "f-operation")
  addConnection("f-operation", "f-diameter")

  return nodes
}

// ── API Handler ──────────────────────────────────────────────
export async function GET() {
  const pool = getSharedPool()

  if (!pool) {
    // Fallback: return empty dynamic data, page will use hardcoded nodes
    return NextResponse.json({
      nodes: [],
      source: "fallback",
      message: "Database not available, using hardcoded knowledge graph",
      syncedAt: new Date().toISOString(),
    })
  }

  try {
    const dbData = await queryDistinctValues(pool)
    const nodes = buildDynamicKG(dbData)

    return NextResponse.json({
      nodes,
      source: "database",
      stats: {
        subtypes: dbData.results.subtypes?.length ?? 0,
        coatings: dbData.results.coatings?.length ?? 0,
        materials: dbData.results.materials?.length ?? 0,
        fluteCounts: dbData.results.fluteCounts?.length ?? 0,
        operations: dbData.results.operations?.length ?? 0,
        coatingMaterialLinks: dbData.coOccurrences.coatingMaterials.length,
        subtypeMaterialLinks: dbData.coOccurrences.subtypeMaterials.length,
      },
      syncedAt: new Date().toISOString(),
    })
  } catch (err) {
    console.error("[kg-sync] Failed:", err)
    return NextResponse.json({
      nodes: [],
      source: "error",
      message: String(err),
      syncedAt: new Date().toISOString(),
    }, { status: 500 })
  }
}
