// SPDX-License-Identifier: MIT
// YG-1 ARIA Simulator v3 — 교육 모드 콘텐츠 DB (코팅)
// PVD/CVD 코팅 특성 사전. Harvey Performance + Oerlikon Balzers + Sandvik Coromant 기반.

import type { EducationDb } from "../education-content"

export const COATING_ENTRIES: EducationDb = {
  "uncoated": {
    id: "uncoated",
    korean: "Uncoated (코팅 없음)",
    english: "Uncoated Carbide",
    category: "coating",
    definition: {
      beginner: "코팅을 입히지 않은 맨 초경 공구. 알루미늄 같은 무른 금속을 빠르게 깎을 때 오히려 유리.",
      intermediate: "폴리싱만 한 초경 모재. 열전도율 높고 매끈한 면 덕에 Al 응착 최소화. vcMultiplier ×1.0 기준.",
      expert: "WC-Co 초경 모재 노출, 표면거칠기 Ra ≤0.05 μm 미러폴리싱. 내열 800°C (초경 자체). vcMultiplier ×1.0 (기준). 권장 재질군: Wrought Aluminum(6061/7075), Brass, Copper. 금기: Steel (급격한 crater wear), SUS (응착·용착 폭증), 주철(연마성 마모). 출처: Harvey Performance Coating Selection Guide.",
    },
    whyItMatters: "Al HSM의 표준. 코팅이 오히려 표면거칠기를 높이므로 미러폴리싱 미코팅이 최선.",
    realWorldExample: "6061-T6 광학마운트 다듬질 ⌀6 3날 미코팅 폴리싱 Vc 2200 m/min, Ra 0.4 μm 달성.",
    commonPitfall: "미코팅을 Steel에 쓰면 10분 내 크레이터 마모로 공구 파단. Al 전용으로만 사용.",
    relatedConcepts: ["wrought-al", "al-6061", "al-7075", "iso-n", "dlc-coating"],
    sourceAuthority: "Harvey Performance Coating Guide / Helical Solutions Tooling Catalog",
  },
  "tin-coating": {
    id: "tin-coating",
    korean: "TiN (황금색)",
    english: "Titanium Nitride (TiN)",
    category: "coating",
    definition: {
      beginner: "황금색 코팅. 가장 오래된 PVD 코팅으로 탭·드릴에 흔함. 저속·연강용 범용. 지금은 구세대.",
      intermediate: "TiN 단층 PVD. 경도 HV 2300, 내열 600°C. vcMultiplier ×1.1. 연강·연질 비철용. 중·고속에서는 AlTiN에 밀림.",
      expert: "조성 TiN stoichiometric, 두께 2-4 μm, 마찰계수 μ 0.4, HV 2300±200, 내열 600°C. vcMultiplier ×1.05-1.15. 권장 재질군: 연강(HBW<200), Brass, Bronze, 저속 탭가공. 금기: SS 고속, 경화강, 난삭재 (600°C 초과 시 산화분해). 출처: Oerlikon Balzers BALINIT A Datasheet.",
    },
    whyItMatters: "가격이 가장 싸고 식별 쉬워(황금색) 탭·리머 기본 코팅. 고속 밀링에는 시대에 뒤떨어짐.",
    realWorldExample: "M10 SM45C 탭가공 TiN 코팅 HSS 탭 Vc 10 m/min, 절삭유 1:20 수용성.",
    commonPitfall: "AlTiN으로 바꿔야 할 SS 가공에 TiN 그대로 쓰면 공구수명 1/3. '금색이면 다 좋다' 오해 주의.",
    relatedConcepts: ["altin-coating", "ticn-coating", "iso-p"],
    sourceAuthority: "Oerlikon Balzers BALINIT A / Harvey Performance Coating Guide",
  },
  "ticn-coating": {
    id: "ticn-coating",
    korean: "TiCN (티타늄 카보나이트라이드)",
    english: "Titanium Carbonitride (TiCN)",
    category: "coating",
    definition: {
      beginner: "TiN에 탄소를 더한 청회색 코팅. TiN보다 단단하고 차갑게 써도 됨. 주철·강용.",
      intermediate: "Ti(C,N) PVD 다층. HV 3000, 내열 400°C(저내열이 약점). vcMultiplier ×1.15. 저-중속 습식가공에 최적.",
      expert: "조성 Ti(C,N) with C/N ratio 0.6-0.8, 두께 3-5 μm, HV 3000±300, μ 0.4, 내열 400°C(중간 수준). vcMultiplier ×1.10-1.20. 권장 재질군: 연·중경 강, 주철(GC, GCD), 습식 드릴링. 금기: 고속 건식 밀링 (400°C 초과 시 산화), SS 고속. 출처: Oerlikon Balzers BALINIT B.",
    },
    whyItMatters: "주철 면삭·드릴링의 주력. AlTiN이 침범하기 전 전통적 주철 챔피언.",
    realWorldExample: "GC250 엔진블록 드릴 ⌀10 TiCN Vc 120 m/min, fz 0.2 mm, 습식 내부쿨런트.",
    commonPitfall: "내열 400°C 한계로 드라이 고속가공에 쓰면 급격한 산화박리. 습식 또는 저속 전용.",
    relatedConcepts: ["tin-coating", "altin-coating", "iso-k", "iso-p"],
    sourceAuthority: "Oerlikon Balzers BALINIT B / Sandvik Coromant PVD Guide",
  },
  "altin-coating": {
    id: "altin-coating",
    korean: "AlTiN (보라색)",
    english: "Aluminum Titanium Nitride (AlTiN)",
    category: "coating",
    definition: {
      beginner: "보라색 코팅. 현대 CNC 엔드밀의 기본. 열에 강해서 빠르게 깎거나 드라이 가공에 최적.",
      intermediate: "Al-rich AlTiN (Al>Ti). HV 3300, 내열 900°C로 고속·건식 적합. vcMultiplier ×1.25. 강·스테인리스·주철 범용.",
      expert: "조성 Al0.67Ti0.33N (Al-rich 조성이 내열성 결정), 두께 3-4 μm, HV 3300±200, μ 0.7, 내열 900°C (절삭중 Al2O3 패시베이션층 생성). vcMultiplier ×1.20-1.30. 권장 재질군: Steel(P), SS(M), Cast Iron(K), 난삭재(S, nano-multilayer 변형). 금기: 알루미늄 (Al 친화성으로 응착 폭증), Diamond 영역. 출처: Oerlikon Balzers BALINIT ALCRONA Pro Datasheet.",
    },
    whyItMatters: "고속가공의 기준 코팅. 한 가지만 고른다면 AlTiN — 강·SS·주철 80% 커버.",
    realWorldExample: "SM45C 몰드 포켓 ⌀10 4날 AlTiN Vc 250 m/min, fz 0.12 mm, ap 10 mm 드라이 트로코이달.",
    commonPitfall: "Al 가공에 AlTiN 그대로 쓰면 Al이 코팅에 녹아 붙음 — Al 전용 미코팅/DLC로 교체.",
    relatedConcepts: ["alcrn-coating", "naco-coating", "iso-p", "iso-m", "iso-k"],
    sourceAuthority: "Oerlikon Balzers BALINIT ALCRONA Pro / Harvey Performance AlTiN Spec",
  },
  "alcrn-coating": {
    id: "alcrn-coating",
    korean: "AlCrN (알루미늄 크롬 나이트라이드)",
    english: "Aluminum Chromium Nitride (AlCrN)",
    category: "coating",
    definition: {
      beginner: "AlTiN의 사촌. 열에 더 강하고 충격에도 강해 황삭·단속가공에 유리.",
      intermediate: "Al-Cr-N 조성. 내열 1100°C로 AlTiN보다 +200°C. 인성 우수 → 단속절삭 챔피언. vcMultiplier ×1.25.",
      expert: "조성 Al0.7Cr0.3N, 두께 3-4 μm, HV 3200±200, μ 0.35, 내열 1100°C (Cr2O3 패시베이션). vcMultiplier ×1.20-1.30. 권장 재질군: SS(M), 고속황삭 강(P), 페이스밀 단속절삭. 금기: Al, 순수 Diamond 영역. 출처: Oerlikon Balzers BALINIT ALCRONA EVO.",
    },
    whyItMatters: "페이스밀·단속절삭의 표준. 충격하중 반복에 AlTiN보다 20% 긴 수명.",
    realWorldExample: "SUS304 페이스밀 ⌀80 인서트 AlCrN Vc 200 m/min, fz 0.15 mm, ap 3 mm, ae 60 mm 단속.",
    commonPitfall: "엔드밀에 AlCrN을 다 쓰면 과도 — 엔드밀은 AlTiN, 페이스밀·인서트는 AlCrN로 구분.",
    relatedConcepts: ["altin-coating", "naco-coating", "iso-m", "iso-p"],
    sourceAuthority: "Oerlikon Balzers BALINIT ALCRONA EVO / Platit Coating Portfolio",
  },
  "naco-coating": {
    id: "naco-coating",
    korean: "nACo / nACRo (나노 복합)",
    english: "nACo / nACRo Nanocomposite",
    category: "coating",
    definition: {
      beginner: "나노 단위 다층 신형 코팅. 극한 재질(인코넬·티타늄) 전용. 비싸지만 수명 2-3배.",
      intermediate: "AlTiN + Si3N4 nano-grain composite. HV 4500+로 PVD 최고등급. 내열 1200°C. vcMultiplier ×1.30. 난삭재 S군 전용.",
      expert: "조성 (Al,Ti,Si)N nanocrystalline + amorphous Si3N4 매트릭스, grain size 3-5 nm. 두께 2-3 μm, HV 4500±300, 내열 1200°C, μ 0.45. vcMultiplier ×1.25-1.35. 권장 재질군: 초내열합금(Inconel, Hastelloy), Ti6Al4V, 경화강 HRC 55+. 금기: Al, 연강 고속(오버스펙). 출처: Platit nACo Technical Brief / Oerlikon BALINIT PERTURA.",
    },
    whyItMatters: "항공엔진 가공의 게임체인저. Inconel에서 AlTiN 대비 수명 2배 → 항공 생산성 핵심.",
    realWorldExample: "IN718 터빈블레이드 루트 ⌀8 4날 nACo Vc 55 m/min, fz 0.08 mm, 수명 90분(AlTiN의 2배).",
    commonPitfall: "연강에 nACo 쓰면 원가만 3배. S·H군 전용으로 한정 — 가격대비 효과 영역 좁음.",
    relatedConcepts: ["altin-coating", "alcrn-coating", "inconel-718", "iso-s", "iso-h"],
    sourceAuthority: "Platit nACo Technical Brief / Oerlikon Balzers BALINIT PERTURA",
  },
  "dlc-coating": {
    id: "dlc-coating",
    korean: "DLC (다이아몬드 유사)",
    english: "Diamond-Like Carbon (DLC)",
    category: "coating",
    definition: {
      beginner: "다이아몬드처럼 미끌미끌한 검은 코팅. 알루미늄이 공구에 붙지 않게 해줌.",
      intermediate: "sp3-rich amorphous carbon (a-C:H). 초저마찰 μ 0.1, 내열 400°C(약점). vcMultiplier ×1.15. Al·비철 응착 방지.",
      expert: "조성 sp3-rich a-C:H (hydrogenated DLC), 두께 1-2 μm, HV 2500-3500, μ 0.1-0.15 (초저마찰), 내열 350-450°C. vcMultiplier ×1.10-1.20. 권장 재질군: Wrought Al, 저실리콘 Cast Al, Cu, 플라스틱, 복합재. 금기: Steel/SS/주철 (내열 부족 + 탄소 확산), 습식 고압 (박리). 출처: Oerlikon Balzers BALINIT DLC / Harvey Performance DLC Guide.",
    },
    whyItMatters: "Al HSM에서 미코팅 이상의 내응착성 제공. 복합재·플라스틱에도 ideal.",
    realWorldExample: "A380 저실리콘 (Si 7%) 다듬질 ⌀6 3날 DLC Vc 1800 m/min, fz 0.10 mm, Ra 0.8 달성.",
    commonPitfall: "DLC를 강에 쓰면 탄소가 철로 확산(FeC 형성) → 수초 내 박리. Al/비철 전용.",
    relatedConcepts: ["uncoated", "zrn-coating", "wrought-al", "cast-al", "iso-n"],
    sourceAuthority: "Oerlikon Balzers BALINIT DLC STAR / Harvey Performance DLC Spec",
  },
  "zrn-coating": {
    id: "zrn-coating",
    korean: "ZrN (지르코늄 나이트라이드)",
    english: "Zirconium Nitride (ZrN)",
    category: "coating",
    definition: {
      beginner: "연한 금색/연황색 코팅. 비철·Al용 대안. TiN보다 Al 친화성이 낮아 응착 덜함.",
      intermediate: "ZrN PVD. HV 2800, 내열 600°C. Al·Cu·Ti 저온 응착 억제. vcMultiplier ×1.10. Al 전용 스페셜.",
      expert: "조성 ZrN stoichiometric, 두께 2-3 μm, HV 2800±200, μ 0.5, 내열 600°C. vcMultiplier ×1.05-1.15. 권장 재질군: Wrought Al(특히 7075), Ti(저속), Cu, 귀금속. 금기: Steel, SS, 주철 (경도 부족). 출처: Oerlikon Balzers BALINIT ZIRENA.",
    },
    whyItMatters: "7075처럼 단단한 Al에서 미코팅보다 수명 30% 연장. Ti 저속 다듬질에도 유용.",
    realWorldExample: "7075-T6 항공 포켓 ⌀10 3날 ZrN Vc 1800 m/min, fz 0.12 mm, 미코팅 대비 수명 +35%.",
    commonPitfall: "강에 잘못 쓰면 수명 TiN 수준. Al/Ti 전용으로 한정.",
    relatedConcepts: ["uncoated", "dlc-coating", "al-7075", "iso-n"],
    sourceAuthority: "Oerlikon Balzers BALINIT ZIRENA / Platit Zirconium Coating Data",
  },
  "crn-coating": {
    id: "crn-coating",
    korean: "CrN (크롬 나이트라이드)",
    english: "Chromium Nitride (CrN)",
    category: "coating",
    definition: {
      beginner: "은회색 코팅. 탭·성형공구에 흔함. 부식·응착에 강하고 생체 친화성도 좋음.",
      intermediate: "CrN PVD 단층/다층. HV 1800, 내열 700°C, 낮은 내부응력으로 두껍게(8-20μm) 코팅 가능. vcMultiplier ×1.05.",
      expert: "조성 CrN, 두께 2-20 μm (성형공구는 후막), HV 1800±150, μ 0.5, 내열 700°C, 잔류응력 낮음. vcMultiplier ×1.00-1.10. 권장 재질군: 탭가공 전반, 연·중경강, Cu, 식품설비(비독성). 금기: 고속 밀링 (경도 부족), 난삭재. 출처: Oerlikon Balzers BALINIT C.",
    },
    whyItMatters: "탭·성형(프레스) 공구의 표준. 연성·인성 중시 응용에 AlTiN 대신.",
    realWorldExample: "SM45C M12 탭 CrN 코팅 HSS Vc 12 m/min, 수명 2000 hole (TiN의 2배).",
    commonPitfall: "엔드밀 고속가공에 쓰면 경도 부족으로 금방 마모. 탭·드로잉 등 저속 전용.",
    relatedConcepts: ["tin-coating", "altin-coating", "alcrn-coating"],
    sourceAuthority: "Oerlikon Balzers BALINIT C / Sandvik Coromant Thread Tooling",
  },
  "diamond-cvd": {
    id: "diamond-cvd",
    korean: "Diamond CVD (다이아몬드 CVD)",
    english: "CVD Diamond Coating",
    category: "coating",
    definition: {
      beginner: "진짜 다이아몬드를 공구에 입힘. 고실리콘 알루미늄·복합재 전용. 강에 쓰면 절대 안 됨.",
      intermediate: "Microcrystalline or nanocrystalline CVD diamond 6-30 μm. HV 9000+, 내열 600°C(공기중). vcMultiplier ×1.40. 초연마성 재료 전용.",
      expert: "조성 폴리크리스탈 sp3 carbon, 두께 6-30 μm, HV 9000-10000 (PVD 대비 3배), 내열 600°C 공기중 (진공에선 1500°C+), μ 0.1. vcMultiplier ×1.30-1.50. 권장 재질군: 고실리콘 Al(A390, Si≥9%), CFRP/GFRP 복합재, 흑연, 세라믹. 금기: Steel/SS/Ni-base (탄소 확산으로 공구 흑연화·순간 파손), 단속절삭(취성 파괴). 출처: Sumitomo CVD Diamond Datasheet / Sandvik Coromant CoroMill 390 Catalog.",
    },
    whyItMatters: "CFRP 항공복합재·고실리콘 주조 Al의 유일한 경제적 해답. 코팅 공구가 PCD 솔리드보다 저렴.",
    realWorldExample: "CFRP 항공스킨 트리밍 ⌀6 2날 CVD Diamond Vc 300 m/min, fz 0.05 mm, 수명 100m (AlTiN의 20배).",
    commonPitfall: "강에 쓰면 즉시 탄소 확산으로 공구 흑연화 — 문자 그대로 수초. 재질 확인 절대 실수 금지.",
    relatedConcepts: ["pcd", "cast-al", "uncoated", "iso-n"],
    sourceAuthority: "Sumitomo Diamond Coating Datasheet / Sandvik Coromant Composite Machining Guide",
  },
  "pcd": {
    id: "pcd",
    korean: "PCD (다결정 다이아몬드)",
    english: "Polycrystalline Diamond (PCD)",
    category: "coating",
    definition: {
      beginner: "공구 인서트 자체가 다이아몬드 결정. 코팅이 아니라 팁에 다이아몬드 덩어리를 브레이징.",
      intermediate: "Co-bonded 다결정 다이아몬드 팁(0.5-1.5 mm). HV 8000, 내열 700°C. vcMultiplier ×1.50 이상. 고실리콘 Al·복합재 전용.",
      expert: "조성 입도 2-25 μm 다이아몬드 + Co 5-10% 결합제, HPHT 소결. 두께 0.5-1.5 mm 팁을 WC 모재에 브레이징. HV 7000-9000, 내열 700°C(공기), μ 0.05-0.1. vcMultiplier ×1.40-1.60. 권장 재질군: 고실리콘 Al(A390, Si 17%), CFRP, Cu·Brass 대량생산, MMC. 금기: Fe계(즉시 확산마모), Ni-base, 단속절삭 중충격. 출처: Element Six PCD Grade Guide / Sandvik Coromant CoroMill PCD.",
    },
    whyItMatters: "자동차 Al 엔진블록 대량생산의 핵심. 수명 CVD 대비 +50%, 재연마 가능 → 장기 TCO 유리.",
    realWorldExample: "A380 엔진블록 페이스밀 ⌀125 PCD 인서트 6매 Vc 1200 m/min, fz 0.15 mm, 수명 20,000 parts.",
    commonPitfall: "PCD는 재연마 가능하지만 전용 EDM 연삭기 필요 — 일반 그라인더에선 다이아몬드 연삭 불가.",
    relatedConcepts: ["diamond-cvd", "cast-al", "wrought-al", "iso-n"],
    sourceAuthority: "Element Six PCD Grade Selection Guide / Sandvik Coromant CoroMill PCD Catalog",
  },
  "tib2-coating": {
    id: "tib2-coating",
    korean: "TiB2 (티타늄 디보라이드)",
    english: "Titanium Diboride (TiB2)",
    category: "coating",
    definition: {
      beginner: "Al 응착을 막는 은색 세라믹 코팅. 알루미늄에 미코팅·DLC 대안으로 점점 인기.",
      intermediate: "TiB2 PVD 단층. HV 3500, 내열 900°C, 낮은 Al 친화성. vcMultiplier ×1.15. Al/Mg 고속가공 스페셜.",
      expert: "조성 TiB2 hexagonal, 두께 2-3 μm, HV 3500±300, μ 0.5, 내열 900°C (공기 중 산화 시작), 화학적으로 Al과 비반응. vcMultiplier ×1.10-1.20. 권장 재질군: Wrought Al(2xxx, 7xxx 포함), Mg 합금, 저-중실리콘 Cast Al. 금기: Steel(경제성 낮음), 난삭재. 출처: Platit TiB2 Technical Brief / Kennametal Aluminum Tooling.",
    },
    whyItMatters: "DLC보다 내열 2배 + Al 응착성 DLC 수준. 고속 Al 드라이가공의 차세대 옵션.",
    realWorldExample: "7075-T6 항공 리브 포켓 ⌀10 3날 TiB2 Vc 2200 m/min, fz 0.15 mm, 드라이 에어블라스트.",
    commonPitfall: "강에 쓰면 경제적 의미 없음 — AlTiN 대비 비싸고 수명도 떨어짐. Al/Mg 전용으로 명확히.",
    relatedConcepts: ["dlc-coating", "uncoated", "zrn-coating", "al-7075", "iso-n"],
    sourceAuthority: "Platit TiB2 Technical Brief / Kennametal Aluminum Application Guide",
  },
}
