// SPDX-License-Identifier: MIT
// YG-1 ARIA Simulator v3 — 교육 콘텐츠: depth (절입/치수 계열)
import type { EducationDb } from "../education-content"

export const DEPTH_ENTRIES: EducationDb = {
  adoc: {
    id: "adoc",
    korean: "축방향 절입 ADOC / ap (Axial Depth of Cut)",
    english: "Axial Depth of Cut",
    category: "depth",
    definition: {
      beginner: "엔드밀을 공작물에 얼마나 깊게(아래로) 꽂고 가공하는지(mm). 빵칼을 얼마나 깊이 누르는가와 같음.",
      intermediate: "축방향 절입량 ap [mm]. 공구 축 방향으로 재료에 잠기는 깊이. LOC의 일부만 쓰는 것이 원칙.",
      expert: "ap ≤ LOC. 슬로팅 기준 일반가공 ap ≤ 1·D, HSM 트로코이달은 ap ≤ 2~3·D 가능(단 ae ≤ 0.1·D). 과대 ap는 공구 편심 deflection과 채터의 1차 원인. 출처: Harvey Performance MAP / Sandvik Coromant Handbook Ch.3.",
    },
    formula: "ap = Axial Depth (mm)  ·  ap ≤ LOC",
    whyItMatters: "ap가 크면 MRR은 직선적으로 커지지만, 공구 비틀림·채터 위험은 ap²~ap³로 커진다. 트레이드오프가 가장 큰 변수.",
    realWorldExample: "⌀10mm 4날 엔드밀로 SUS304 트로코이달: ap=25mm(2.5D), ae=1mm(0.1D), Vf=1500 mm/min.",
    commonPitfall: "LOC를 ap로 착각해서 공구 전체 날 길이를 꽂으면 flute 상단이 칩을 못 배출해 채터·파손.",
    relatedConcepts: ["rdoc", "loc", "engagement-angle", "axial"],
    sourceAuthority: "Harvey Performance MAP User Guide",
  },
  rdoc: {
    id: "rdoc",
    korean: "경방향 절입 RDOC / ae (Radial Depth of Cut)",
    english: "Radial Depth of Cut",
    category: "depth",
    definition: {
      beginner: "엔드밀이 옆으로 재료를 얼마나 넓게 베어먹고 지나가는지(mm). 공구 지름 대비 몇 %를 먹느냐로 본다.",
      intermediate: "경방향 절입량 ae [mm]. Stepover라고도 함. ae/D 비율이 접촉각과 칩 두께를 결정.",
      expert: "ae [mm]. 슬로팅 ae=D, 일반 측면 ae=0.3~0.5·D, HSM 트로코이달 ae ≤ 0.1·D. ae<D/2에서 chip thinning: hex = fz·2·√(ae/D − (ae/D)^2), fz 보정 필수. 출처: Harvey Performance MAP §Radial Chip Thinning.",
    },
    formula: "ae = Radial Depth (mm)",
    whyItMatters: "ae가 작을수록 접촉각·발열이 작아 공구 수명↑, 대신 같은 MRR에 이송을 크게 올려야 해서 기계 동특성이 중요해진다.",
    realWorldExample: "⌀10mm HSM: ae=1mm(10%), ap=20mm(2D), fz_보정=0.08mm → 카탈로그 fz 0.05의 1.6배까지 올려야 정상 칩 두께.",
    commonPitfall: "ae를 줄이면서 fz를 그대로 두면 실제 칩이 너무 얇아져 rubbing·경화 발생. chip thinning 보정은 필수.",
    relatedConcepts: ["adoc", "engagement-angle", "radial", "fz"],
    sourceAuthority: "Harvey Performance MAP User Guide §Radial Chip Thinning",
  },
  loc: {
    id: "loc",
    korean: "절삭날 길이 LOC (Length of Cut)",
    english: "Length of Cut",
    category: "depth",
    definition: {
      beginner: "공구 끝부터 날(플루트)이 새겨진 부분까지의 길이(mm). 이 길이 안에서만 실제로 깎을 수 있음.",
      intermediate: "절삭날 유효 길이 LOC [mm]. Flute length라고도 함. ap의 상한이자 칩 배출 공간의 지표.",
      expert: "LOC [mm]. ap ≤ LOC가 원칙이나 실무는 ap ≤ 0.8·LOC 권장(상단 칩 충돌 방지). LOC가 길수록 강성은 급감(deflection ∝ L³), 대신 깊은 포켓 가공 가능. 출처: Kennametal NOVO / Harvey Performance Tool Selection Guide.",
    },
    formula: "ap_max ≈ 0.8 · LOC",
    whyItMatters: "긴 LOC 공구는 깊이 파지만 강성이 L^3로 떨어져 채터와 치수오차가 급증. 필요한 최소 LOC만 골라야 한다.",
    realWorldExample: "⌀10mm · LOC 30mm 스터브 vs LOC 50mm 롱넥. 같은 조건에서 롱넥은 deflection이 약 4.6배 크다.",
    commonPitfall: "가공 깊이보다 훨씬 긴 LOC 공구를 선택해 강성을 불필요하게 낭비하는 케이스가 가장 흔하다.",
    relatedConcepts: ["adoc", "oal", "stick-out"],
    sourceAuthority: "Kennametal NOVO Technical Guide",
  },
  oal: {
    id: "oal",
    korean: "공구 전장 OAL (Overall Length)",
    english: "Overall Length",
    category: "depth",
    definition: {
      beginner: "공구 맨 끝부터 섕크 끝까지의 전체 길이(mm). 공구 한 자루의 총 길이.",
      intermediate: "전장 OAL [mm]. 홀더에 물리는 구간과 돌출 구간 모두 포함. Stick-out(LSO) = OAL − 섕크 파지 길이.",
      expert: "OAL [mm]. 공구 강성은 LSO(돌출)로 결정되며 deflection ∝ LSO³. 같은 OAL이라도 홀더 파지 깊이를 최대화(섕크 길이의 3D 이상 파지)하면 강성 대폭 상승. 출처: Sandvik Coromant Holder Handbook.",
    },
    formula: "LSO = OAL − 홀더 파지 길이",
    whyItMatters: "OAL 자체보다 stick-out이 강성의 본질. 같은 OAL도 얕게 파지하면 공구가 한참 더 흔들린다.",
    realWorldExample: "⌀10mm 엔드밀 OAL 75mm. 섕크 25mm 파지 시 LSO=50mm, 섕크 35mm 파지 시 LSO=40mm → deflection 약 2배 차이.",
    commonPitfall: "깊은 포켓 때문에 OAL 긴 공구를 쓰면서 홀더 파지 길이를 늘리지 않아 과도한 채터가 나는 경우.",
    relatedConcepts: ["loc", "stick-out", "shank"],
    sourceAuthority: "Sandvik Coromant Holder & Adaptive Tooling Handbook",
  },
  "engagement-angle": {
    id: "engagement-angle",
    korean: "접촉각 (Engagement Angle)",
    english: "Radial Engagement Angle",
    category: "depth",
    definition: {
      beginner: "공구 날 하나가 공작물을 지나가는 동안 재료와 맞닿는 각도(도). 슬로팅은 180°, 얇게 치면 작아짐.",
      intermediate: "경방향 접촉각 φ [deg]. ae/D에 의해 결정. 발열·절삭력·칩 두께 프로필을 지배.",
      expert: "φ = arccos(1 − 2·ae/D) [rad] · 180/π. 슬로팅 ae=D → 180°, ae=0.5D → 120°, ae=0.1D → 53°. HSM/트로코이달은 φ ≤ 60° 유지가 원칙(발열·공구수명 최적점). 출처: Harvey Performance MAP §Dynamic Milling.",
    },
    formula: "φ = arccos(1 − 2·ae/D)",
    whyItMatters: "접촉각이 크면 한 날이 재료에 오래 잠겨 열 부하↑·공구수명↓. HSM의 핵심 원리는 이 각을 작게 유지하는 것.",
    realWorldExample: "⌀10mm, ae=1mm → φ ≈ 53°. ae=3mm → φ ≈ 93°. ae=5mm → φ = 180°(슬로팅).",
    commonPitfall: "CAM에서 stepover(ae)만 보고 접촉각을 고려하지 않으면 코너에서 실제 접촉각이 급격히 커져 공구가 깨진다.",
    relatedConcepts: ["rdoc", "radial", "adoc"],
    sourceAuthority: "Harvey Performance MAP User Guide §Dynamic Milling",
  },
  axial: {
    id: "axial",
    korean: "축방향 (Axial Direction)",
    english: "Axial Direction",
    category: "depth",
    definition: {
      beginner: "공구 회전축 방향(보통 Z축, 위아래). 엔드밀에서 '깊이' 방향을 말함.",
      intermediate: "공구 회전축과 평행한 방향. 밀링에서 ap(ADOC)가 이 방향의 절입. 드릴링의 이송 방향도 축방향.",
      expert: "Axial direction. 3축 밀링 스탠다드 좌표에서 일반적으로 −Z. 축방향 절삭력 Fz는 공구 당김(pulling)이나 밀어냄(pushing)을 유발하며 helix angle과 up/down cut에 의해 부호가 바뀜. 출처: ISO 841 / Sandvik Coromant Handbook Ch.A.",
    },
    formula: "— (방향 정의)",
    whyItMatters: "축방향 절삭력의 부호(up/down)가 클램핑 방식과 맞지 않으면 공작물이 들려 정밀도가 무너진다.",
    realWorldExample: "⌀10mm 30° helix 엔드밀 다운컷: Fz가 아래로 작용해 공작물을 테이블에 눌러줌 → 얇은 판재 가공에 유리.",
    commonPitfall: "헬릭스 방향과 up/down cut을 고려 안 하면 축방향 힘이 공작물을 들어올려 바이스에서 빠진다.",
    relatedConcepts: ["adoc", "radial", "loc"],
    sourceAuthority: "ISO 841 Machine Tool Axis Convention",
  },
  radial: {
    id: "radial",
    korean: "경방향 (Radial Direction)",
    english: "Radial Direction",
    category: "depth",
    definition: {
      beginner: "공구 회전축과 직각 방향(옆 방향). 엔드밀이 옆으로 얼마나 먹는지를 이 방향으로 잰다.",
      intermediate: "공구 회전축에 수직인 방향. ae(RDOC)가 이 방향 절입. 측면 가공에서 주로 논의되는 축.",
      expert: "Radial direction. 경방향 절삭력 Fr은 공구를 공작물에서 밀어내려 함 → deflection의 주원인. 측면 가공에서 다운컷은 Fr이 벽쪽으로, 업컷은 공구 쪽으로 작용해 표면조도·치수에 반대 효과. 출처: ASM Metals Handbook Vol.16.",
    },
    formula: "— (방향 정의)",
    whyItMatters: "경방향 deflection은 벽면 치수 오차(예: 10mm 폭이 9.95mm)의 1차 원인. 공구 강성·ae 선택이 중요.",
    realWorldExample: "⌀10mm LSO=40mm 엔드밀, ae=5mm(슬롯 절반)에서 경방향 deflection 약 20~40μm 발생 가능.",
    commonPitfall: "경방향 deflection을 감안하지 않고 한 번에 마무리 패스를 하면 벽이 테이퍼지거나 치수가 덜 나온다. 마무리 패스는 ae를 작게.",
    relatedConcepts: ["rdoc", "axial", "engagement-angle"],
    sourceAuthority: "ASM Metals Handbook Vol.16 Machining",
  },
  "stick-out": {
    id: "stick-out",
    korean: "공구 돌출 Stick-out (LSO)",
    english: "Tool Stick-out (Overhang)",
    category: "depth",
    definition: {
      beginner: "홀더에서 공구가 얼마나 바깥으로 튀어나와 있는지(mm). 길게 튀어나올수록 흔들리기 쉬움.",
      intermediate: "Stick-out, Overhang LSO [mm]. 홀더 끝에서 공구 팁까지의 길이. 공구 유효 강성의 1차 지표.",
      expert: "LSO [mm]. 공구 끝 변형 δ ∝ F·LSO³ / (E·I), I = π·D^4/64. LSO 4D 초과 시 deflection·채터 급증, 6D 이상은 HSM/트로코이달 전용 파라미터 필수. 출처: Kennametal NOVO Technical / Altintas, Manufacturing Automation (2012).",
    },
    formula: "δ ∝ LSO³ / D⁴  (deflection)",
    whyItMatters: "LSO가 2배면 deflection은 8배. 공구 선정의 1순위는 '가공 깊이 + 여유'로 LSO를 최소화하는 것.",
    realWorldExample: "⌀10mm, LSO 30mm(3D)에서 deflection 10μm이면 LSO 60mm(6D)에서는 80μm.",
    commonPitfall: "넥이 가는 long-reach 공구(reduced neck)를 일반 ap로 쓰면 LSO³ 효과로 치수가 전혀 안 맞음. 필요한 reach 이상은 절대 쓰지 말 것.",
    relatedConcepts: ["oal", "loc", "axial"],
    sourceAuthority: "Altintas, Manufacturing Automation, Cambridge Univ. Press (2012)",
  },
}
