// SPDX-License-Identifier: MIT
// YG-1 ARIA Simulator v3 — 교육 모드 콘텐츠 DB (재질)
// ISO 513:2012 분류 + ASM Metals Handbook 기반 공작물 재질 사전.

import type { EducationDb } from "../education-content"

export const MATERIAL_ENTRIES: EducationDb = {
  "iso-p": {
    id: "iso-p",
    korean: "ISO P — 탄소·합금강",
    english: "ISO P (Steel, Carbon & Alloy)",
    category: "material",
    definition: {
      beginner: "가장 흔한 쇠. 자동차 차축이나 기계 부품에 쓰인다. 깎기 무난해서 CNC 입문자도 다루기 쉬움.",
      intermediate: "ISO 513의 P군. 탄소강·합금강·주강 포함. 칩 형성 연속형이라 칩브레이커 필수. 권장 Vc 150-250 m/min (HSS 공구 기준 25-40).",
      expert: "탄소강 C 0.1-0.6% / 합금강 Cr·Mo·Ni 첨가. HBW 150-300, HRC 25-35 구간. 권장 Vc 150-300 m/min (코팅 초경), fz 0.08-0.25 mm/tooth. 권장 코팅: TiAlN, AlTiN, nACo. 금기: Diamond/PCD (탄소 확산 → 공구 흑연화). 응용: 자동차 크랭크샤프트·기어·금형 베이스. 출처: ISO 513:2012, Sandvik Coromant Rotating Tools Ch.A.",
    },
    whyItMatters: "전 세계 절삭 가공의 약 40%를 차지하는 기준 재질군. 모든 SFM 차트의 베이스라인.",
    realWorldExample: "SM45C (C 0.45%) 블록에 ⌀12 4날 AlTiN 엔드밀로 Vc 220 m/min, fz 0.12 mm, ap 6 mm 슬롯가공이 표준.",
    commonPitfall: "저탄소강(SM10C 등)은 연질이라 오히려 칩이 공구에 엉겨붙음 — BUE(구성인선) 주의.",
    relatedConcepts: ["sfm", "ipt", "altin-coating", "iso-h", "kc"],
    sourceAuthority: "ISO 513:2012 Table 1 / ASM Metals Handbook Vol.1",
  },
  "iso-m": {
    id: "iso-m",
    korean: "ISO M — 스테인리스 강",
    english: "ISO M (Stainless Steel)",
    category: "material",
    definition: {
      beginner: "스테인리스 강. 자석에 잘 안 붙고 녹슬지 않지만 끈적해서 깎기 까다롭다. 공구가 빨리 닳음.",
      intermediate: "오스테나이트·페라이트·마르텐사이트계 포함. 가공경화성 높고 열전도율 낮아 (15 W/m·K, 강의 1/3) 날끝 온도 급상승. 권장 Vc 120-180 m/min.",
      expert: "Cr ≥10.5% 필수, 대표 304/316/17-4PH. HBW 150-250, 가공 후 표층 HV +30-50 증가 (work-hardening). 권장 Vc 120-200 m/min, fz 0.05-0.15 mm, ap 최소 0.3 mm (경화층 아래 진입 필수). 권장 코팅: AlTiN, AlCrN, nACo. 금기: TiN 단층 (내열성 부족). 응용: 의료기기·식품설비·화학플랜트. 출처: Sandvik Coromant Material Classification.",
    },
    whyItMatters: "가공경화 특성으로 '얕게 긁으면 더 단단해짐' — 올바른 진입전략 없으면 공구 수명이 1/5로 떨어진다.",
    realWorldExample: "SUS304 파이프 페이싱 시 Vc 150 m/min, fz 0.12 mm, ap 1.5 mm로 경화층을 확실히 아래부터 자른다.",
    commonPitfall: "fz가 너무 작으면(<0.05) 공구가 표면을 '문지르며' 경화층만 두껍게 만들어 다음 패스가 더 힘들어짐.",
    relatedConcepts: ["sus-304", "sus-316", "altin-coating", "alcrn-coating", "work-hardening"],
    sourceAuthority: "ISO 513:2012 / Sandvik Coromant Stainless Application Guide",
  },
  "iso-k": {
    id: "iso-k",
    korean: "ISO K — 주철",
    english: "ISO K (Cast Iron)",
    category: "material",
    definition: {
      beginner: "주철. 엔진 블록이나 맨홀 뚜껑에 쓰이는 회색 쇠. 부서지는 칩이 나와서 절삭유 없이도 깎인다.",
      intermediate: "회주철(GC)·구상흑연주철(GGG)·가단주철 포함. 칩 형성 불연속형(단편칩). 흑연이 내부 윤활 역할 → Vc 높게 가능. 권장 Vc 180-350 m/min.",
      expert: "회주철 GC250: C 3.2-3.5%, Si 1.8-2.2%, HBW 180-230 / 구상흑연주철 GCD500: HBW 170-241. 권장 Vc 200-400 m/min (세라믹공구는 800까지), fz 0.15-0.40 mm. 권장 코팅: Al2O3 CVD, TiCN. 금기: 습식 + 고속 (열충격으로 세라믹 공구 파손). 응용: 자동차 엔진블록·실린더헤드·기계 베드. 출처: ASM Handbook Vol.1 'Cast Irons'.",
    },
    whyItMatters: "드라이가공 가능한 거의 유일한 재질군. 절삭유 없어도 흑연이 윤활 → 비용·환경 양쪽 절감.",
    realWorldExample: "엔진블록 GC250 면삭 시 Vc 300 m/min, fz 0.25 mm, ap 2 mm 드라이 가공으로 공구수명 500 min 확보.",
    commonPitfall: "표면의 주조 스킨(경도 HV 500+)을 얕은 ap로 긁으면 공구 치핑 — 첫 패스는 ap 2 mm 이상으로 스킨 아래 진입.",
    relatedConcepts: ["ticn-coating", "sfm", "cast-al", "iso-p"],
    sourceAuthority: "ISO 513:2012 / ASM Metals Handbook Vol.1 Ch.'Cast Irons'",
  },
  "iso-n": {
    id: "iso-n",
    korean: "ISO N — 비철·알루미늄",
    english: "ISO N (Non-ferrous, Aluminum & Copper alloys)",
    category: "material",
    definition: {
      beginner: "알루미늄·구리처럼 무른 금속. 엄청 빠르게 깎을 수 있고 칩이 길게 나와 감겨 올라옴.",
      intermediate: "가공용 Al(2xxx-7xxx) / 주조 Al(A356 등) / 구리·황동 포함. 높은 열전도율로 날끝 냉각 유리. 권장 Vc 500-3000 m/min.",
      expert: "Wrought Al: HBW 60-150, Cast Al (Si 함유): HBW 70-120, Si ≥9%는 고실리콘 — PCD 필수. 권장 Vc 1000-3500 m/min (Helical 고속 알루미늄 3날 기준), fz 0.08-0.25 mm at ⌀10. 권장 코팅: Uncoated polished, ZrN, DLC. 금기: TiN·AlTiN (Al 응착). 응용: 항공기 스킨·자동차 휠·전자기기 하우징. 출처: Helical Solutions Aluminum SFM Chart.",
    },
    whyItMatters: "HSM(고속가공)의 주 대상. 날수 2-3으로 줄이고 나선각 35-45°로 칩 배출 극대화.",
    realWorldExample: "Al6061 포켓 ⌀8 3날 미코팅 엔드밀 Vc 1500 m/min, fz 0.12 mm, ap 8 mm(=1×D) 풀슬롯 가공.",
    commonPitfall: "일반 엔드밀(날수 4+)로 Al 가공 시 칩포켓 부족 → 칩이 재절삭되며 공구 파단. 3날 전용품 사용할 것.",
    relatedConcepts: ["wrought-al", "cast-al", "al-6061", "al-7075", "dlc-coating", "uncoated"],
    sourceAuthority: "ISO 513:2012 / Helical Solutions Technical Data Sheet (Aluminum)",
  },
  "iso-s": {
    id: "iso-s",
    korean: "ISO S — 초내열합금·티타늄",
    english: "ISO S (Superalloys & Titanium)",
    category: "material",
    definition: {
      beginner: "제트엔진용 특수 금속. 700°C에서도 강도 유지. 깎기 엄청 어려워 공구 수명이 강 대비 1/10.",
      intermediate: "Ni-base(Inconel, Hastelloy) / Co-base / Ti-base 포함. 낮은 열전도(Ti: 7 W/m·K) + 가공경화 + 화학적 반응성 3중고. 권장 Vc 30-80 m/min.",
      expert: "Inconel 718: HBW 330-400, Ti6Al4V: HBW 300-350. 권장 Vc 30-60 m/min (Ni-base), 40-90 m/min (Ti), fz 0.05-0.12 mm, radial chip thinning 고려 필수 ae ≤ 0.3×D. 권장 코팅: AlTiN nano-layer, nACRo, TiAlSiN. 금기: 고속 드라이 + Ti (발화 위험). 응용: 항공 터빈 블레이드·우주 엔진·인공관절. 출처: Sandvik Coromant Aerospace Application Guide.",
    },
    whyItMatters: "항공·의료 고부가가치 가공의 핵심. 공구비가 총가공비의 30% 이상 차지 — 파라미터 실수 1회로 $500+ 손실.",
    realWorldExample: "Inconel 718 임펠러 황삭 ⌀16 4날 AlTiN 엔드밀 Vc 45 m/min, fz 0.08 mm, ae 2.4 mm(0.15×D) 트로코이달.",
    commonPitfall: "일반 강 파라미터로 진입하면 1패스에 공구 파손. Vc를 강 대비 1/4-1/5로 낮추는 것이 출발점.",
    relatedConcepts: ["inconel-718", "altin-coating", "naco-coating", "iso-h", "trochoidal"],
    sourceAuthority: "ISO 513:2012 / Sandvik Coromant Aerospace Machining Guide",
  },
  "iso-h": {
    id: "iso-h",
    korean: "ISO H — 경화강",
    english: "ISO H (Hardened Steel, HRC 45-65)",
    category: "material",
    definition: {
      beginner: "열처리로 아주 단단하게 만든 쇠. 금형에 많이 쓰임. 연삭 대신 깎을 수 있으면 시간 대폭 절감.",
      intermediate: "HRC 45-65 담금질강·고속도강·콜드워크 금형강. Hard milling으로 연삭 대체. 권장 Vc 80-180 m/min (CBN/세라믹은 200+).",
      expert: "대표 재질 STD61 HRC 50-52, SKD11 HRC 58-62, D2 HRC 60-62. 권장 Vc 80-200 m/min, fz 0.05-0.15 mm, ap ≤0.3×D (공구 휨 최소화). 권장 코팅: AlTiN, TiAlSiN, CBN 인서트. 금기: 습식 (열충격으로 미세 크랙). 응용: 금형 코어·핀·다이 인서트. 출처: Harvey Tool Hardened Steel Guide.",
    },
    whyItMatters: "연삭공정을 절삭으로 대체하면 리드타임 50% 단축. 금형산업의 패러다임 시프트 주도.",
    realWorldExample: "STD61 HRC 52 금형코어 ⌀6 2날 AlTiN 볼 엔드밀 Vc 150 m/min, fz 0.08 mm, ap 0.15 mm 드라이 다듬질.",
    commonPitfall: "HRC 55 이상에서는 돌출 길이 L/D ≤ 3 필수. 공구 휨 = 치수 오차 = 금형 수정 비용.",
    relatedConcepts: ["iso-p", "altin-coating", "hbw-hrc-scales"],
    sourceAuthority: "ISO 513:2012 / Harvey Performance Hardened Steel Machining Guide",
  },
  "wrought-al": {
    id: "wrought-al",
    korean: "가공용 알루미늄 (Wrought)",
    english: "Wrought Aluminum Alloys",
    category: "material",
    definition: {
      beginner: "판재·봉재로 압연·압출한 알루미늄. 6061/7075가 대표. 항공기 부품에 많이 쓰임.",
      intermediate: "2xxx(Cu계)·6xxx(Mg-Si계)·7xxx(Zn계). T6 시효경화 상태가 가장 흔함. 권장 Vc 800-2500 m/min.",
      expert: "6061-T6: Si 0.6%, Mg 1.0%, HBW 95±5 / 7075-T6: Zn 5.6%, Mg 2.5%, HBW 150±10. 권장 Vc 1000-3000 m/min, fz 0.08-0.20 mm at ⌀10, 3날 하이헬릭스(40-45°). 권장 코팅: Uncoated polished, ZrN, DLC. 금기: AlTiN/TiAlN (Al 응착). 응용: 항공 스킨·프레임·자동차 스티어링 너클. 출처: ASM Metals Handbook Vol.2 'Aluminum Alloys'.",
    },
    whyItMatters: "주조 알루미늄과 파라미터 체계가 다름. Si 함량 1% 이하라 공구 마모가 낮고 HSM 최적 대상.",
    realWorldExample: "7075-T6 블록 포켓 가공 ⌀10 3날 미코팅 엔드밀 Vc 1800 m/min, fz 0.15 mm, ap 10 mm(=1×D) 풀슬롯.",
    commonPitfall: "7075는 6061보다 단단해서 같은 파라미터로 시작하면 공구 수명 2배 차이 — T6 상태 경도 반드시 확인.",
    relatedConcepts: ["al-6061", "al-7075", "iso-n", "cast-al", "uncoated"],
    sourceAuthority: "ASM Metals Handbook Vol.2 / Helical Solutions Aluminum Speeds&Feeds",
  },
  "cast-al": {
    id: "cast-al",
    korean: "주조 알루미늄 (Cast)",
    english: "Cast Aluminum Alloys",
    category: "material",
    definition: {
      beginner: "녹여서 틀에 부어 만든 알루미늄. 자동차 엔진블록·휠이 대표. 실리콘이 섞여 약간 거칠게 깎임.",
      intermediate: "A356·A380·ADC12 등. Si 7-12%로 내마모성 확보했지만 Si 입자가 공구 마모 주범. 권장 Vc 300-900 m/min.",
      expert: "A356-T6: Si 7%, Mg 0.3%, HBW 75-85 / A380: Si 8.5%, Cu 3.5%, HBW 80 / 고실리콘 A390 Si 17%는 PCD 필수. 권장 Vc 500-1200 m/min (일반 주조 Al), fz 0.08-0.18 mm. 권장 코팅: Diamond CVD, PCD (Si≥9%), DLC. 금기: AlTiN (응착), Uncoated (Si 연삭성 마모). 응용: 엔진블록·트랜스미션 하우징·휠. 출처: ASM Metals Handbook Vol.2.",
    },
    whyItMatters: "Si 함량이 코팅 선택을 좌우. 일반(7%)은 DLC, 고실리콘(≥9%)은 PCD — 잘못 고르면 공구수명 10배 차이.",
    realWorldExample: "A380 엔진블록 페이싱 ⌀80 PCD 페이스밀 Vc 1000 m/min, fz 0.15 mm, ap 3 mm 드라이 가공.",
    commonPitfall: "재활용 Al(ADC12) 사용 시 Si·Fe 변동 크고 경질 개재물 포함 — 공구수명 예측 어려워 안전계수 1.5 적용.",
    relatedConcepts: ["wrought-al", "pcd", "diamond-cvd", "iso-n", "dlc-coating"],
    sourceAuthority: "ASM Metals Handbook Vol.2 'Aluminum Alloys' Ch.Casting",
  },
  "sus-304": {
    id: "sus-304",
    korean: "SUS304 / AISI 304",
    english: "SUS304 / AISI 304 Austenitic Stainless",
    category: "material",
    definition: {
      beginner: "주방용 싱크대나 주전자에 쓰는 가장 흔한 스테인리스. 깎을 때 끈적하고 공구가 잘 무뎌짐.",
      intermediate: "오스테나이트계 대표. 18Cr-8Ni. 비자성, 우수한 내식성, 그러나 낮은 열전도·높은 가공경화. 권장 Vc 130-200 m/min.",
      expert: "조성: Cr 18%, Ni 8%, C ≤0.08%. HBW 150-200, 가공경화 후 표층 HV 400+. 권장 Vc 150-220 m/min, fz 0.08-0.18 mm at ⌀10, ap ≥0.5 mm. 권장 코팅: AlTiN, AlCrN. 금기: TiN 단층, Diamond. 응용: 식품설비·건축외장·화학배관. 출처: Sandvik Coromant Stainless Handbook.",
    },
    whyItMatters: "전 세계 스테인리스 수요의 50%. 오스테나이트계 기준 파라미터 — 다른 SS는 여기서 ±10% 보정.",
    realWorldExample: "SUS304 파이프 이면 다듬질 ⌀8 4날 AlTiN 엔드밀 Vc 180 m/min, fz 0.10 mm, ap 0.5 mm, ae 0.4 mm.",
    commonPitfall: "316과 헷갈리기 쉬움 — 304에 316 파라미터(-15%) 적용하면 생산성 손실. 자석·성분 확인 필수.",
    relatedConcepts: ["sus-316", "iso-m", "altin-coating", "work-hardening"],
    sourceAuthority: "AISI 304 / JIS G 4303 / Sandvik Coromant Material Card P-M-N-S",
  },
  "sus-316": {
    id: "sus-316",
    korean: "SUS316 / AISI 316",
    english: "SUS316 / AISI 316 Molybdenum-bearing Stainless",
    category: "material",
    definition: {
      beginner: "SUS304보다 녹 더 잘 안 스는 스테인리스. 바닷물·약품에 강함. 의료기기·선박에 쓰임. 더 깎기 힘듦.",
      intermediate: "Mo 2-3% 추가로 내공식성 향상. 가공성은 304 대비 -10~-15%. 권장 Vc 120-180 m/min.",
      expert: "조성: Cr 17%, Ni 10-14%, Mo 2-3%, C ≤0.08%. HBW 160-210. 권장 Vc 130-200 m/min, fz 0.07-0.15 mm, ap ≥0.5 mm. 권장 코팅: AlTiN nano-layer, nACo. 금기: TiN, Diamond. 응용: 해양플랜트·의료 임플란트·제약설비. 출처: Sandvik Coromant Stainless Guide.",
    },
    whyItMatters: "의료·식품 산업 필수. 가격은 304 대비 1.5배이지만 재작업 비용이 더 크므로 파라미터 보수적으로.",
    realWorldExample: "316L 의료임플란트 드릴링 ⌀5 고압 쿨런트 40bar Vc 150 m/min, fz 0.08 mm, peck 1×D.",
    commonPitfall: "Mo 때문에 절삭저항 kc가 304보다 높음 (2700 → 2900 N/mm²) — 공구 강성 부족 시 채터 빈발.",
    relatedConcepts: ["sus-304", "iso-m", "naco-coating", "kc"],
    sourceAuthority: "AISI 316 / ASTM A240 / Sandvik Coromant Material Card",
  },
  "inconel-718": {
    id: "inconel-718",
    korean: "Inconel 718",
    english: "Inconel 718 (UNS N07718)",
    category: "material",
    definition: {
      beginner: "제트엔진 터빈용 극한 금속. 700°C에서도 강철만큼 단단. 깎기 극악 난이도. 공구 수명이 보통 강의 1/10.",
      intermediate: "니켈-크롬 초내열합금. 가스터빈/제트엔진 터빈 블레이드용. 일반 탄소강 대비 Vc 1/4~1/5로 매우 느림.",
      expert: "조성: Ni 50-55%, Cr 17-21%, Fe balance, Nb 4.75-5.5%, Mo 2.8-3.3%, Ti 0.65-1.15%. HBW 330-400 (시효후), Rm 1240 MPa. 권장 Vc 30-60 m/min (황삭), 40-80 m/min (다듬질), fz 0.05-0.12 mm, ae ≤0.3×D + chip thinning. 권장 코팅: AlTiN nano-multilayer, nACRo, TiAlSiN. 금기: PCD (Ni 확산), 고속 드라이. 응용: 제트엔진 터빈 디스크·로켓 노즐. 출처: Special Metals Inconel 718 Datasheet + Sandvik Aerospace Guide.",
    },
    whyItMatters: "항공엔진 고부가가치 부품의 80% 사용. 파라미터 1회 실수 = 공구 $300+ 파손 + 블랭크 $5000+ 폐기.",
    realWorldExample: "IN718 터빈디스크 포켓 황삭 ⌀12 4날 AlTiN 엔드밀 Vc 45 m/min, fz 0.08 mm, ap 12 mm, ae 1.8 mm 트로코이달.",
    commonPitfall: "fz를 낮추는 것이 안전하다고 오해 — 0.05 이하로 가면 오히려 공구가 경화층만 문질러 수명 급감.",
    relatedConcepts: ["iso-s", "altin-coating", "naco-coating", "trochoidal", "work-hardening"],
    sourceAuthority: "Special Metals Corp. Inconel 718 Data Sheet / Sandvik Coromant Aerospace",
  },
  "al-6061": {
    id: "al-6061",
    korean: "Al 6061-T6",
    english: "Aluminum 6061-T6",
    category: "material",
    definition: {
      beginner: "가장 흔한 가공용 알루미늄. 항공·자전거 프레임·방열판에 사용. 빠르게 깎기 좋음.",
      intermediate: "6xxx계(Mg-Si). T6는 용체화+인공시효로 강도 극대화. 우수한 가공성·용접성 겸비. 권장 Vc 800-2500 m/min.",
      expert: "조성: Si 0.6%, Mg 1.0%, Cu 0.28%, Cr 0.2%. T6 시효경화 완료상태. HBW 95±5, Rm 310 MPa. 권장 Vc 1000-2500 m/min (Helical Aluminum 3날), fz 0.10-0.20 mm at ⌀10, ap 1×D 풀슬롯 가능. 권장 코팅: Uncoated polished 또는 ZrN/DLC (응착 방지). 금기: AlTiN (Al 응착). 응용: 항공기 2차 구조·광학 마운트·자동차 섀시. 출처: ASM Metals Handbook Vol.2 + Helical Speeds&Feeds Chart.",
    },
    whyItMatters: "CNC 샵의 70% 이상이 만지는 기준 재질. 모든 Al 파라미터의 출발점.",
    realWorldExample: "6061-T6 브라켓 포켓 ⌀10 3날 미코팅 Vc 2000 m/min (RPM 63,700), fz 0.15 mm, ap 10 mm 풀슬롯 1패스.",
    commonPitfall: "O(어닐링) 재료에 T6 파라미터 적용 시 끈적한 BUE 발생. 열처리 기호 확인 필수.",
    relatedConcepts: ["wrought-al", "al-7075", "uncoated", "dlc-coating", "iso-n"],
    sourceAuthority: "ASM Metals Handbook Vol.2 / Helical Solutions Aluminum Technical Data",
  },
  "al-7075": {
    id: "al-7075",
    korean: "Al 7075-T6",
    english: "Aluminum 7075-T6",
    category: "material",
    definition: {
      beginner: "6061보다 훨씬 단단한 항공용 알루미늄. '알루미늄 중의 강철'. 전투기·군수에 쓰임.",
      intermediate: "7xxx계(Zn-Mg). 고강도 항공용. HBW 150 수준으로 6061의 1.6배. 권장 Vc 700-2000 m/min.",
      expert: "조성: Zn 5.6%, Mg 2.5%, Cu 1.6%, Cr 0.23%. T6 상태. HBW 150±10, Rm 570 MPa (6061의 1.8배). 권장 Vc 900-2200 m/min, fz 0.08-0.15 mm at ⌀10. 권장 코팅: ZrN, DLC (6061 대비 열부하 큼). 금기: AlTiN, 습식 저압 (칩 감김). 응용: 전투기 날개 스파·사격용 총열 블록·고응력 항공부품. 출처: ASM Metals Handbook Vol.2.",
    },
    whyItMatters: "항공 1차 구조재. 6061 대비 강도 1.8배지만 내식성 낮아 애노다이징 필수 — 치수공차 엄격.",
    realWorldExample: "7075-T6 항공 리브 포켓 ⌀10 3날 ZrN Vc 1800 m/min, fz 0.12 mm, ap 10 mm, 고압 쿨런트 70bar.",
    commonPitfall: "6061 파라미터 그대로 적용 시 공구수명 50% 단축. Vc -10%, fz -20% 보정 출발.",
    relatedConcepts: ["al-6061", "wrought-al", "zrn-coating", "dlc-coating", "iso-n"],
    sourceAuthority: "ASM Metals Handbook Vol.2 / Helical Solutions 7075 Application Note",
  },
  "kc": {
    id: "kc",
    korean: "비절삭저항 kc",
    english: "Specific Cutting Force (kc)",
    category: "material",
    definition: {
      beginner: "재료를 1 mm² 단면으로 깎을 때 필요한 힘(N). 재료마다 다르고 값이 클수록 힘센 기계가 필요.",
      intermediate: "kc [N/mm²] = 절삭력 / (ap × fz). 재료별 고유값으로 스핀들 동력·토크 계산의 핵심. Kienzle 공식의 기본 파라미터.",
      expert: "Kienzle 공식: Fc = kc1.1 × b × h^(1-mc). kc1.1은 h=b=1mm 기준 비저항, mc는 경화지수. 대표값: Al 6061 kc=750, Steel S45C kc=2100, SUS304 kc=2700, SUS316 kc=2900, Inconel 718 kc=3500-4200, Ti6Al4V kc=2000, GC250 kc=1100, A380 kc=700 N/mm². 공칭 Pc[kW] = (kc × ap × ae × fz × z × n) / (60 × 10^6 × η). 출처: Sandvik Coromant Rotating Tools Handbook Ch.B / Kienzle DIN 6584.",
    },
    formula: "Fc [N] = kc × ap × h_m,  Pc [kW] = Fc × Vc / (60 × 1000 × η)",
    whyItMatters: "스핀들 동력 부족 판정의 유일한 정량 지표. kc를 무시하면 과부하로 스핀들 베어링 조기 손상.",
    realWorldExample: "Inconel 718에서 ⌀12 4날 ap 12 ae 2 fz 0.08로 가공 시 Pc = 3500×12×2×0.08×4×1200/(60e6×0.8) ≈ 13.4 kW — 15 kW 스핀들 거의 한계.",
    commonPitfall: "kc는 상수가 아님. 가공 두께 h가 작아지면 kc 증가(Kienzle mc 효과) — 다듬질에서 의외로 동력 부족.",
    relatedConcepts: ["iso-p", "iso-m", "iso-s", "inconel-718", "sfm"],
    sourceAuthority: "DIN 6584 / Sandvik Coromant Rotating Tools Handbook / Kienzle 1952",
  },
  "hbw-hrc-scales": {
    id: "hbw-hrc-scales",
    korean: "경도 스케일 HBW/HBS/HRB/HRC",
    english: "Hardness Scales (Brinell / Rockwell B / Rockwell C)",
    category: "material",
    definition: {
      beginner: "재료가 얼마나 단단한지 나타내는 숫자. 종류가 여러 개라 스케일 이름을 꼭 같이 봐야 함.",
      intermediate: "HBW: 초경볼 Brinell / HBS: 강구 Brinell(구식) / HRB: 록웰 B(연질) / HRC: 록웰 C(경질 HRC 20-65). 재질별 적합 스케일 다름 — HRC는 담금질강, HBW는 주철·비철·연강 공용.",
      expert: "HBW 10/3000 = ⌀10mm 초경볼 + 3000kgf 하중, d[mm] 측정 후 HBW = 2F / (πD(D-√(D²-d²))). HRC = 100 - (e/0.002mm) where e는 브레일 침투깊이. 환산: HRC 20 ≈ HBW 225, HRC 30 ≈ HBW 285, HRC 40 ≈ HBW 375, HRC 50 ≈ HBW 475(외삽), HRC 60 ≈ HBW 620(외삽, 부정확). Vickers HV 환산은 HV ≈ HBW × 1.05 (HBW<400). ISO 18265 환산표 권장. 출처: ISO 6506(HBW), ISO 6508(HRC), ISO 18265(환산).",
    },
    whyItMatters: "Vc 결정의 1차 입력값. 'SM45C HBW 200'인지 'HBW 280'인지에 따라 Vc 권장이 20% 이상 차이.",
    realWorldExample: "금형 STD61 '경도 HRC 52' 사양 → HBW 환산 500 → AlTiN 권장 Vc 130 m/min (연강 220의 60%).",
    commonPitfall: "HBW 값이 400 초과면 Brinell 신뢰도 저하 — 경화강은 반드시 HRC로 표기할 것. HB와 HBW 혼용 주의 (HB=구식 강구).",
    relatedConcepts: ["iso-h", "iso-p", "iso-s", "kc"],
    sourceAuthority: "ISO 6506-1:2014 (Brinell), ISO 6508-1:2016 (Rockwell), ISO 18265:2013 (Conversion)",
  },
}
