// SPDX-License-Identifier: MIT
// YG-1 ARIA Simulator v3 — 교육 콘텐츠: speeds (절삭속도 계열)
import type { EducationDb } from "../education-content"

export const SPEEDS_ENTRIES: EducationDb = {
  sfm: {
    id: "sfm",
    korean: "절삭속도 SFM (Surface Feet per Minute)",
    english: "Surface Feet per Minute",
    category: "speeds",
    definition: {
      beginner: "공구 날 끝이 1분 동안 재료 표면을 몇 피트(약 30cm) 스치는지 나타내는 속도. 재료마다 적정 걸음 속도가 정해져 있음.",
      intermediate: "표면속도(영미식). 공구 외주가 가공물 표면을 스치는 선속도(ft/min). 재질·코팅이 결정하는 1차 절삭 변수.",
      expert: "SFM = π·D·RPM / 12 (D in inch). Al 6061 ~1000 SFM, 1018 탄소강 ~350 SFM, SUS304 ~300 SFM, Ti-6Al-4V ~150 SFM, Inconel 718 ~80 SFM (코팅 초경 기준). 경도·냉각·공구수명 목표에 따라 Taylor 식 V·T^n=C로 보정. 출처: Machinery's Handbook 30th ed., Sandvik Coromant Handbook Ch.2.",
    },
    formula: "SFM = π·D(inch)·RPM / 12",
    whyItMatters: "SFM이 권장치 대비 너무 높으면 공구 수명 급락·열화 마모, 너무 낮으면 BUE(구성인선) 발생으로 표면조도와 치수가 깨진다.",
    realWorldExample: "⌀0.5in(12.7mm) 초경 엔드밀로 1018강 가공 시 SFM 350 → RPM ≈ 2675. Al 6061이면 SFM 1000 → RPM ≈ 7640.",
    commonPitfall: "HSS 권장치(SFM)를 초경 공구에 그대로 쓰면 공구 성능의 1/3만 쓰는 셈. 공구 재질·코팅별 표를 분리해서 봐야 한다.",
    relatedConcepts: ["rpm", "vc", "ipt", "mrr"],
    sourceAuthority: "Machinery's Handbook 30th ed. / Sandvik Coromant Handbook Ch.2",
  },
  rpm: {
    id: "rpm",
    korean: "회전수 RPM (Revolutions Per Minute)",
    english: "Revolutions Per Minute",
    category: "speeds",
    definition: {
      beginner: "공구(또는 공작물)가 1분 동안 몇 바퀴 도는지. 선풍기 단수처럼 스핀들이 얼마나 빨리 돌고 있는지를 나타냄.",
      intermediate: "스핀들 회전속도(rev/min). SFM/Vc와 공구 직경 D로부터 역산해서 설정하는 종속 변수.",
      expert: "RPM = 12·SFM / (π·D_inch) = 1000·Vc / (π·D_mm). 머신 스핀들 정격 RPM·토크 곡선의 한계 내에서만 유효. 고속 스핀들의 저 RPM 구간은 토크 부족으로 실질 MRR이 떨어진다. 출처: Kennametal NOVO / ASM Metals Handbook Vol.16.",
    },
    formula: "RPM = 12·SFM / (π·D_inch) = 1000·Vc / (π·D_mm)",
    whyItMatters: "RPM은 직접 설정하는 값이지만 본질은 SFM(Vc)의 종속 변수다. 공구 직경을 바꾸면 같은 SFM이라도 RPM을 다시 계산해야 한다.",
    realWorldExample: "⌀10mm 초경 엔드밀로 SUS304 가공 시 Vc=120 m/min → RPM ≈ 3820. ⌀6mm로 바꾸면 같은 Vc에서 RPM ≈ 6366.",
    commonPitfall: "공구 바꾸고 RPM을 그대로 두면 작은 공구는 실제 Vc가 절반으로 떨어져 BUE가 난다.",
    relatedConcepts: ["sfm", "vc", "n", "ipm"],
    sourceAuthority: "Kennametal NOVO Technical Guide",
  },
  ipt: {
    id: "ipt",
    korean: "날당 이송 IPT (Inches Per Tooth)",
    english: "Inches Per Tooth",
    category: "speeds",
    definition: {
      beginner: "날 하나가 한 번 지나갈 때 공구가 앞으로 나아가는 거리(inch). 칼질 한 번에 도마 위 재료를 얼마나 미는가와 같음.",
      intermediate: "날당 이송량(chip load per tooth, in/tooth). 칩 두께를 결정하는 핵심 변수.",
      expert: "IPT = IPM / (RPM·Z). 초경 엔드밀 기준: Al ⌀10mm 0.003~0.006in, 강 ⌀10mm 0.002~0.004in, SUS 0.0015~0.003in. RDOC<D/2일 때 chip thinning 보정 필요(h_ex = IPT·2·√(RDOC/D - (RDOC/D)^2)). 출처: Harvey Performance MAP User Guide §Chip Thinning.",
    },
    formula: "IPT = IPM / (RPM·Z)",
    whyItMatters: "IPT가 너무 작으면 날이 재료를 깎지 못하고 문질러서 마모(rubbing)하고, 너무 크면 날 결손(chipping). 공구수명의 가장 큰 지배 변수.",
    realWorldExample: "⌀10mm 4날 엔드밀, RPM 3820, IPT 0.003in(≈0.076mm) → IPM = 3820·4·0.003 ≈ 45.8 in/min.",
    commonPitfall: "측면 가공(RDOC ≪ D)에서 chip thinning 보정 없이 카탈로그 IPT를 그대로 쓰면 실제 칩이 너무 얇아 rubbing이 일어난다.",
    relatedConcepts: ["ipm", "fz", "ipr", "rpm"],
    sourceAuthority: "Harvey Performance MAP User Guide",
  },
  ipm: {
    id: "ipm",
    korean: "분당 이송 IPM (Inches Per Minute)",
    english: "Inches Per Minute",
    category: "speeds",
    definition: {
      beginner: "공구가 1분 동안 몇 inch 나아가는지. 가공 테이블이 움직이는 실제 속도. G코드 F값에 그대로 들어감.",
      intermediate: "테이블 이송속도(feed rate, in/min). CAM이 포스트에서 F 워드로 출력하는 최종 값.",
      expert: "IPM = RPM · Z · IPT. 기계 가감속(look-ahead)·서보 대역폭·스핀들 파워의 한계로 상한이 제한됨. 고 IPM에서는 코너에서 가공기 jerk·공구 deflection이 치수 오차의 주범. 출처: Sandvik Coromant Handbook Ch.3.",
    },
    formula: "IPM = RPM · Z · IPT",
    whyItMatters: "IPM은 사이클타임에 직접 비례. 단 기계 동특성 한계를 넘으면 값만 크고 실제로는 못 따라가서 코너 언더컷·진동이 난다.",
    realWorldExample: "⌀10mm 4날, RPM 3820, IPT 0.003in → IPM ≈ 45.8 in/min(≈ 1164 mm/min, 즉 Vf ≈ 1164).",
    commonPitfall: "작은 공구의 IPM을 크게 설정하고 소형 포켓에 넣으면 look-ahead가 끊겨 실이송이 설정치의 절반도 못 나온다.",
    relatedConcepts: ["ipt", "vf", "rpm", "mrr"],
    sourceAuthority: "Sandvik Coromant Handbook Ch.3",
  },
  ipr: {
    id: "ipr",
    korean: "회전당 이송 IPR (Inches Per Revolution)",
    english: "Inches Per Revolution",
    category: "speeds",
    definition: {
      beginner: "공구가 한 바퀴 도는 동안 얼마나 앞으로 나가는지(inch). 드릴·선삭에서 주로 쓰는 이송 단위.",
      intermediate: "회전당 이송량(in/rev). 드릴링·보링·선삭에서 F를 지정하는 방식. 밀링 IPT와는 Z(날수) 배만큼 차이.",
      expert: "IPR = IPT · Z = IPM / RPM. ⌀10mm HSS 드릴 on 1018강 IPR 0.005~0.008 in/rev. 드릴은 IPR이 칩 두께를 결정하고, 과소 시 csp(중심부) 마찰 발열·파손. 출처: Kennametal Drilling Application Guide.",
    },
    formula: "IPR = IPM / RPM = IPT · Z",
    whyItMatters: "드릴링에서 IPR이 너무 작으면 chisel edge가 재료를 문질러 드릴이 소부(burn)되고, 크면 웹(web)이 부러진다.",
    realWorldExample: "⌀10mm 탄소강 드릴링, RPM 1500, IPR 0.006in → IPM = 1500·0.006 = 9 in/min(≈ 229 mm/min).",
    commonPitfall: "밀링 IPT 감각으로 드릴 IPR을 잡으면 지나치게 작아서 드릴 날이 타버린다. 드릴은 원래 IPR이 크다.",
    relatedConcepts: ["ipt", "ipm", "rpm"],
    sourceAuthority: "Kennametal Drilling Application Guide",
  },
  fz: {
    id: "fz",
    korean: "날당 이송 fz (metric)",
    english: "Feed per Tooth (metric)",
    category: "speeds",
    definition: {
      beginner: "IPT의 미터 버전. 날 하나가 지나갈 때 공구가 앞으로 몇 mm 나아가는지. 칩 두께를 정하는 값.",
      intermediate: "날당 이송량 fz [mm/tooth]. Vf·n·z로부터 역산. ISO/메트릭 카탈로그의 표준 표기.",
      expert: "fz = Vf / (n·z) [mm/tooth]. ⌀10mm 초경 4날 기준: Al 0.08~0.15, 강 0.05~0.10, SUS304 0.04~0.08, Inconel 0.03~0.05. 측면 가공 시 chip thinning 보정 hex = fz·2·√(ae/D − (ae/D)^2). 출처: Sandvik Coromant Handbook Ch.3 / ISO 3002-1.",
    },
    formula: "fz = Vf / (n · z)",
    whyItMatters: "fz가 권장 범위 밖이면 날이 문지르거나 결손. 공구수명 그래프의 가장 가파른 기울기를 가진 변수.",
    realWorldExample: "⌀10mm 4날 엔드밀로 SUS304 슬로팅, n=3820 RPM, fz=0.05 mm/tooth → Vf = 3820·4·0.05 = 764 mm/min.",
    commonPitfall: "얇은 측면절삭(ae=0.1D)에서 hex 보정 없이 카탈로그 fz를 그대로 입력하면 실칩이 1/3 두께라 rubbing.",
    relatedConcepts: ["ipt", "vc", "vf", "n"],
    sourceAuthority: "Sandvik Coromant Handbook Ch.3 / ISO 3002-1",
  },
  vc: {
    id: "vc",
    korean: "절삭속도 Vc (metric)",
    english: "Cutting Speed (metric)",
    category: "speeds",
    definition: {
      beginner: "SFM의 미터 버전. 공구 날 끝이 1분 동안 표면을 몇 m 스치는지(m/min). 재료마다 정해진 걸음 속도.",
      intermediate: "절삭속도 Vc [m/min]. ISO 표기. 공구 재질·피삭재·코팅이 결정하는 1차 변수.",
      expert: "Vc = π·D·n / 1000 [m/min]. 초경 코팅 기준: Al 6061 ~300, 1018 ~120, SUS304 ~120, Ti-6Al-4V ~60, Inconel 718 ~30. Taylor V·T^n=C, n(초경)=0.2~0.4. 고속절삭(HSM)은 이 값을 2~5배까지 끌어올림. 출처: Sandvik Coromant Handbook Ch.2 / ASM Vol.16.",
    },
    formula: "Vc = π·D·n / 1000",
    whyItMatters: "Vc가 너무 높으면 공구 날이 적열되어 수명이 지수적으로 감소(Taylor 식), 너무 낮으면 BUE·표면조도 악화.",
    realWorldExample: "⌀10mm 엔드밀로 SUS304 가공 시 Vc=120 m/min → n = 1000·120 / (π·10) ≈ 3820 RPM.",
    commonPitfall: "Vc 권장치를 공구 수명 15min 기준으로 잡은 표를 60min 장시간 가공에 그대로 쓰면 수명이 급락한다.",
    relatedConcepts: ["sfm", "n", "fz", "vf"],
    sourceAuthority: "Sandvik Coromant Handbook Ch.2 / Taylor's Tool Life Equation (1907)",
  },
  vf: {
    id: "vf",
    korean: "테이블 이송 Vf (metric)",
    english: "Feed Rate (metric)",
    category: "speeds",
    definition: {
      beginner: "IPM의 미터 버전. 테이블이 1분 동안 몇 mm 움직이는지(mm/min). G코드 F값으로 들어가는 값.",
      intermediate: "이송속도 Vf [mm/min]. CAM 포스트의 F 워드. 기계 가감속·서보 응답의 한계 안에서 유효.",
      expert: "Vf = fz · z · n [mm/min]. 상한은 머신 가감속(look-ahead)·스핀들 토크·공구 deflection으로 결정. 소형 공구는 deflection으로 실제 경로가 F값보다 안쪽으로 들어간다. 출처: Sandvik Coromant Handbook Ch.3.",
    },
    formula: "Vf = fz · z · n",
    whyItMatters: "Vf는 사이클타임에 직선 비례하지만, 기계 동특성 한계를 넘으면 실이송이 설정치보다 작아 ROI가 떨어진다.",
    realWorldExample: "⌀10mm 4날, n=3820 RPM, fz=0.05 → Vf = 3820·4·0.05 = 764 mm/min.",
    commonPitfall: "F값만 올리고 가감속·look-ahead 파라미터를 건드리지 않으면 코너에서 실제 이송이 절반 이하로 떨어진다.",
    relatedConcepts: ["ipm", "fz", "n", "mrr"],
    sourceAuthority: "Sandvik Coromant Handbook Ch.3",
  },
  n: {
    id: "n",
    korean: "회전수 n (metric RPM)",
    english: "Spindle Speed (metric)",
    category: "speeds",
    definition: {
      beginner: "RPM과 똑같은 말. 미터계 카탈로그에서 쓰는 기호. 스핀들이 1분에 몇 바퀴 도는지.",
      intermediate: "스핀들 회전속도 n [rev/min, min^-1]. ISO 표기. Vc와 D에서 유도되는 종속 변수.",
      expert: "n = 1000·Vc / (π·D) [min^-1]. 스핀들 정격 RPM·출력 곡선에 종속. 저RPM 대역은 토크는 크지만 Vc가 부족해 BUE, 고RPM 대역은 Vc는 충분하지만 토크가 부족해 MRR이 제한. 출처: ISO 3002-1.",
    },
    formula: "n = 1000·Vc / (π·D)",
    whyItMatters: "공구 직경이 바뀔 때마다 같은 Vc를 유지하려면 n을 다시 계산해야 한다. 이걸 놓치면 작은 공구가 느리게, 큰 공구가 너무 빠르게 돈다.",
    realWorldExample: "SUS304, Vc=120 m/min. ⌀10mm → n ≈ 3820 RPM. ⌀6mm → n ≈ 6366 RPM. ⌀20mm → n ≈ 1910 RPM.",
    commonPitfall: "다중 공구 프로그램에서 공구별 n을 재계산하지 않고 공통 S값을 쓰면 일부 공구는 극단적 Vc에서 돈다.",
    relatedConcepts: ["rpm", "vc", "vf"],
    sourceAuthority: "ISO 3002-1 / Sandvik Coromant Handbook Ch.2",
  },
  mrr: {
    id: "mrr",
    korean: "금속제거율 MRR (Material Removal Rate)",
    english: "Material Removal Rate",
    category: "speeds",
    definition: {
      beginner: "1분 동안 깎아낸 재료의 부피(cm³/min 또는 in³/min). 가공 생산성을 한 숫자로 나타낸 값.",
      intermediate: "금속제거율 Q [cm³/min]. 밀링에서 Q = ae·ap·Vf / 1000. 스핀들 파워·공구 수명과 맞바꾸는 KPI.",
      expert: "Q = ae·ap·Vf / 1000 [cm³/min]. 필요 스핀들 파워 Pc = Q·kc / (60·10^3·η), kc는 비절삭력(강 2000~3000 N/mm², Al 800 N/mm²). HSM/트로코이달은 ap 크고 ae 작게 가서 동일 Q를 공구수명↑로 달성. 출처: Sandvik Coromant Handbook Ch.A / Kienzle 식.",
    },
    formula: "Q = ae · ap · Vf / 1000  [cm³/min]",
    whyItMatters: "MRR은 곧 돈. 단 스핀들 파워·공구 수명과 맞바꿔야 하는 값이라, 무작정 올리면 공구가 1개 분에 1개씩 나간다.",
    realWorldExample: "ap=10mm, ae=2mm, Vf=800 mm/min → Q = 10·2·800 / 1000 = 16 cm³/min. SUS304 kc≈2500이면 Pc ≈ 0.67 kW.",
    commonPitfall: "MRR만 보고 파라미터를 뽑으면 공구 수명이 수십 분의 일로 떨어져 툴 교체시간 포함 실질 생산성은 오히려 감소.",
    relatedConcepts: ["vf", "vc", "fz"],
    sourceAuthority: "Sandvik Coromant Handbook Ch.A / Kienzle-Victor 비절삭력 모델",
  },
}
