// SPDX-License-Identifier: MIT
// YG-1 ARIA Simulator v3 — 교육 콘텐츠: tool-shape (공구 형상 계열)
import type { EducationDb } from "../education-content"

export const TOOL_SHAPE_ENTRIES: EducationDb = {
  "square-endmill": {
    id: "square-endmill",
    korean: "스퀘어 엔드밀 (Square Endmill / Flat Endmill)",
    english: "Square (Flat) Endmill",
    category: "tool-shape",
    definition: {
      beginner: "끝이 평평한(직각) 엔드밀. 바닥이 평면인 홈이나 단(shoulder)을 깎을 때 쓰는 가장 기본 공구.",
      intermediate: "플랫 엔드밀. 바닥 평면·직각 숄더·슬롯 가공용 표준 공구. 코너는 날카로워 응력집중이 큼.",
      expert: "Square endmill, corner radius ≈ 0. 유효 직경 D_eff = D(절입 깊이 무관). 직각 코너로 인한 응력집중으로 코너 치핑이 최빈 고장모드, 경가공·내열합금에는 corner-radius 공구가 권장됨. 출처: Sandvik Coromant Handbook Ch.3 / Harvey Performance Catalog.",
    },
    formula: "D_eff = D",
    whyItMatters: "바닥 평면·직각 어깨를 만드는 유일한 표준 공구. 하지만 코너가 약해 고부하 가공에서는 코너R 공구로 교체해야 한다.",
    realWorldExample: "⌀10mm 4날 스퀘어로 Al 6061 슬롯 ap=10mm, ae=10mm(슬로팅), Vc=300 m/min, fz=0.08mm.",
    commonPitfall: "경질 재료(SUS·Inconel)에서 스퀘어로 숄더링하면 코너가 2~3패스 만에 치핑. 이런 경우 corner-radius 0.5mm를 선택.",
    relatedConcepts: ["corner-radius", "ball-nose", "flutes", "cutter-diameter"],
    sourceAuthority: "Harvey Performance Endmill Catalog",
  },
  "ball-nose": {
    id: "ball-nose",
    korean: "볼노즈 엔드밀 (Ball Nose)",
    english: "Ball Nose Endmill",
    category: "tool-shape",
    definition: {
      beginner: "끝이 동그란(반구) 엔드밀. 곡면·금형처럼 둥근 표면을 깎을 때 쓰는 공구.",
      intermediate: "볼엔드밀, R = D/2. 3D 곡면·금형 마무리·컨투어링에 사용. 중심부(팁)는 절삭속도가 0이라 절삭이 어려움.",
      expert: "Ball nose endmill. 유효 직경 D_eff = 2·√(D·ap − ap²) (ap ≤ R). 팁 중심 Vc=0이라 정삭 시 경사면 가공(축 기울임)으로 D_eff를 키워 Vc 확보 필수. scallop height h = ae²/(8·R). 출처: Sandvik Coromant Die & Mould Application Guide.",
    },
    formula: "D_eff = 2·√(D·ap − ap²),  scallop h = ae²/(8R)",
    whyItMatters: "곡면 가공 표준이지만 팁 중심 Vc=0이 치명적. 수직 가공 시 팁이 문지르기만 하고 안 깎여 공구가 망가진다.",
    realWorldExample: "⌀10mm 볼로 금형 마무리 ap=0.5mm → D_eff = 2·√(10·0.5 − 0.25) ≈ 4.36mm. Vc 설정은 이 값 기준.",
    commonPitfall: "수직 컨투어링(축 기울기 0°)에서 카탈로그 Vc 그대로 쓰면 실 Vc는 0 근방. 경사 가공이나 tilt 5°~15° 필수.",
    relatedConcepts: ["d-eff", "corner-radius", "square-endmill"],
    sourceAuthority: "Sandvik Coromant Die & Mould Application Guide",
  },
  "corner-radius": {
    id: "corner-radius",
    korean: "코너 R 엔드밀 (Corner Radius / Bull Nose)",
    english: "Corner Radius Endmill",
    category: "tool-shape",
    definition: {
      beginner: "끝 모서리에만 작은 동그라미(R)가 있는 엔드밀. 스퀘어와 볼노즈의 중간 형태.",
      intermediate: "Corner radius endmill (Bull nose). 코너에 R 0.2~2mm가 있어 응력집중 감소, 공구수명·표면조도에 유리.",
      expert: "Corner radius Rc [mm], 일반적으로 0.1D ~ 0.3D. 코너 응력을 분산시켜 공구수명 1.5~3배 증가(대비 스퀘어). 바닥면에 R 자국이 남으므로 완전 직각 숄더가 필요하면 부적합. 출처: Kennametal NOVO / Harvey Performance MAP.",
    },
    formula: "Rc ≈ 0.1·D ~ 0.3·D (권장)",
    whyItMatters: "경질 재료 고부하 가공에서 공구 수명의 핵심. 스퀘어 → 코너R로 바꾸는 것만으로 수명이 2배 이상 느는 경우가 많다.",
    realWorldExample: "⌀10mm · Rc=1mm 엔드밀로 SUS304 shouldering: ap=10mm, ae=3mm, fz=0.06mm, 수명 스퀘어 대비 약 2.2배.",
    commonPitfall: "바닥 완전 직각이 필요한 도면에 코너R 공구를 써 바닥 R 자국이 남아 검사 탈락.",
    relatedConcepts: ["square-endmill", "ball-nose", "edge-hone"],
    sourceAuthority: "Harvey Performance MAP / Kennametal NOVO",
  },
  "chamfer-tool": {
    id: "chamfer-tool",
    korean: "챔퍼 공구 (Chamfer Mill / 모따기)",
    english: "Chamfer Mill",
    category: "tool-shape",
    definition: {
      beginner: "모서리를 비스듬히 깎는(모따기) 공구. 날 끝이 원뿔처럼 생긴 엔드밀.",
      intermediate: "Chamfer mill. 일반 각도 45°·60°·82° 등. 모따기·디버링(deburring)·스팟 가공에 사용.",
      expert: "Chamfer mill with included angle 2α (흔히 90°, 즉 α=45°). 절입 깊이 z에서 유효 직경 D_eff = D_tip + 2·z·tan(α). Vc 설정은 D_eff 기준, 깊이에 따라 실질 Vc가 변하는 것이 함정. 출처: Harvey Performance Chamfer Mill Application Guide.",
    },
    formula: "D_eff(z) = D_tip + 2·z·tan(α)",
    whyItMatters: "깊이에 따라 유효 직경이 달라져서 동일 RPM에서도 Vc가 2~3배 변한다. 조건 설정 실수가 가장 많은 공구.",
    realWorldExample: "45° 챔퍼 D_tip=2mm, 0.5mm 모따기 → D_eff = 2 + 2·0.5·1 = 3mm. 1mm 모따기 → D_eff = 4mm.",
    commonPitfall: "D_tip으로 RPM 계산 후 큰 모따기를 주면 실 Vc가 2배로 뛰어 공구 소부. D_eff 기준으로 다시 계산해야 함.",
    relatedConcepts: ["d-eff", "square-endmill", "cutter-diameter"],
    sourceAuthority: "Harvey Performance Chamfer Mill Application Guide",
  },
  flutes: {
    id: "flutes",
    korean: "플루트 / 절삭날 수 (Flutes, Z)",
    english: "Flutes (Number of Teeth, Z)",
    category: "tool-shape",
    definition: {
      beginner: "엔드밀 몸통에 파인 나선홈(=절삭날)의 개수. 2날, 3날, 4날, 6날 등이 있음.",
      intermediate: "플루트 수 Z. 날수↑면 Vf↑ 가능하지만 칩 배출 공간↓. 재질·가공모드에 따라 선택.",
      expert: "Z [-]. Vf = fz·Z·n이므로 날수↑는 Vf↑·MRR↑. 그러나 flute 단면적↓ → 칩 배출 저하. 권장: Al Z=2~3(큰 칩 공간), 강 Z=4, SUS/Inconel Z=5~7(안정·고이송), 고경도강(HRC>50) Z=6~9. 출처: Sandvik Coromant Handbook Ch.3.",
    },
    formula: "Vf = fz · Z · n",
    whyItMatters: "같은 fz라도 Z를 늘리면 이송이 비례 증가. 단 알루미늄 같은 긴 칩 재료는 Z↑ 시 칩이 막혀 공구가 깨진다.",
    realWorldExample: "⌀10mm SUS304 측면: Z=4 → Vf=764, Z=6 → Vf=1146 mm/min(같은 fz=0.05).",
    commonPitfall: "Al에 6날 엔드밀을 쓰면 flute 공간 부족으로 칩 재절삭(recutting) 발생 → 공구·표면 다 망가짐.",
    relatedConcepts: ["variable-helix", "ipt", "fz", "vf"],
    sourceAuthority: "Sandvik Coromant Handbook Ch.3",
  },
  "variable-helix": {
    id: "variable-helix",
    korean: "Variable Helix / 불균일 나선",
    english: "Variable Helix / Variable Pitch Endmill",
    category: "tool-shape",
    definition: {
      beginner: "날마다 나선 각도나 간격이 살짝 다른 엔드밀. 진동(채터)을 깨뜨려 더 조용하고 오래 가는 공구.",
      intermediate: "Variable helix / variable pitch. 날 간격이나 helix angle이 불균일(예: 35°/37°/38°/36°)해서 규칙적 진동 주파수를 분산.",
      expert: "Variable helix·variable pitch. 규칙 피치는 toothpassing frequency ω_tp = Z·n/60에서 채터 lobe와 공진, 불규칙 피치는 이 공진 에너지를 주파수 분산시켜 안정 lobe 폭 확대. 깊은 ap·긴 stick-out·내열합금에서 특히 유효. 출처: Altintas, Manufacturing Automation (2012) Ch.4.",
    },
    formula: "ω_tp = Z·n / 60  (채터 분산 대상 주파수)",
    whyItMatters: "긴 돌출·깊은 절입에서 regular pitch 공구가 우는 조건이라도 variable helix로 바꾸면 말끔히 들어간다.",
    realWorldExample: "⌀10mm LSO=50mm · SUS304 · ap=15mm 조건에서 regular 38° helix는 채터, 35/37/38/36° variable은 안정.",
    commonPitfall: "Variable 공구는 고가라 일반 얕은 가공에 쓰면 손해. 채터가 실제로 문제가 되는 긴 돌출·깊은 가공에만 투입.",
    relatedConcepts: ["flutes", "stick-out", "adoc"],
    sourceAuthority: "Altintas, Manufacturing Automation, Cambridge Univ. Press (2012)",
  },
  shank: {
    id: "shank",
    korean: "섕크 (Shank)",
    english: "Shank",
    category: "tool-shape",
    definition: {
      beginner: "공구에서 홀더(척)가 잡는 매끈한 부분. 손잡이에 해당하는 영역.",
      intermediate: "Shank. 홀더가 클램핑하는 원통 구간. 규격(h6 등) 공차로 가공되어 홀더와 정밀 정합.",
      expert: "Shank diameter·tolerance (보통 h6, ⌀6/8/10/12/16/20mm 스탠다드). 열박음(shrink-fit)은 h6 섕크 필수, milling chuck는 h5 선호. Weldon flat(평탄부)·Whistle Notch는 고토크 전용 인터페이스. 출처: DIN 1835 / ISO 5413.",
    },
    formula: "섕크 공차: h6 (일반), h5 (열박음 고정밀)",
    whyItMatters: "섕크 공차가 h6이 아니거나 상처가 나면 홀더 정합이 깨져 T.I.R.↑·공구수명↓·표면조도 악화.",
    realWorldExample: "⌀10h6 섕크 엔드밀을 열박음(shrink-fit) 홀더에 장착 시 T.I.R. < 3μm @ 3×D 돌출 달성 가능.",
    commonPitfall: "드로우바로 섕크를 조이다 평탄부(Weldon flat) 없는 공구에 흠집을 내면 이후 정합 불가능해짐.",
    relatedConcepts: ["stick-out", "oal", "cutter-diameter"],
    sourceAuthority: "DIN 1835 / ISO 5413 Tool Shank Standard",
  },
  "edge-hone": {
    id: "edge-hone",
    korean: "에지혼 / 날끝 반경 (Edge Hone / Edge Prep)",
    english: "Edge Hone (Edge Preparation)",
    category: "tool-shape",
    definition: {
      beginner: "날 끝에 아주 작게(수 μm) 둥근 처리를 해놓은 것. 너무 날카로우면 쉽게 깨지기 때문에 일부러 둥글게 만든다.",
      intermediate: "Edge hone, edge prep. 날 끝 반경 rβ [μm]. 코팅 밀착·치핑 방지 목적. 재질·가공모드에 따라 최적값 다름.",
      expert: "Edge radius rβ [μm]. 코팅 초경 일반 10~25μm, 고이송·황삭 30~50μm, 정삭·Al 2~8μm (sharp edge). rβ < fz가 일반적, rβ > fz이면 ploughing(문지름)으로 burr·가공경화. 출처: Denkena & Biermann, CIRP Annals 2014 'Cutting edge geometries'.",
    },
    formula: "조건: rβ < fz (ploughing 회피)",
    whyItMatters: "너무 날카로우면 치핑, 너무 둥글면 rubbing. 재질·fz에 맞는 에지혼이 공구수명의 숨은 1등 변수.",
    realWorldExample: "Ti-6Al-4V 가공 fz=0.05mm(50μm)인데 rβ=30μm 공구 선택. rβ=8μm sharp edge 쓰면 치핑 발생.",
    commonPitfall: "알루미늄 전용 sharp-edge(rβ<5μm) 공구로 강·SUS를 깎으면 즉시 치핑. 재질 대응 에지혼 스펙 확인 필수.",
    relatedConcepts: ["corner-radius", "flutes", "fz"],
    sourceAuthority: "Denkena & Biermann, CIRP Annals — Manufacturing Technology, 2014",
  },
  "cutter-diameter": {
    id: "cutter-diameter",
    korean: "공구 직경 D (Cutter Diameter)",
    english: "Cutter Diameter",
    category: "tool-shape",
    definition: {
      beginner: "공구 날 부분의 지름(mm 또는 inch). ⌀10mm면 직경 10mm라는 뜻.",
      intermediate: "Cutter diameter D [mm]. 공구 선정의 1차 스펙. Vc·n·deflection·MRR 모두 D에 강하게 의존.",
      expert: "D [mm]. n = 1000·Vc/(π·D) (∝1/D), 강성 I ∝ D^4 (deflection ∝ 1/D^4). D 2배 → n 절반, deflection 1/16. 카탈로그 D는 공칭, 실측 허용 공차는 보통 −0.01~−0.03mm(주로 −측 offset). 출처: DIN 6527 / ISO 1641.",
    },
    formula: "n ∝ 1/D,  deflection ∝ 1/D⁴",
    whyItMatters: "공구 하나 바꿀 때 D가 바뀌면 RPM·이송·deflection 전부 재계산 필요. 같은 F값을 돌리면 실 Vc가 완전히 달라진다.",
    realWorldExample: "⌀10 → ⌀6으로 교체: 같은 Vc=120이면 n은 3820 → 6366, 같은 fz면 Vf는 1.67배로 올려야 동일 칩두께.",
    commonPitfall: "소형 D 공구에 대형 공구 파라미터를 그대로 두면 Vc는 낮고 deflection은 폭증 → 치수·수명 모두 파국.",
    relatedConcepts: ["d-eff", "shank", "square-endmill"],
    sourceAuthority: "DIN 6527 / ISO 1641 Solid Endmill Dimensions",
  },
  "d-eff": {
    id: "d-eff",
    korean: "유효 직경 D_eff (Effective Diameter)",
    english: "Effective Cutting Diameter",
    category: "tool-shape",
    definition: {
      beginner: "공구 전체 직경이 아니라, 실제로 재료를 깎고 있는 부분의 직경(mm). 볼노즈·챔퍼에서 중요한 개념.",
      intermediate: "Effective diameter D_eff [mm]. 실제 절삭이 일어나는 지점의 직경. 볼·챔퍼·코너R에서 깊이에 따라 변함.",
      expert: "볼노즈: D_eff = 2·√(D·ap − ap²) (ap ≤ R). 챔퍼(2α): D_eff = D_tip + 2·z·tan(α). Vc_실제 = π·D_eff·n/1000. 기울임(tilt) β 적용 시 ball: D_eff = 2·R·sin(arccos(1 − ap/R) + β). 출처: Sandvik Coromant Die & Mould Guide / Harvey Performance MAP.",
    },
    formula: "Vc_real = π · D_eff · n / 1000",
    whyItMatters: "볼·챔퍼에서 공칭 D로 RPM을 잡으면 실 Vc가 엉뚱한 값이 된다. 공구수명·표면조도·발열 모두 D_eff에서 결정.",
    realWorldExample: "⌀10 볼노즈, ap=1mm → D_eff ≈ 6mm. Vc=120 m/min 원하면 n = 1000·120/(π·6) ≈ 6366, ⌀10 기준 3820이 아님.",
    commonPitfall: "금형 정삭에서 공칭 D로 RPM 설정 → 팁 근방은 Vc가 0에 가까워 공구가 문지르기만 하고 표면이 거칠어짐.",
    relatedConcepts: ["ball-nose", "chamfer-tool", "cutter-diameter"],
    sourceAuthority: "Sandvik Coromant Die & Mould Application Guide",
  },
  series: {
    id: "series",
    korean: "시리즈 (Series, 공구 명명법)",
    english: "Tool Series",
    category: "tool-shape",
    definition: {
      beginner: "공구 카탈로그에서 '이 공구는 어떤 용도·어떤 재료용인지'를 나타내는 계열 이름. YG-1의 Alu-Power, Sandvik CoroMill 등.",
      intermediate: "Tool series. 재질·가공모드(rough/finish)·피삭재군(P/M/K/N/S/H)·코팅조합을 묶은 제품군 분류.",
      expert: "ISO 피삭재 분류: P(강), M(스테인리스), K(주철), N(비철/Al), S(내열합금 Ti·Ni), H(경화강 HRC>45). 각 제조사 시리즈명은 이 구간별로 최적화된 기하·코팅·에지혼 조합. 예: YG-1 Alu-Power(N), X-Power(P/M 범용), V7(S), Sandvik CoroMill Plura·GC1630. 출처: ISO 513 / YG-1·Sandvik 제품 카탈로그.",
    },
    formula: "ISO 513: P · M · K · N · S · H",
    whyItMatters: "피삭재에 맞지 않는 시리즈를 쓰면 수명·표면이 2~5배 차이. 카탈로그의 ISO 컬러코드(P=파랑, N=녹색 등)부터 맞춰야 한다.",
    realWorldExample: "Ti-6Al-4V 가공에 P계 범용(X-Power) 쓰면 수명 20분, S계 전용(V7)이면 60~90분 달성.",
    commonPitfall: "'잘 깎이는 공구'라는 평판만 듣고 P계를 S계 재료에 사용 → 비용은 더 쓰는데 수명은 훨씬 짧음.",
    relatedConcepts: ["edp", "cutter-diameter", "flutes"],
    sourceAuthority: "ISO 513 Classification of Hard Cutting Materials",
  },
  edp: {
    id: "edp",
    korean: "EDP 번호 (EDP / Catalog Number)",
    english: "EDP Number",
    category: "tool-shape",
    definition: {
      beginner: "공구 하나하나에 붙어있는 고유 번호. 주문할 때 이 숫자로 '정확히 이 공구 주세요'라고 지정함.",
      intermediate: "EDP(Electronic Data Processing) number. 제조사별 SKU 코드. 직경·날수·LOC·코팅·코너R을 하나의 번호로 인코딩.",
      expert: "EDP #. 제조사마다 체계 상이. 예: YG-1 EMB EDP '01234'는 직경·플루트·코팅 조합을 고유 식별. Kennametal NOVO·Sandvik CoroPlus는 EDP 기반으로 가공조건을 DB 매칭. 구매·재고·CAM tool library·ERP 연결의 키. 출처: 각 제조사 Master Catalog.",
    },
    formula: "— (식별자)",
    whyItMatters: "동일 스펙이라도 코팅·에지혼 세부가 다르면 EDP가 다르다. EDP 없이 '⌀10 4날'만 말하면 다른 공구가 온다.",
    realWorldExample: "YG-1 'EMB89100' vs 'GMH89100' — 직경/플루트는 같아도 코팅·시리즈 달라 SUS304 수명 차이 2배.",
    commonPitfall: "CAM 라이브러리에서 EDP 없이 '동급 공구'로 치환하면 실가공 조건이 카탈로그와 어긋나 수명 급락.",
    relatedConcepts: ["series", "cutter-diameter", "flutes"],
    sourceAuthority: "YG-1 Master Catalog / Kennametal NOVO / Sandvik CoroPlus",
  },
}
